BEGIN;

-- Seed operacional idempotente dos pacotes fisicos por dominio prioritario.
-- Gerado automaticamente por scripts/automacao_sincronizador_modulos.py.

WITH package_source (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
) AS (
    VALUES
    ('commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'Commerce Fintech Assets', 2, 'priority_domains_v1', ARRAY['MARKETPLACE', 'PAY', 'PLUG', 'UP', 'FINANCAS', 'DIGITAL', 'REAL_ESTATE', 'INSURANCE']::TEXT[], ARRAY['MARKETPLACE.exec.01', 'MARKETPLACE.exec.02', 'PAY.exec.01', 'PAY.exec.02', 'PLUG.exec.01', 'PLUG.exec.02', 'UP.exec.01', 'UP.exec.02', 'MARKETPLACE.exec.03', 'PAY.exec.03', 'FINANCAS.exec.01', 'FINANCAS.exec.02', 'PLUG.exec.03', 'UP.exec.03', 'DIGITAL.exec.01', 'DIGITAL.exec.02', 'REAL_ESTATE.exec.01', 'REAL_ESTATE.exec.02', 'INSURANCE.exec.01', 'INSURANCE.exec.02', 'FINANCAS.exec.03', 'DIGITAL.exec.03', 'REAL_ESTATE.exec.03', 'INSURANCE.exec.03']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"artifacts":[{"artifact_key":"commerce_fintech_assets.ddl.v1","artifact_path":"database/domain-delivery/priority-domains/commerce_fintech_assets/ddl_complement.sql","layer_type":"DDL_COMPLEMENT","target_engine":"postgres"},{"artifact_key":"commerce_fintech_assets.seed.v1","artifact_path":"database/domain-delivery/priority-domains/commerce_fintech_assets/operational_seed.sql","layer_type":"OPERATIONS_SEED","target_engine":"postgres"},{"artifact_key":"commerce_fintech_assets.contract.v1","artifact_path":"contracts/events/priority-domains/commerce_fintech_assets.json","layer_type":"EVENT_CONTRACT","target_engine":"filesystem"}],"backlog_keys":["MARKETPLACE.exec.01","MARKETPLACE.exec.02","PAY.exec.01","PAY.exec.02","PLUG.exec.01","PLUG.exec.02","UP.exec.01","UP.exec.02","MARKETPLACE.exec.03","PAY.exec.03","FINANCAS.exec.01","FINANCAS.exec.02","PLUG.exec.03","UP.exec.03","DIGITAL.exec.01","DIGITAL.exec.02","REAL_ESTATE.exec.01","REAL_ESTATE.exec.02","INSURANCE.exec.01","INSURANCE.exec.02","FINANCAS.exec.03","DIGITAL.exec.03","REAL_ESTATE.exec.03","INSURANCE.exec.03"],"domain_key":"commerce_fintech_assets","domain_label":"Commerce Fintech Assets","event_topics":["marketplace.listing.published","marketplace.cart.checked_out","marketplace.sale.validated","pay.wallet.opened","pay.transaction.posted","pay.settlement.reconciled","plug.device.activated","plug.payment.authorized","plug.advance.requested","up.link.generated","up.conversion.attributed","up.commission.booked","financas.goal.created","financas.roundup.booked","financas.cashflow.closed","digital.asset.minted","digital.asset.transferred","digital.royalty.calculated","real_estate.property.registered","real_estate.listing.published","real_estate.deal.executed","insurance.policy.issued","insurance.claim.opened","insurance.claim.settled"],"modules":["MARKETPLACE","PAY","PLUG","UP","FINANCAS","DIGITAL","REAL_ESTATE","INSURANCE"],"package_key":"commerce_fintech_assets.priority.v1","priority_rank":2}'::JSONB)
)
INSERT INTO domain_delivery_packages (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
)
SELECT
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
FROM package_source
ON CONFLICT (package_key) DO UPDATE SET
    domain_key = EXCLUDED.domain_key,
    domain_label = EXCLUDED.domain_label,
    priority_rank = EXCLUDED.priority_rank,
    package_scope = EXCLUDED.package_scope,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    package_status = EXCLUDED.package_status,
    artifact_manifest_json = EXCLUDED.artifact_manifest_json,
    updated_at = NOW();

WITH artifact_source (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
) AS (
    VALUES
    ('commerce_fintech_assets.ddl.v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'DDL_COMPLEMENT'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/commerce_fintech_assets/ddl_complement.sql', ARRAY['MARKETPLACE', 'PAY', 'PLUG', 'UP', 'FINANCAS', 'DIGITAL', 'REAL_ESTATE', 'INSURANCE']::TEXT[], ARRAY['MARKETPLACE.exec.01', 'MARKETPLACE.exec.02', 'PAY.exec.01', 'PAY.exec.02', 'PLUG.exec.01', 'PLUG.exec.02', 'UP.exec.01', 'UP.exec.02', 'MARKETPLACE.exec.03', 'PAY.exec.03', 'FINANCAS.exec.01', 'FINANCAS.exec.02', 'PLUG.exec.03', 'UP.exec.03', 'DIGITAL.exec.01', 'DIGITAL.exec.02', 'REAL_ESTATE.exec.01', 'REAL_ESTATE.exec.02', 'INSURANCE.exec.01', 'INSURANCE.exec.02', 'FINANCAS.exec.03', 'DIGITAL.exec.03', 'REAL_ESTATE.exec.03', 'INSURANCE.exec.03']::TEXT[], ARRAY[]::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"package_key":"commerce_fintech_assets.priority.v1","priority_rank":2,"views":["v_commerce_fintech_assets_priority_backlog","v_commerce_fintech_assets_delivery_artifacts","v_commerce_fintech_assets_event_contracts"]}'::JSONB),
    ('commerce_fintech_assets.seed.v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'OPERATIONS_SEED'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/commerce_fintech_assets/operational_seed.sql', ARRAY['MARKETPLACE', 'PAY', 'PLUG', 'UP', 'FINANCAS', 'DIGITAL', 'REAL_ESTATE', 'INSURANCE']::TEXT[], ARRAY['MARKETPLACE.exec.01', 'MARKETPLACE.exec.02', 'PAY.exec.01', 'PAY.exec.02', 'PLUG.exec.01', 'PLUG.exec.02', 'UP.exec.01', 'UP.exec.02', 'MARKETPLACE.exec.03', 'PAY.exec.03', 'FINANCAS.exec.01', 'FINANCAS.exec.02', 'PLUG.exec.03', 'UP.exec.03', 'DIGITAL.exec.01', 'DIGITAL.exec.02', 'REAL_ESTATE.exec.01', 'REAL_ESTATE.exec.02', 'INSURANCE.exec.01', 'INSURANCE.exec.02', 'FINANCAS.exec.03', 'DIGITAL.exec.03', 'REAL_ESTATE.exec.03', 'INSURANCE.exec.03']::TEXT[], ARRAY['commerce_fintech_assets.ddl.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"contract_count":24,"package_key":"commerce_fintech_assets.priority.v1","seed_scope":"priority_domain_delivery_v1"}'::JSONB),
    ('commerce_fintech_assets.contract.v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'EVENT_CONTRACT'::domain_delivery_layer_enum, 'filesystem', 'contracts/events/priority-domains/commerce_fintech_assets.json', ARRAY['MARKETPLACE', 'PAY', 'PLUG', 'UP', 'FINANCAS', 'DIGITAL', 'REAL_ESTATE', 'INSURANCE']::TEXT[], ARRAY['MARKETPLACE.exec.01', 'MARKETPLACE.exec.02', 'PAY.exec.01', 'PAY.exec.02', 'PLUG.exec.01', 'PLUG.exec.02', 'UP.exec.01', 'UP.exec.02', 'MARKETPLACE.exec.03', 'PAY.exec.03', 'FINANCAS.exec.01', 'FINANCAS.exec.02', 'PLUG.exec.03', 'UP.exec.03', 'DIGITAL.exec.01', 'DIGITAL.exec.02', 'REAL_ESTATE.exec.01', 'REAL_ESTATE.exec.02', 'INSURANCE.exec.01', 'INSURANCE.exec.02', 'FINANCAS.exec.03', 'DIGITAL.exec.03', 'REAL_ESTATE.exec.03', 'INSURANCE.exec.03']::TEXT[], ARRAY['commerce_fintech_assets.ddl.v1', 'commerce_fintech_assets.seed.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"event_topics":["marketplace.listing.published","marketplace.cart.checked_out","marketplace.sale.validated","pay.wallet.opened","pay.transaction.posted","pay.settlement.reconciled","plug.device.activated","plug.payment.authorized","plug.advance.requested","up.link.generated","up.conversion.attributed","up.commission.booked","financas.goal.created","financas.roundup.booked","financas.cashflow.closed","digital.asset.minted","digital.asset.transferred","digital.royalty.calculated","real_estate.property.registered","real_estate.listing.published","real_estate.deal.executed","insurance.policy.issued","insurance.claim.opened","insurance.claim.settled"],"package_key":"commerce_fintech_assets.priority.v1"}'::JSONB)
)
INSERT INTO domain_delivery_artifacts (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
)
SELECT
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
FROM artifact_source
ON CONFLICT (artifact_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    layer_type = EXCLUDED.layer_type,
    target_engine = EXCLUDED.target_engine,
    artifact_path = EXCLUDED.artifact_path,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    depends_on_keys = EXCLUDED.depends_on_keys,
    artifact_status = EXCLUDED.artifact_status,
    artifact_payload_json = EXCLUDED.artifact_payload_json,
    updated_at = NOW();

WITH contract_source (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
) AS (
    VALUES
    ('MARKETPLACE:marketplace.listing.published:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'MARKETPLACE', 'marketplace.listing.published', '1.0.0', 'painel de seller', ARRAY['STOCK', 'ADS', 'UP', 'painel de seller', 'aprovacao de listing']::TEXT[], ARRAY['marketplace_listings', 'merchant_storefronts', 'sale_validation_events']::TEXT[], ARRAY['merchant_kyb', 'pricing_audit', 'listing_governance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["merchant_kyb","pricing_audit","listing_governance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"marketplace.listing.published"},"evidence_refs":{"items":{"enum":["marketplace_listings","merchant_storefronts","sale_validation_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MARKETPLACE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["listagem local","storefront por merchant","validacao de venda"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["seller","comprador","curador comercial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MARKETPLACE::marketplace.listing.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('MARKETPLACE:marketplace.cart.checked_out:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'MARKETPLACE', 'marketplace.cart.checked_out', '1.0.0', 'painel de seller', ARRAY['STOCK', 'ADS', 'UP', 'painel de seller', 'aprovacao de listing']::TEXT[], ARRAY['marketplace_listings', 'merchant_storefronts', 'sale_validation_events']::TEXT[], ARRAY['merchant_kyb', 'pricing_audit', 'listing_governance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["merchant_kyb","pricing_audit","listing_governance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"marketplace.cart.checked_out"},"evidence_refs":{"items":{"enum":["marketplace_listings","merchant_storefronts","sale_validation_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MARKETPLACE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["listagem local","storefront por merchant","validacao de venda"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["seller","comprador","curador comercial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MARKETPLACE::marketplace.cart.checked_out","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('MARKETPLACE:marketplace.sale.validated:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'MARKETPLACE', 'marketplace.sale.validated', '1.0.0', 'painel de seller', ARRAY['STOCK', 'ADS', 'UP', 'painel de seller', 'aprovacao de listing']::TEXT[], ARRAY['marketplace_listings', 'merchant_storefronts', 'sale_validation_events']::TEXT[], ARRAY['merchant_kyb', 'pricing_audit', 'listing_governance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["merchant_kyb","pricing_audit","listing_governance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"marketplace.sale.validated"},"evidence_refs":{"items":{"enum":["marketplace_listings","merchant_storefronts","sale_validation_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MARKETPLACE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["listagem local","storefront por merchant","validacao de venda"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["seller","comprador","curador comercial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MARKETPLACE::marketplace.sale.validated","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('PAY:pay.wallet.opened:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'PAY', 'pay.wallet.opened', '1.0.0', 'painel financeiro', ARRAY['WALLETS', 'TRANSACTIONS', 'EQUITY', 'painel financeiro', 'monitor de conciliacao']::TEXT[], ARRAY['wallets', 'transactions', 'equity_ledger']::TEXT[], ARRAY['kyc', 'aml_monitoring', 'financial_ledger_immutability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["kyc","aml_monitoring","financial_ledger_immutability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"pay.wallet.opened"},"evidence_refs":{"items":{"enum":["wallets","transactions","equity_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"PAY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["wallet e saldo","ledger atomico","splits e conciliacao"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["titular da wallet","operador financeiro","motor de conciliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"PAY::pay.wallet.opened","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('PAY:pay.transaction.posted:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'PAY', 'pay.transaction.posted', '1.0.0', 'painel financeiro', ARRAY['WALLETS', 'TRANSACTIONS', 'EQUITY', 'painel financeiro', 'monitor de conciliacao']::TEXT[], ARRAY['wallets', 'transactions', 'equity_ledger']::TEXT[], ARRAY['kyc', 'aml_monitoring', 'financial_ledger_immutability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["kyc","aml_monitoring","financial_ledger_immutability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"pay.transaction.posted"},"evidence_refs":{"items":{"enum":["wallets","transactions","equity_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"PAY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["wallet e saldo","ledger atomico","splits e conciliacao"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["titular da wallet","operador financeiro","motor de conciliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"PAY::pay.transaction.posted","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('PAY:pay.settlement.reconciled:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'PAY', 'pay.settlement.reconciled', '1.0.0', 'painel financeiro', ARRAY['WALLETS', 'TRANSACTIONS', 'EQUITY', 'painel financeiro', 'monitor de conciliacao']::TEXT[], ARRAY['wallets', 'transactions', 'equity_ledger']::TEXT[], ARRAY['kyc', 'aml_monitoring', 'financial_ledger_immutability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["kyc","aml_monitoring","financial_ledger_immutability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"pay.settlement.reconciled"},"evidence_refs":{"items":{"enum":["wallets","transactions","equity_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"PAY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["wallet e saldo","ledger atomico","splits e conciliacao"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["titular da wallet","operador financeiro","motor de conciliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"PAY::pay.settlement.reconciled","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('PLUG:plug.device.activated:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'PLUG', 'plug.device.activated', '1.0.0', 'painel de adquirencia', ARRAY['WALLETS', 'BUSINESS', 'painel de adquirencia', 'monitor de terminais']::TEXT[], ARRAY['transactions', 'wallets', 'merchant_storefronts']::TEXT[], ARRAY['pci_boundary', 'mdr_audit', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["pci_boundary","mdr_audit","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"plug.device.activated"},"evidence_refs":{"items":{"enum":["transactions","wallets","merchant_storefronts"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"PLUG"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["tap-to-pay","maquininha","antecipacao de recebivel"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["lojista","operador de adquirencia","comprador presencial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"PLUG::plug.device.activated","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('PLUG:plug.payment.authorized:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'PLUG', 'plug.payment.authorized', '1.0.0', 'painel de adquirencia', ARRAY['WALLETS', 'BUSINESS', 'painel de adquirencia', 'monitor de terminais']::TEXT[], ARRAY['transactions', 'wallets', 'merchant_storefronts']::TEXT[], ARRAY['pci_boundary', 'mdr_audit', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["pci_boundary","mdr_audit","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"plug.payment.authorized"},"evidence_refs":{"items":{"enum":["transactions","wallets","merchant_storefronts"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"PLUG"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["tap-to-pay","maquininha","antecipacao de recebivel"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["lojista","operador de adquirencia","comprador presencial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"PLUG::plug.payment.authorized","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('PLUG:plug.advance.requested:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'PLUG', 'plug.advance.requested', '1.0.0', 'painel de adquirencia', ARRAY['WALLETS', 'BUSINESS', 'painel de adquirencia', 'monitor de terminais']::TEXT[], ARRAY['transactions', 'wallets', 'merchant_storefronts']::TEXT[], ARRAY['pci_boundary', 'mdr_audit', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["pci_boundary","mdr_audit","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"plug.advance.requested"},"evidence_refs":{"items":{"enum":["transactions","wallets","merchant_storefronts"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"PLUG"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["tap-to-pay","maquininha","antecipacao de recebivel"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["lojista","operador de adquirencia","comprador presencial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"PLUG::plug.advance.requested","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('UP:up.link.generated:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'UP', 'up.link.generated', '1.0.0', 'painel de afiliados', ARRAY['INFLUENCERS', 'LOYALTY', 'painel de afiliados', 'monitor de conversao']::TEXT[], ARRAY['transactions', 'pepita_ledger', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['attribution_audit', 'commission_traceability', 'anti_fraud']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["attribution_audit","commission_traceability","anti_fraud"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"up.link.generated"},"evidence_refs":{"items":{"enum":["transactions","pepita_ledger","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"UP"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["indicacao","link de atribuicao","comissao"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["afiliado","merchant","operador de atribuicao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"UP::up.link.generated","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('UP:up.conversion.attributed:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'UP', 'up.conversion.attributed', '1.0.0', 'painel de afiliados', ARRAY['INFLUENCERS', 'LOYALTY', 'painel de afiliados', 'monitor de conversao']::TEXT[], ARRAY['transactions', 'pepita_ledger', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['attribution_audit', 'commission_traceability', 'anti_fraud']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["attribution_audit","commission_traceability","anti_fraud"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"up.conversion.attributed"},"evidence_refs":{"items":{"enum":["transactions","pepita_ledger","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"UP"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["indicacao","link de atribuicao","comissao"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["afiliado","merchant","operador de atribuicao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"UP::up.conversion.attributed","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('UP:up.commission.booked:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'UP', 'up.commission.booked', '1.0.0', 'painel de afiliados', ARRAY['INFLUENCERS', 'LOYALTY', 'painel de afiliados', 'monitor de conversao']::TEXT[], ARRAY['transactions', 'pepita_ledger', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['attribution_audit', 'commission_traceability', 'anti_fraud']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["attribution_audit","commission_traceability","anti_fraud"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"up.commission.booked"},"evidence_refs":{"items":{"enum":["transactions","pepita_ledger","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"UP"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["indicacao","link de atribuicao","comissao"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["afiliado","merchant","operador de atribuicao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"UP::up.commission.booked","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('FINANCAS:financas.goal.created:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'FINANCAS', 'financas.goal.created', '1.0.0', 'painel financeiro pessoal', ARRAY['ADVISOR', 'BUSINESS', 'painel financeiro pessoal', 'monitor de metas']::TEXT[], ARRAY['financial_goals', 'transactions', 'wallets']::TEXT[], ARRAY['financial_privacy', 'goal_audit', 'ledger_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["financial_privacy","goal_audit","ledger_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"financas.goal.created"},"evidence_refs":{"items":{"enum":["financial_goals","transactions","wallets"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FINANCAS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["metas financeiras","round-up","visao de caixa"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario PF","microempreendedor","operador financeiro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FINANCAS::financas.goal.created","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('FINANCAS:financas.roundup.booked:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'FINANCAS', 'financas.roundup.booked', '1.0.0', 'painel financeiro pessoal', ARRAY['ADVISOR', 'BUSINESS', 'painel financeiro pessoal', 'monitor de metas']::TEXT[], ARRAY['financial_goals', 'transactions', 'wallets']::TEXT[], ARRAY['financial_privacy', 'goal_audit', 'ledger_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["financial_privacy","goal_audit","ledger_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"financas.roundup.booked"},"evidence_refs":{"items":{"enum":["financial_goals","transactions","wallets"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FINANCAS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["metas financeiras","round-up","visao de caixa"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario PF","microempreendedor","operador financeiro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FINANCAS::financas.roundup.booked","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('FINANCAS:financas.cashflow.closed:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'FINANCAS', 'financas.cashflow.closed', '1.0.0', 'painel financeiro pessoal', ARRAY['ADVISOR', 'BUSINESS', 'painel financeiro pessoal', 'monitor de metas']::TEXT[], ARRAY['financial_goals', 'transactions', 'wallets']::TEXT[], ARRAY['financial_privacy', 'goal_audit', 'ledger_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["financial_privacy","goal_audit","ledger_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"financas.cashflow.closed"},"evidence_refs":{"items":{"enum":["financial_goals","transactions","wallets"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FINANCAS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["metas financeiras","round-up","visao de caixa"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario PF","microempreendedor","operador financeiro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FINANCAS::financas.cashflow.closed","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('DIGITAL:digital.asset.minted:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'DIGITAL', 'digital.asset.minted', '1.0.0', 'painel de colecoes', ARRAY['CREATOR', 'DOCS', 'painel de colecoes', 'fila de mint']::TEXT[], ARRAY['digital_asset_collections', 'digital_assets', 'digital_asset_events']::TEXT[], ARRAY['ownership_traceability', 'royalty_audit', 'custody_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ownership_traceability","royalty_audit","custody_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"digital.asset.minted"},"evidence_refs":{"items":{"enum":["digital_asset_collections","digital_assets","digital_asset_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"DIGITAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["colecoes digitais","mint e transferencia","trilha de royalties"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","colecionador","operador de custodia"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"DIGITAL::digital.asset.minted","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('DIGITAL:digital.asset.transferred:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'DIGITAL', 'digital.asset.transferred', '1.0.0', 'painel de colecoes', ARRAY['CREATOR', 'DOCS', 'painel de colecoes', 'fila de mint']::TEXT[], ARRAY['digital_asset_collections', 'digital_assets', 'digital_asset_events']::TEXT[], ARRAY['ownership_traceability', 'royalty_audit', 'custody_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ownership_traceability","royalty_audit","custody_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"digital.asset.transferred"},"evidence_refs":{"items":{"enum":["digital_asset_collections","digital_assets","digital_asset_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"DIGITAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["colecoes digitais","mint e transferencia","trilha de royalties"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","colecionador","operador de custodia"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"DIGITAL::digital.asset.transferred","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('DIGITAL:digital.royalty.calculated:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'DIGITAL', 'digital.royalty.calculated', '1.0.0', 'painel de colecoes', ARRAY['CREATOR', 'DOCS', 'painel de colecoes', 'fila de mint']::TEXT[], ARRAY['digital_asset_collections', 'digital_assets', 'digital_asset_events']::TEXT[], ARRAY['ownership_traceability', 'royalty_audit', 'custody_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ownership_traceability","royalty_audit","custody_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"digital.royalty.calculated"},"evidence_refs":{"items":{"enum":["digital_asset_collections","digital_assets","digital_asset_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"DIGITAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["colecoes digitais","mint e transferencia","trilha de royalties"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","colecionador","operador de custodia"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"DIGITAL::digital.royalty.calculated","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('REAL_ESTATE:real_estate.property.registered:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'REAL_ESTATE', 'real_estate.property.registered', '1.0.0', 'painel de propriedades', ARRAY['DIGITAL', 'DOCS', 'painel de propriedades', 'fila de due diligence']::TEXT[], ARRAY['real_estate_properties', 'real_estate_listings', 'real_estate_deals']::TEXT[], ARRAY['property_traceability', 'contract_audit', 'investor_suitability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["property_traceability","contract_audit","investor_suitability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"real_estate.property.registered"},"evidence_refs":{"items":{"enum":["real_estate_properties","real_estate_listings","real_estate_deals"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"REAL_ESTATE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["cadastro de imovel","listagem e proposta","deal tokenizado"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["corretor","investidor","operador juridico"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"REAL_ESTATE::real_estate.property.registered","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('REAL_ESTATE:real_estate.listing.published:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'REAL_ESTATE', 'real_estate.listing.published', '1.0.0', 'painel de propriedades', ARRAY['DIGITAL', 'DOCS', 'painel de propriedades', 'fila de due diligence']::TEXT[], ARRAY['real_estate_properties', 'real_estate_listings', 'real_estate_deals']::TEXT[], ARRAY['property_traceability', 'contract_audit', 'investor_suitability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["property_traceability","contract_audit","investor_suitability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"real_estate.listing.published"},"evidence_refs":{"items":{"enum":["real_estate_properties","real_estate_listings","real_estate_deals"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"REAL_ESTATE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["cadastro de imovel","listagem e proposta","deal tokenizado"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["corretor","investidor","operador juridico"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"REAL_ESTATE::real_estate.listing.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('REAL_ESTATE:real_estate.deal.executed:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'REAL_ESTATE', 'real_estate.deal.executed', '1.0.0', 'painel de propriedades', ARRAY['DIGITAL', 'DOCS', 'painel de propriedades', 'fila de due diligence']::TEXT[], ARRAY['real_estate_properties', 'real_estate_listings', 'real_estate_deals']::TEXT[], ARRAY['property_traceability', 'contract_audit', 'investor_suitability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["property_traceability","contract_audit","investor_suitability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"real_estate.deal.executed"},"evidence_refs":{"items":{"enum":["real_estate_properties","real_estate_listings","real_estate_deals"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"REAL_ESTATE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["cadastro de imovel","listagem e proposta","deal tokenizado"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["corretor","investidor","operador juridico"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"REAL_ESTATE::real_estate.deal.executed","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('INSURANCE:insurance.policy.issued:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'INSURANCE', 'insurance.policy.issued', '1.0.0', 'painel de apolices', ARRAY['SECURITY', 'DOCS', 'painel de apolices', 'fila de claim']::TEXT[], ARRAY['insurance_products', 'insurance_policies', 'insurance_claims']::TEXT[], ARRAY['policy_audit', 'claim_traceability', 'risk_underwriting']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["policy_audit","claim_traceability","risk_underwriting"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"insurance.policy.issued"},"evidence_refs":{"items":{"enum":["insurance_products","insurance_policies","insurance_claims"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INSURANCE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["produtos e apolices","claims","eventos de claim"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["segurado","underwriter","analista de sinistro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INSURANCE::insurance.policy.issued","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('INSURANCE:insurance.claim.opened:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'INSURANCE', 'insurance.claim.opened', '1.0.0', 'painel de apolices', ARRAY['SECURITY', 'DOCS', 'painel de apolices', 'fila de claim']::TEXT[], ARRAY['insurance_products', 'insurance_policies', 'insurance_claims']::TEXT[], ARRAY['policy_audit', 'claim_traceability', 'risk_underwriting']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["policy_audit","claim_traceability","risk_underwriting"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"insurance.claim.opened"},"evidence_refs":{"items":{"enum":["insurance_products","insurance_policies","insurance_claims"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INSURANCE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["produtos e apolices","claims","eventos de claim"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["segurado","underwriter","analista de sinistro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INSURANCE::insurance.claim.opened","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json'),
    ('INSURANCE:insurance.claim.settled:v1', 'commerce_fintech_assets.priority.v1', 'commerce_fintech_assets', 'INSURANCE', 'insurance.claim.settled', '1.0.0', 'painel de apolices', ARRAY['SECURITY', 'DOCS', 'painel de apolices', 'fila de claim']::TEXT[], ARRAY['insurance_products', 'insurance_policies', 'insurance_claims']::TEXT[], ARRAY['policy_audit', 'claim_traceability', 'risk_underwriting']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["policy_audit","claim_traceability","risk_underwriting"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"commerce_fintech_assets"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"insurance.claim.settled"},"evidence_refs":{"items":{"enum":["insurance_products","insurance_policies","insurance_claims"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INSURANCE"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["produtos e apolices","claims","eventos de claim"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["segurado","underwriter","analista de sinistro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INSURANCE::insurance.claim.settled","type":"object"}'::JSONB, 'contracts/events/priority-domains/commerce_fintech_assets.json')
)
INSERT INTO domain_event_contracts (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
)
SELECT
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
FROM contract_source
ON CONFLICT (contract_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    module_code = EXCLUDED.module_code,
    event_topic = EXCLUDED.event_topic,
    contract_version = EXCLUDED.contract_version,
    producer_surface = EXCLUDED.producer_surface,
    consumer_surfaces = EXCLUDED.consumer_surfaces,
    evidence_entities = EXCLUDED.evidence_entities,
    compliance_tags = EXCLUDED.compliance_tags,
    contract_status = EXCLUDED.contract_status,
    payload_schema_json = EXCLUDED.payload_schema_json,
    artifact_path = EXCLUDED.artifact_path,
    updated_at = NOW();

COMMIT;
