BEGIN;

-- Seed operacional idempotente dos pacotes fisicos por dominio prioritario.
-- Gerado automaticamente por scripts/valley_module_automation.py.

WITH package_source (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
) AS (
    VALUES
    ('city_mobility_security.priority.v1', 'city_mobility_security', 'City Mobility Security', 2, 'priority_domains_v1', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"artifacts":[{"artifact_key":"city_mobility_security.ddl.v1","artifact_path":"database/domain-delivery/priority-domains/city_mobility_security/ddl_complement.sql","layer_type":"DDL_COMPLEMENT","target_engine":"postgres"},{"artifact_key":"city_mobility_security.seed.v1","artifact_path":"database/domain-delivery/priority-domains/city_mobility_security/operational_seed.sql","layer_type":"OPERATIONS_SEED","target_engine":"postgres"},{"artifact_key":"city_mobility_security.contract.v1","artifact_path":"contracts/events/priority-domains/city_mobility_security.json","layer_type":"EVENT_CONTRACT","target_engine":"filesystem"}],"backlog_keys":["LEGAL.exec.01","LEGAL.exec.02","EVENTS.exec.01","EVENTS.exec.02","MOBILITY.exec.01","MOBILITY.exec.02","SECURITY.exec.01","SECURITY.exec.02","LEGAL.exec.03","TOURISM.exec.01","TOURISM.exec.02","EVENTS.exec.03","MOBILITY.exec.03","SECURITY.exec.03","GOV.exec.01","GOV.exec.02","TOURISM.exec.03","GOV.exec.03"],"domain_key":"city_mobility_security","domain_label":"City Mobility Security","event_topics":["legal.contract.created","legal.signature.recorded","legal.dispute.opened","events.program.published","events.ticket.issued","events.ticket.transferred","mobility.trip.requested","mobility.trip.started","mobility.trip.completed","security.sos.triggered","security.biometric.enrolled","security.incident.closed","tourism.experience.published","tourism.booking.confirmed","tourism.checkin.recorded","gov.service.requested","gov.request.routed","gov.request.resolved"],"modules":["LEGAL","EVENTS","MOBILITY","SECURITY","TOURISM","GOV"],"package_key":"city_mobility_security.priority.v1","priority_rank":2}'::JSONB)
)
INSERT INTO domain_delivery_packages (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
)
SELECT
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
FROM package_source
ON CONFLICT (package_key) DO UPDATE SET
    domain_key = EXCLUDED.domain_key,
    domain_label = EXCLUDED.domain_label,
    priority_rank = EXCLUDED.priority_rank,
    package_scope = EXCLUDED.package_scope,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    package_status = EXCLUDED.package_status,
    artifact_manifest_json = EXCLUDED.artifact_manifest_json,
    updated_at = NOW();

WITH artifact_source (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
) AS (
    VALUES
    ('city_mobility_security.ddl.v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'DDL_COMPLEMENT'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/city_mobility_security/ddl_complement.sql', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], ARRAY[]::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"package_key":"city_mobility_security.priority.v1","priority_rank":2,"views":["v_city_mobility_security_legal_ops","v_city_mobility_security_experience_ops","v_city_mobility_security_incident_ops","v_city_mobility_security_gov_requests"]}'::JSONB),
    ('city_mobility_security.seed.v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'OPERATIONS_SEED'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/city_mobility_security/operational_seed.sql', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], ARRAY['city_mobility_security.ddl.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"contract_count":18,"package_key":"city_mobility_security.priority.v1","seed_scope":"priority_domain_delivery_v1"}'::JSONB),
    ('city_mobility_security.contract.v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENT_CONTRACT'::domain_delivery_layer_enum, 'filesystem', 'contracts/events/priority-domains/city_mobility_security.json', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], ARRAY['city_mobility_security.ddl.v1', 'city_mobility_security.seed.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"event_topics":["legal.contract.created","legal.signature.recorded","legal.dispute.opened","events.program.published","events.ticket.issued","events.ticket.transferred","mobility.trip.requested","mobility.trip.started","mobility.trip.completed","security.sos.triggered","security.biometric.enrolled","security.incident.closed","tourism.experience.published","tourism.booking.confirmed","tourism.checkin.recorded","gov.service.requested","gov.request.routed","gov.request.resolved"],"package_key":"city_mobility_security.priority.v1"}'::JSONB)
)
INSERT INTO domain_delivery_artifacts (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
)
SELECT
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
FROM artifact_source
ON CONFLICT (artifact_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    layer_type = EXCLUDED.layer_type,
    target_engine = EXCLUDED.target_engine,
    artifact_path = EXCLUDED.artifact_path,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    depends_on_keys = EXCLUDED.depends_on_keys,
    artifact_status = EXCLUDED.artifact_status,
    artifact_payload_json = EXCLUDED.artifact_payload_json,
    updated_at = NOW();

WITH contract_source (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
) AS (
    VALUES
    ('LEGAL:legal.contract.created:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'LEGAL', 'legal.contract.created', '1.0.0', 'painel juridico', ARRAY['DOCS', 'SECURITY', 'painel juridico', 'fila de assinaturas']::TEXT[], ARRAY['legal_contracts', 'legal_contract_parties', 'legal_signatures']::TEXT[], ARRAY['legal_audit', 'signature_traceability', 'fallback_pin_hashing']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["legal_audit","signature_traceability","fallback_pin_hashing"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"legal.contract.created"},"evidence_refs":{"items":{"enum":["legal_contracts","legal_contract_parties","legal_signatures"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LEGAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contratos","assinaturas","disputas e trilha juridica"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["juridico","assinante","mediador"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LEGAL::legal.contract.created","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('LEGAL:legal.signature.recorded:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'LEGAL', 'legal.signature.recorded', '1.0.0', 'painel juridico', ARRAY['DOCS', 'SECURITY', 'painel juridico', 'fila de assinaturas']::TEXT[], ARRAY['legal_contracts', 'legal_contract_parties', 'legal_signatures']::TEXT[], ARRAY['legal_audit', 'signature_traceability', 'fallback_pin_hashing']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["legal_audit","signature_traceability","fallback_pin_hashing"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"legal.signature.recorded"},"evidence_refs":{"items":{"enum":["legal_contracts","legal_contract_parties","legal_signatures"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LEGAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contratos","assinaturas","disputas e trilha juridica"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["juridico","assinante","mediador"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LEGAL::legal.signature.recorded","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('LEGAL:legal.dispute.opened:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'LEGAL', 'legal.dispute.opened', '1.0.0', 'painel juridico', ARRAY['DOCS', 'SECURITY', 'painel juridico', 'fila de assinaturas']::TEXT[], ARRAY['legal_contracts', 'legal_contract_parties', 'legal_signatures']::TEXT[], ARRAY['legal_audit', 'signature_traceability', 'fallback_pin_hashing']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["legal_audit","signature_traceability","fallback_pin_hashing"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"legal.dispute.opened"},"evidence_refs":{"items":{"enum":["legal_contracts","legal_contract_parties","legal_signatures"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LEGAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contratos","assinaturas","disputas e trilha juridica"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["juridico","assinante","mediador"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LEGAL::legal.dispute.opened","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('EVENTS:events.program.published:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENTS', 'events.program.published', '1.0.0', 'painel de eventos', ARRAY['TICKETS', 'DOCS', 'painel de eventos', 'monitor de bilheteria']::TEXT[], ARRAY['event_programs', 'event_ticket_types', 'event_ticket_ledger']::TEXT[], ARRAY['ticket_immutability', 'escrow_audit', 'fraud_prevention']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ticket_immutability","escrow_audit","fraud_prevention"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"events.program.published"},"evidence_refs":{"items":{"enum":["event_programs","event_ticket_types","event_ticket_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"EVENTS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["programacao de evento","tipos de ingresso","ledger de tickets"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["organizador","participante","operador de bilheteria"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"EVENTS::events.program.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('EVENTS:events.ticket.issued:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENTS', 'events.ticket.issued', '1.0.0', 'painel de eventos', ARRAY['TICKETS', 'DOCS', 'painel de eventos', 'monitor de bilheteria']::TEXT[], ARRAY['event_programs', 'event_ticket_types', 'event_ticket_ledger']::TEXT[], ARRAY['ticket_immutability', 'escrow_audit', 'fraud_prevention']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ticket_immutability","escrow_audit","fraud_prevention"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"events.ticket.issued"},"evidence_refs":{"items":{"enum":["event_programs","event_ticket_types","event_ticket_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"EVENTS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["programacao de evento","tipos de ingresso","ledger de tickets"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["organizador","participante","operador de bilheteria"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"EVENTS::events.ticket.issued","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('EVENTS:events.ticket.transferred:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENTS', 'events.ticket.transferred', '1.0.0', 'painel de eventos', ARRAY['TICKETS', 'DOCS', 'painel de eventos', 'monitor de bilheteria']::TEXT[], ARRAY['event_programs', 'event_ticket_types', 'event_ticket_ledger']::TEXT[], ARRAY['ticket_immutability', 'escrow_audit', 'fraud_prevention']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ticket_immutability","escrow_audit","fraud_prevention"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"events.ticket.transferred"},"evidence_refs":{"items":{"enum":["event_programs","event_ticket_types","event_ticket_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"EVENTS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["programacao de evento","tipos de ingresso","ledger de tickets"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["organizador","participante","operador de bilheteria"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"EVENTS::events.ticket.transferred","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('MOBILITY:mobility.trip.requested:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'MOBILITY', 'mobility.trip.requested', '1.0.0', 'torre de corridas', ARRAY['LOG', 'FLEET', 'torre de corridas', 'monitor de checkpoints']::TEXT[], ARRAY['mobility_trips', 'mobility_trip_events', 'orders', 'fleet_vehicle_profiles', 'telemetry_logs']::TEXT[], ARRAY['ride_audit', 'driver_accountability', 'fare_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ride_audit","driver_accountability","fare_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"mobility.trip.requested"},"evidence_refs":{"items":{"enum":["mobility_trips","mobility_trip_events","orders","fleet_vehicle_profiles","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MOBILITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["corrida urbana","checkpoint operacional","precificacao de rota"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["passageiro","rider","dispatcher"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MOBILITY::mobility.trip.requested","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('MOBILITY:mobility.trip.started:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'MOBILITY', 'mobility.trip.started', '1.0.0', 'torre de corridas', ARRAY['LOG', 'FLEET', 'torre de corridas', 'monitor de checkpoints']::TEXT[], ARRAY['mobility_trips', 'mobility_trip_events', 'orders', 'fleet_vehicle_profiles', 'telemetry_logs']::TEXT[], ARRAY['ride_audit', 'driver_accountability', 'fare_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ride_audit","driver_accountability","fare_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"mobility.trip.started"},"evidence_refs":{"items":{"enum":["mobility_trips","mobility_trip_events","orders","fleet_vehicle_profiles","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MOBILITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["corrida urbana","checkpoint operacional","precificacao de rota"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["passageiro","rider","dispatcher"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MOBILITY::mobility.trip.started","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('MOBILITY:mobility.trip.completed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'MOBILITY', 'mobility.trip.completed', '1.0.0', 'torre de corridas', ARRAY['LOG', 'FLEET', 'torre de corridas', 'monitor de checkpoints']::TEXT[], ARRAY['mobility_trips', 'mobility_trip_events', 'orders', 'fleet_vehicle_profiles', 'telemetry_logs']::TEXT[], ARRAY['ride_audit', 'driver_accountability', 'fare_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ride_audit","driver_accountability","fare_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"mobility.trip.completed"},"evidence_refs":{"items":{"enum":["mobility_trips","mobility_trip_events","orders","fleet_vehicle_profiles","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MOBILITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["corrida urbana","checkpoint operacional","precificacao de rota"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["passageiro","rider","dispatcher"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MOBILITY::mobility.trip.completed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('SECURITY:security.sos.triggered:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'SECURITY', 'security.sos.triggered', '1.0.0', 'torre de seguranca', ARRAY['IOT', 'LEGAL', 'torre de seguranca', 'fila de incidentes']::TEXT[], ARRAY['security_trusted_contacts', 'security_biometric_credentials', 'security_incidents', 'security_signal_logs', 'iot_sensor_events']::TEXT[], ARRAY['biometric_hashing', 'incident_chain_of_custody', 'access_control']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["biometric_hashing","incident_chain_of_custody","access_control"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"security.sos.triggered"},"evidence_refs":{"items":{"enum":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_signal_logs","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SECURITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario protegido","analista de risco","operador SOS"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SECURITY::security.sos.triggered","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('SECURITY:security.biometric.enrolled:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'SECURITY', 'security.biometric.enrolled', '1.0.0', 'torre de seguranca', ARRAY['IOT', 'LEGAL', 'torre de seguranca', 'fila de incidentes']::TEXT[], ARRAY['security_trusted_contacts', 'security_biometric_credentials', 'security_incidents', 'security_signal_logs', 'iot_sensor_events']::TEXT[], ARRAY['biometric_hashing', 'incident_chain_of_custody', 'access_control']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["biometric_hashing","incident_chain_of_custody","access_control"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"security.biometric.enrolled"},"evidence_refs":{"items":{"enum":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_signal_logs","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SECURITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario protegido","analista de risco","operador SOS"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SECURITY::security.biometric.enrolled","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('SECURITY:security.incident.closed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'SECURITY', 'security.incident.closed', '1.0.0', 'torre de seguranca', ARRAY['IOT', 'LEGAL', 'torre de seguranca', 'fila de incidentes']::TEXT[], ARRAY['security_trusted_contacts', 'security_biometric_credentials', 'security_incidents', 'security_signal_logs', 'iot_sensor_events']::TEXT[], ARRAY['biometric_hashing', 'incident_chain_of_custody', 'access_control']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["biometric_hashing","incident_chain_of_custody","access_control"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"security.incident.closed"},"evidence_refs":{"items":{"enum":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_signal_logs","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SECURITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario protegido","analista de risco","operador SOS"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SECURITY::security.incident.closed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('TOURISM:tourism.experience.published:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'TOURISM', 'tourism.experience.published', '1.0.0', 'painel de experiencias', ARRAY['EVENTS', 'MOBILITY', 'painel de experiencias', 'fila de bookings']::TEXT[], ARRAY['tourism_experiences', 'tourism_bookings', 'tourism_booking_events', 'tourism_experience_feeds', 'space_anchor_maps']::TEXT[], ARRAY['booking_audit', 'guide_accountability', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["booking_audit","guide_accountability","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"tourism.experience.published"},"evidence_refs":{"items":{"enum":["tourism_experiences","tourism_bookings","tourism_booking_events","tourism_experience_feeds","space_anchor_maps"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"TOURISM"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["experiencias locais","booking","feed exploratorio"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["turista","guia","operador local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"TOURISM::tourism.experience.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('TOURISM:tourism.booking.confirmed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'TOURISM', 'tourism.booking.confirmed', '1.0.0', 'painel de experiencias', ARRAY['EVENTS', 'MOBILITY', 'painel de experiencias', 'fila de bookings']::TEXT[], ARRAY['tourism_experiences', 'tourism_bookings', 'tourism_booking_events', 'tourism_experience_feeds', 'space_anchor_maps']::TEXT[], ARRAY['booking_audit', 'guide_accountability', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["booking_audit","guide_accountability","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"tourism.booking.confirmed"},"evidence_refs":{"items":{"enum":["tourism_experiences","tourism_bookings","tourism_booking_events","tourism_experience_feeds","space_anchor_maps"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"TOURISM"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["experiencias locais","booking","feed exploratorio"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["turista","guia","operador local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"TOURISM::tourism.booking.confirmed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('TOURISM:tourism.checkin.recorded:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'TOURISM', 'tourism.checkin.recorded', '1.0.0', 'painel de experiencias', ARRAY['EVENTS', 'MOBILITY', 'painel de experiencias', 'fila de bookings']::TEXT[], ARRAY['tourism_experiences', 'tourism_bookings', 'tourism_booking_events', 'tourism_experience_feeds', 'space_anchor_maps']::TEXT[], ARRAY['booking_audit', 'guide_accountability', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["booking_audit","guide_accountability","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"tourism.checkin.recorded"},"evidence_refs":{"items":{"enum":["tourism_experiences","tourism_bookings","tourism_booking_events","tourism_experience_feeds","space_anchor_maps"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"TOURISM"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["experiencias locais","booking","feed exploratorio"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["turista","guia","operador local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"TOURISM::tourism.checkin.recorded","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('GOV:gov.service.requested:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'GOV', 'gov.service.requested', '1.0.0', 'portal de requests', ARRAY['LEGAL', 'DOCS', 'portal de requests', 'fila de atendimento']::TEXT[], ARRAY['gov_service_catalog', 'gov_service_requests', 'gov_request_events']::TEXT[], ARRAY['public_auditability', 'citizen_identity', 'service_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["public_auditability","citizen_identity","service_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gov.service.requested"},"evidence_refs":{"items":{"enum":["gov_service_catalog","gov_service_requests","gov_request_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GOV"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["catalogo de servicos","requests publicos","eventos de atendimento"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["cidadao","servidor","operador govtech"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GOV::gov.service.requested","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('GOV:gov.request.routed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'GOV', 'gov.request.routed', '1.0.0', 'portal de requests', ARRAY['LEGAL', 'DOCS', 'portal de requests', 'fila de atendimento']::TEXT[], ARRAY['gov_service_catalog', 'gov_service_requests', 'gov_request_events']::TEXT[], ARRAY['public_auditability', 'citizen_identity', 'service_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["public_auditability","citizen_identity","service_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gov.request.routed"},"evidence_refs":{"items":{"enum":["gov_service_catalog","gov_service_requests","gov_request_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GOV"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["catalogo de servicos","requests publicos","eventos de atendimento"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["cidadao","servidor","operador govtech"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GOV::gov.request.routed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('GOV:gov.request.resolved:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'GOV', 'gov.request.resolved', '1.0.0', 'portal de requests', ARRAY['LEGAL', 'DOCS', 'portal de requests', 'fila de atendimento']::TEXT[], ARRAY['gov_service_catalog', 'gov_service_requests', 'gov_request_events']::TEXT[], ARRAY['public_auditability', 'citizen_identity', 'service_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["public_auditability","citizen_identity","service_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gov.request.resolved"},"evidence_refs":{"items":{"enum":["gov_service_catalog","gov_service_requests","gov_request_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GOV"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["catalogo de servicos","requests publicos","eventos de atendimento"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["cidadao","servidor","operador govtech"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GOV::gov.request.resolved","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json')
)
INSERT INTO domain_event_contracts (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
)
SELECT
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
FROM contract_source
ON CONFLICT (contract_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    module_code = EXCLUDED.module_code,
    event_topic = EXCLUDED.event_topic,
    contract_version = EXCLUDED.contract_version,
    producer_surface = EXCLUDED.producer_surface,
    consumer_surfaces = EXCLUDED.consumer_surfaces,
    evidence_entities = EXCLUDED.evidence_entities,
    compliance_tags = EXCLUDED.compliance_tags,
    contract_status = EXCLUDED.contract_status,
    payload_schema_json = EXCLUDED.payload_schema_json,
    artifact_path = EXCLUDED.artifact_path,
    updated_at = NOW();

-- Seed operacional minimo do dominio com cadeia juridica, eventos, turismo, seguranca e govtech.

INSERT INTO users (
    user_id,
    user_kind,
    account_status,
    kyc_status,
    full_name,
    display_name,
    email,
    phone_e164,
    document_country,
    document_type,
    document_number,
    nationality,
    tax_residence_country,
    risk_level,
    primary_role,
    nexus_external_ref,
    terms_accepted_at,
    privacy_accepted_at,
    module_tier,
    ops_region_code,
    compliance_notes,
    internal_tags,
    created_at,
    updated_at
) VALUES
    (
        '10000000-0000-4000-8000-000000000301',
        'PJ'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Nexora Civic Experiences Ltda',
        'Nexora Civic',
        'civic.ops@nexora.local',
        '+5511999000301',
        'BR',
        'CNPJ',
        '52.884.330/0001-11',
        'BR',
        'BR',
        1,
        'CITY_OPERATOR',
        'seed-city-owner',
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:02:00+00',
        'ENTERPRISE',
        'BR-SP',
        'Operador ancora dos fluxos juridicos, eventos e govtech do dominio city_mobility_security.',
        ARRAY['seed','city_mobility_security','priority_2']::TEXT[],
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000302',
        'PF'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Livia Cidada',
        'Livia Cidada',
        'livia.cidada@nexora.local',
        '+5511999000302',
        'BR',
        'CPF',
        '391.552.770-43',
        'BR',
        'BR',
        1,
        'CITIZEN',
        'seed-city-citizen',
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:02:00+00',
        'CORE',
        'BR-SP',
        'Cidada usada para contrato, turismo, seguranca e servico publico.',
        ARRAY['seed','city_mobility_security','citizen']::TEXT[],
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000303',
        'ADMIN'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Carlos Operacoes Publicas',
        'Carlos GovOps',
        'carlos.govops@nexora.local',
        '+5511999000303',
        'BR',
        'CPF',
        '448.220.980-67',
        'BR',
        'BR',
        1,
        'RISK_OPERATOR',
        'seed-city-operator',
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:02:00+00',
        'PRO',
        'BR-SP',
        'Administrador de risco, govtech e mediacao operacional.',
        ARRAY['seed','city_mobility_security','ops']::TEXT[],
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000304',
        'PF'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Mateus Guia Local',
        'Mateus Guia',
        'mateus.guia@nexora.local',
        '+5511999000304',
        'BR',
        'CPF',
        '285.671.250-48',
        'BR',
        'BR',
        1,
        'GUIDE',
        'seed-city-guide',
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:02:00+00',
        'PRO',
        'BR-SP',
        'Guia local do fluxo tourism e experiencia urbana.',
        ARRAY['seed','city_mobility_security','tourism']::TEXT[],
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00'
    )
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO wallets (
    wallet_id,
    user_id,
    wallet_type,
    asset_code,
    wallet_status,
    balance_available_brl,
    balance_blocked_brl,
    balance_pending_brl,
    balance_available_nex,
    balance_blocked_nex,
    balance_pending_nex,
    daily_limit_brl,
    monthly_limit_brl,
    ledger_version,
    last_reconciled_at,
    created_at,
    updated_at
) VALUES
    (
        '20000000-0000-4000-8000-000000000301',
        '10000000-0000-4000-8000-000000000301',
        'CUSTODIAL'::wallet_type_enum,
        'BRL'::wallet_asset_enum,
        'ACTIVE'::wallet_status_enum,
        18000.0000,
        0.0000,
        0.0000,
        0.00000000,
        0.00000000,
        0.00000000,
        35000.0000,
        500000.0000,
        4,
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00'
    ),
    (
        '20000000-0000-4000-8000-000000000302',
        '10000000-0000-4000-8000-000000000302',
        'CUSTODIAL'::wallet_type_enum,
        'BRL'::wallet_asset_enum,
        'ACTIVE'::wallet_status_enum,
        950.0000,
        0.0000,
        0.0000,
        0.00000000,
        0.00000000,
        0.00000000,
        5000.0000,
        60000.0000,
        2,
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00',
        TIMESTAMPTZ '2026-04-21 12:00:00+00'
    )
ON CONFLICT (wallet_id) DO NOTHING;

INSERT INTO document_records (
    document_id,
    user_id,
    module_code,
    order_id,
    transaction_id,
    file_url,
    checksum_sha256,
    event_reference,
    created_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000501',
        '10000000-0000-4000-8000-000000000301',
        NULL,
        NULL,
        NULL,
        'https://files.nexora.local/city/terms/urban-experience-master.pdf',
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        NULL,
        TIMESTAMPTZ '2026-04-21 12:05:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000502',
        '10000000-0000-4000-8000-000000000302',
        NULL,
        NULL,
        NULL,
        'https://files.nexora.local/city/security/sos-case-001.pdf',
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        NULL,
        TIMESTAMPTZ '2026-04-21 12:50:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000503',
        '10000000-0000-4000-8000-000000000302',
        NULL,
        NULL,
        NULL,
        'https://files.nexora.local/city/gov/protocol-urban-pass-001.pdf',
        'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
        NULL,
        TIMESTAMPTZ '2026-04-21 13:20:00+00'
    )
ON CONFLICT (document_id) DO NOTHING;

INSERT INTO legal_contracts (
    legal_contract_id,
    owner_user_id,
    counterparty_user_id,
    module_code,
    document_id,
    contract_status,
    contract_type,
    title,
    jurisdiction_country,
    terms_hash_sha256,
    contract_uri,
    effective_at,
    expires_at,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000504',
    '10000000-0000-4000-8000-000000000301',
    '10000000-0000-4000-8000-000000000302',
    'LEGAL',
    '30000000-0000-4000-8000-000000000501',
    'DISPUTED'::legal_contract_status_enum,
    'CITY_EXPERIENCE_TERMS',
    'Contrato de experiencia urbana monitorada',
    'BR',
    'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
    'https://contracts.nexora.local/city/urban-experience-master',
    TIMESTAMPTZ '2026-04-21 12:10:00+00',
    TIMESTAMPTZ '2027-04-21 12:10:00+00',
    '{"domain":"city_mobility_security","coverage":["LEGAL","EVENTS","TOURISM","GOV"]}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:10:00+00',
    TIMESTAMPTZ '2026-04-21 12:30:00+00'
) ON CONFLICT (legal_contract_id) DO NOTHING;

INSERT INTO legal_contract_parties (
    legal_contract_party_id,
    legal_contract_id,
    user_id,
    party_role,
    signing_order,
    accepted_at,
    created_at,
    updated_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000505',
        '30000000-0000-4000-8000-000000000504',
        '10000000-0000-4000-8000-000000000301',
        'OWNER'::legal_party_role_enum,
        1,
        TIMESTAMPTZ '2026-04-21 12:12:00+00',
        TIMESTAMPTZ '2026-04-21 12:12:00+00',
        TIMESTAMPTZ '2026-04-21 12:12:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000506',
        '30000000-0000-4000-8000-000000000504',
        '10000000-0000-4000-8000-000000000302',
        'COUNTERPARTY'::legal_party_role_enum,
        2,
        TIMESTAMPTZ '2026-04-21 12:15:00+00',
        TIMESTAMPTZ '2026-04-21 12:15:00+00',
        TIMESTAMPTZ '2026-04-21 12:15:00+00'
    )
ON CONFLICT (legal_contract_party_id) DO NOTHING;

INSERT INTO legal_signatures (
    legal_signature_id,
    legal_contract_id,
    signer_user_id,
    document_id,
    signature_status,
    signature_method,
    signature_hash_sha256,
    ip_hash_sha256,
    device_fingerprint_hash_sha256,
    signed_at,
    created_at
) VALUES (
    '30000000-0000-4000-8000-000000000507',
    '30000000-0000-4000-8000-000000000504',
    '10000000-0000-4000-8000-000000000302',
    '30000000-0000-4000-8000-000000000501',
    'SIGNED'::legal_signature_status_enum,
    'FALLBACK_PIN_HASHED'::legal_signature_method_enum,
    'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
    '1111111111111111111111111111111111111111111111111111111111111111',
    TIMESTAMPTZ '2026-04-21 12:16:00+00',
    TIMESTAMPTZ '2026-04-21 12:16:00+00'
) ON CONFLICT (legal_signature_id) DO NOTHING;

INSERT INTO legal_fallback_pin_credentials (
    fallback_pin_id,
    user_id,
    pin_status,
    pin_hash_sha256,
    failed_attempts,
    locked_until,
    last_verified_at,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000508',
    '10000000-0000-4000-8000-000000000302',
    'ACTIVE'::fallback_pin_status_enum,
    '2222222222222222222222222222222222222222222222222222222222222222',
    0,
    NULL,
    TIMESTAMPTZ '2026-04-21 12:16:00+00',
    TIMESTAMPTZ '2026-04-21 12:14:00+00',
    TIMESTAMPTZ '2026-04-21 12:16:00+00'
) ON CONFLICT (fallback_pin_id) DO NOTHING;

INSERT INTO legal_disputes (
    legal_dispute_id,
    owner_user_id,
    opened_by_user_id,
    assigned_admin_id,
    module_code,
    legal_contract_id,
    order_id,
    transaction_id,
    dispute_status,
    dispute_reason,
    resolution_summary,
    opened_at,
    resolved_at,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000509',
    '10000000-0000-4000-8000-000000000301',
    '10000000-0000-4000-8000-000000000302',
    NULL,
    'LEGAL',
    '30000000-0000-4000-8000-000000000504',
    NULL,
    NULL,
    'OPEN'::legal_dispute_status_enum,
    'Contestacao de horario e cobertura do pacote urbano.',
    NULL,
    TIMESTAMPTZ '2026-04-21 12:30:00+00',
    NULL,
    '{"domain":"city_mobility_security","source":"tourism_event_package"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:30:00+00',
    TIMESTAMPTZ '2026-04-21 12:30:00+00'
) ON CONFLICT (legal_dispute_id) DO NOTHING;

INSERT INTO legal_audit_events (
    legal_audit_event_id,
    legal_contract_id,
    legal_dispute_id,
    user_id,
    admin_id,
    event_type,
    event_name,
    event_payload_json,
    event_hash_sha256,
    created_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000510',
        '30000000-0000-4000-8000-000000000504',
        NULL,
        '10000000-0000-4000-8000-000000000301',
        NULL,
        'CONTRACT_CREATED'::legal_audit_event_type_enum,
        'contract_created',
        '{"source":"seed","module":"LEGAL"}'::JSONB,
        '3333333333333333333333333333333333333333333333333333333333333333',
        TIMESTAMPTZ '2026-04-21 12:10:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000511',
        '30000000-0000-4000-8000-000000000504',
        '30000000-0000-4000-8000-000000000509',
        '10000000-0000-4000-8000-000000000302',
        NULL,
        'DISPUTE_OPENED'::legal_audit_event_type_enum,
        'dispute_opened',
        '{"source":"seed","channel":"city_app"}'::JSONB,
        '4444444444444444444444444444444444444444444444444444444444444444',
        TIMESTAMPTZ '2026-04-21 12:31:00+00'
    )
ON CONFLICT (legal_audit_event_id) DO NOTHING;

INSERT INTO event_programs (
    event_program_id,
    organizer_user_id,
    wallet_id,
    module_code,
    event_status,
    title,
    venue_name,
    venue_json,
    starts_at,
    ends_at,
    sales_start_at,
    sales_end_at,
    max_capacity,
    age_rating,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000512',
    '10000000-0000-4000-8000-000000000301',
    '20000000-0000-4000-8000-000000000301',
    'EVENTS',
    'PUBLISHED'::event_program_status_enum,
    'Circuito Seguro Centro Vivo',
    'Pateo do Collegio',
    '{"city":"Sao Paulo","lat":-23.5503,"lng":-46.6339}'::JSONB,
    TIMESTAMPTZ '2026-05-02 18:00:00+00',
    TIMESTAMPTZ '2026-05-02 22:00:00+00',
    TIMESTAMPTZ '2026-04-21 12:20:00+00',
    TIMESTAMPTZ '2026-05-02 17:30:00+00',
    250,
    '16',
    '{"theme":"heritage_night","security_mode":"escorted"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:20:00+00',
    TIMESTAMPTZ '2026-04-21 12:20:00+00'
) ON CONFLICT (event_program_id) DO NOTHING;

INSERT INTO event_ticket_types (
    event_ticket_type_id,
    event_program_id,
    ticket_type_status,
    ticket_name,
    batch_code,
    unit_price_brl,
    inventory_total,
    inventory_available,
    max_per_order,
    is_transferable,
    sales_start_at,
    sales_end_at,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000513',
    '30000000-0000-4000-8000-000000000512',
    'ACTIVE'::event_ticket_type_status_enum,
    'Passe Experiencia Integrada',
    'CITY-BATCH-01',
    180.0000,
    50,
    49,
    4,
    TRUE,
    TIMESTAMPTZ '2026-04-21 12:20:00+00',
    TIMESTAMPTZ '2026-05-02 17:30:00+00',
    '{"bundle":["events","tourism"],"anti_scalping":true}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:20:00+00',
    TIMESTAMPTZ '2026-04-21 12:20:00+00'
) ON CONFLICT (event_ticket_type_id) DO NOTHING;

INSERT INTO transactions (
    transaction_id,
    user_id,
    wallet_id,
    counterparty_user_id,
    counterparty_wallet_id,
    transaction_type,
    transaction_status,
    order_id,
    asset_code,
    amount_brl,
    amount_nex,
    fee_amount_brl,
    platform_amount_brl,
    merchant_amount_brl,
    affiliate_amount_brl,
    escrow_amount_brl,
    fx_rate,
    reference_code,
    external_reference,
    channel,
    origin_module,
    description,
    metadata_json,
    authorized_at,
    settled_at,
    failed_at,
    created_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000514',
        '10000000-0000-4000-8000-000000000302',
        '20000000-0000-4000-8000-000000000302',
        '10000000-0000-4000-8000-000000000301',
        '20000000-0000-4000-8000-000000000301',
        'PAYMENT'::transaction_type_enum,
        'SETTLED'::transaction_status_enum,
        NULL,
        'BRL'::wallet_asset_enum,
        180.0000,
        0.00000000,
        0.0000,
        0.0000,
        180.0000,
        0.0000,
        0.0000,
        NULL,
        'TX-CITY-TICKET-001',
        'city-ticket-001',
        'city_app',
        'EVENTS',
        'Liquidacao do passe integrado de evento e turismo.',
        '{"domain":"city_mobility_security","flow":"event_ticket"}'::JSONB,
        TIMESTAMPTZ '2026-04-21 12:22:00+00',
        TIMESTAMPTZ '2026-04-21 12:23:00+00',
        NULL,
        TIMESTAMPTZ '2026-04-21 12:22:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000525',
        '10000000-0000-4000-8000-000000000302',
        '20000000-0000-4000-8000-000000000302',
        '10000000-0000-4000-8000-000000000301',
        '20000000-0000-4000-8000-000000000301',
        'PAYMENT'::transaction_type_enum,
        'SETTLED'::transaction_status_enum,
        NULL,
        'BRL'::wallet_asset_enum,
        45.0000,
        0.00000000,
        0.0000,
        0.0000,
        45.0000,
        0.0000,
        0.0000,
        NULL,
        'TX-CITY-GOV-001',
        'city-gov-001',
        'citizen_portal',
        'GOV',
        'Pagamento de taxa do servico publico de credencial urbana.',
        '{"domain":"city_mobility_security","flow":"gov_service"}'::JSONB,
        TIMESTAMPTZ '2026-04-21 13:15:00+00',
        TIMESTAMPTZ '2026-04-21 13:16:00+00',
        NULL,
        TIMESTAMPTZ '2026-04-21 13:15:00+00'
    )
ON CONFLICT (transaction_id) DO NOTHING;

INSERT INTO event_ticket_ledger (
    event_ticket_ledger_id,
    ticket_instance_id,
    event_program_id,
    event_ticket_type_id,
    order_id,
    holder_user_id,
    actor_user_id,
    transaction_id,
    ticket_code,
    qr_hash_sha256,
    ticket_status,
    event_type,
    seat_label,
    payload_json,
    occurred_at
) VALUES (
    '30000000-0000-4000-8000-000000000516',
    '30000000-0000-4000-8000-000000000515',
    '30000000-0000-4000-8000-000000000512',
    '30000000-0000-4000-8000-000000000513',
    NULL,
    '10000000-0000-4000-8000-000000000302',
    '10000000-0000-4000-8000-000000000301',
    '30000000-0000-4000-8000-000000000514',
    'CITY-TICKET-0001',
    '5555555555555555555555555555555555555555555555555555555555555555',
    'SOLD'::event_ticket_status_enum,
    'SOLD'::event_ticket_event_type_enum,
    'AREA-C-12',
    '{"domain":"city_mobility_security","experience_bundle":true}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:24:00+00'
) ON CONFLICT (event_ticket_ledger_id) DO NOTHING;

INSERT INTO tourism_experiences (
    experience_id,
    owner_user_id,
    wallet_id,
    module_code,
    experience_code,
    experience_status,
    experience_kind,
    title,
    summary,
    base_price_brl,
    deposit_brl,
    capacity_total,
    duration_minutes,
    city_code,
    meeting_point_json,
    route_snapshot_json,
    event_program_id,
    cover_document_id,
    available_from,
    available_until,
    ops_notes,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000517',
    '10000000-0000-4000-8000-000000000301',
    '20000000-0000-4000-8000-000000000301',
    'TOURISM',
    'CITY_EXP_URBAN_01',
    'ACTIVE'::tourism_experience_status_enum,
    'GUIDED_ROUTE'::tourism_experience_kind_enum,
    'Rota Patrimonial com Escolta Cidada',
    'Experiencia urbana guiada com validacao documental, ticket integrado e protocolo de seguranca.',
    220.0000,
    40.0000,
    20,
    240,
    'SAO_PAULO',
    '{"label":"Pateo do Collegio","lat":-23.5503,"lng":-46.6339}'::JSONB,
    '{"stops":["Pateo do Collegio","Largo Sao Bento","Mosteiro Sao Bento"],"mode":"WALK"}'::JSONB,
    '30000000-0000-4000-8000-000000000512',
    '30000000-0000-4000-8000-000000000501',
    TIMESTAMPTZ '2026-04-22 09:00:00+00',
    TIMESTAMPTZ '2026-12-31 22:00:00+00',
    'Seed usado para consolidar turismo, eventos e seguranca no mesmo dominio.',
    TIMESTAMPTZ '2026-04-21 12:25:00+00',
    TIMESTAMPTZ '2026-04-21 12:25:00+00'
) ON CONFLICT (experience_id) DO NOTHING;

INSERT INTO tourism_bookings (
    booking_id,
    experience_id,
    traveler_user_id,
    wallet_id,
    module_code,
    order_id,
    transaction_id,
    mobility_trip_id,
    assigned_guide_user_id,
    event_ticket_type_id,
    booking_code,
    booking_status,
    quantity,
    unit_price_brl,
    discount_brl,
    total_brl,
    deposit_brl,
    scheduled_start_at,
    scheduled_end_at,
    checked_in_at,
    completed_at,
    cancelled_at,
    cancellation_reason,
    voucher_document_id,
    guest_manifest_json,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000518',
    '30000000-0000-4000-8000-000000000517',
    '10000000-0000-4000-8000-000000000302',
    '20000000-0000-4000-8000-000000000302',
    'TOURISM',
    NULL,
    '30000000-0000-4000-8000-000000000514',
    NULL,
    '10000000-0000-4000-8000-000000000304',
    '30000000-0000-4000-8000-000000000513',
    'CITYBOOK-000001',
    'CONFIRMED'::tourism_booking_status_enum,
    1,
    220.0000,
    40.0000,
    180.0000,
    40.0000,
    TIMESTAMPTZ '2026-05-02 18:00:00+00',
    TIMESTAMPTZ '2026-05-02 22:00:00+00',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{"lead_guest":"Livia Cidada","guests":1}'::JSONB,
    '{"channel":"city_app","bundle":"event_plus_tourism"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:26:00+00',
    TIMESTAMPTZ '2026-04-21 12:26:00+00'
) ON CONFLICT (booking_id) DO NOTHING;

INSERT INTO tourism_booking_events (
    booking_event_id,
    booking_id,
    actor_user_id,
    wallet_id,
    order_id,
    transaction_id,
    mobility_trip_id,
    event_type,
    event_amount_brl,
    guest_count,
    details_json,
    notes,
    occurred_at
) VALUES (
    '30000000-0000-4000-8000-000000000519',
    '30000000-0000-4000-8000-000000000518',
    '10000000-0000-4000-8000-000000000304',
    '20000000-0000-4000-8000-000000000302',
    NULL,
    '30000000-0000-4000-8000-000000000514',
    NULL,
    'CONFIRMED'::tourism_booking_event_type_enum,
    180.0000,
    1,
    '{"source":"seed","status":"confirmed"}'::JSONB,
    'Reserva integrada confirmada para smoke do dominio.',
    TIMESTAMPTZ '2026-04-21 12:27:00+00'
) ON CONFLICT (booking_event_id) DO NOTHING;

INSERT INTO security_trusted_contacts (
    security_contact_id,
    user_id,
    contact_kind,
    contact_name,
    relation_label,
    phone_e164,
    email,
    priority,
    notify_sms,
    notify_email,
    notify_push,
    is_active,
    notes,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000520',
    '10000000-0000-4000-8000-000000000302',
    'FAMILY'::security_contact_kind_enum,
    'Helena Contato',
    'Irma',
    '+5511999550302',
    'helena.contato@nexora.local',
    1,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'Contato principal do fluxo SOS seedado.',
    TIMESTAMPTZ '2026-04-21 12:40:00+00',
    TIMESTAMPTZ '2026-04-21 12:40:00+00'
) ON CONFLICT (security_contact_id) DO NOTHING;

INSERT INTO security_biometric_credentials (
    biometric_credential_id,
    user_id,
    credential_kind,
    credential_status,
    provider_name,
    template_hash,
    device_reference_hash,
    liveness_score,
    enrollment_document_id,
    enrolled_at,
    verified_at,
    revoked_at,
    revocation_reason,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000521',
    '10000000-0000-4000-8000-000000000302',
    'FACE'::biometric_credential_kind_enum,
    'ACTIVE'::biometric_credential_status_enum,
    'NEXORA_SOS',
    '6666666666666666666666666666666666666666666666666666666666666666',
    '7777777777777777777777777777777777777777777777777777777777777777',
    0.9820,
    '30000000-0000-4000-8000-000000000502',
    TIMESTAMPTZ '2026-04-21 12:42:00+00',
    TIMESTAMPTZ '2026-04-21 12:42:30+00',
    NULL,
    NULL,
    '{"provider_flow":"device_enrollment","channel":"panic_guard"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:42:00+00',
    TIMESTAMPTZ '2026-04-21 12:42:30+00'
) ON CONFLICT (biometric_credential_id) DO NOTHING;

INSERT INTO security_incidents (
    security_incident_id,
    module_code,
    user_id,
    reporter_user_id,
    rider_user_id,
    order_id,
    trip_id,
    shipment_id,
    legal_dispute_id,
    incident_type,
    severity,
    incident_status,
    title,
    description,
    address_json,
    geo_json,
    correlation_id,
    risk_score,
    evidence_document_id,
    opened_at,
    acknowledged_at,
    escalation_deadline_at,
    resolved_at,
    resolution_summary,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000522',
    'SECURITY',
    '10000000-0000-4000-8000-000000000302',
    '10000000-0000-4000-8000-000000000303',
    NULL,
    NULL,
    NULL,
    NULL,
    '30000000-0000-4000-8000-000000000509',
    'SOS'::security_incident_type_enum,
    'HIGH'::security_incident_severity_enum,
    'ESCALATED'::security_incident_status_enum,
    'Botao SOS acionado em rota patrimonial',
    'Incidente aberto durante deslocamento entre checkpoints do circuito urbano.',
    '{"street":"Largo Sao Bento","city":"Sao Paulo","state":"SP"}'::JSONB,
    '{"lat":-23.5458,"lng":-46.6351}'::JSONB,
    'CITY-SOS-0001',
    92,
    '30000000-0000-4000-8000-000000000502',
    TIMESTAMPTZ '2026-04-21 12:50:00+00',
    TIMESTAMPTZ '2026-04-21 12:51:00+00',
    TIMESTAMPTZ '2026-04-21 13:05:00+00',
    NULL,
    NULL,
    '{"domain":"city_mobility_security","playbook":"escort_dispatch"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:50:00+00',
    TIMESTAMPTZ '2026-04-21 12:51:00+00'
) ON CONFLICT (security_incident_id) DO NOTHING;

INSERT INTO security_incident_events (
    security_incident_event_id,
    security_incident_id,
    actor_user_id,
    event_type,
    incident_status,
    notified_contact_id,
    document_id,
    notes,
    payload_json,
    occurred_at
) VALUES (
    '30000000-0000-4000-8000-000000000523',
    '30000000-0000-4000-8000-000000000522',
    '10000000-0000-4000-8000-000000000303',
    'CONTACT_NOTIFIED'::security_incident_event_type_enum,
    'ESCALATED'::security_incident_status_enum,
    '30000000-0000-4000-8000-000000000520',
    '30000000-0000-4000-8000-000000000502',
    'Contato confiavel notificado e protocolo de escolta iniciado.',
    '{"channel":"sms_push","playbook":"escort_dispatch"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:52:00+00'
) ON CONFLICT (security_incident_event_id) DO NOTHING;

INSERT INTO mobility.cost_benchmarks (
    benchmark_id,
    user_id,
    module_code,
    route_fingerprint,
    region_code,
    benchmark_status,
    observed_at,
    expires_at,
    origin_geo_json,
    destination_geo_json,
    estimated_distance_km,
    estimated_duration_sec,
    valley_estimated_brl,
    valley_max_accepted_brl,
    competitor_lowest_brl,
    competitor_median_brl,
    competitor_highest_brl,
    provider_quotes_json,
    selected_provider,
    notes,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000529',
    '10000000-0000-4000-8000-000000000302',
    'MOBILITY',
    'city-mobility-security:rota-patrimonial:livia:20260421',
    'BR-SP-SAO_PAULO',
    'ACTIVE'::mobility.cost_benchmark_status_enum,
    TIMESTAMPTZ '2026-04-21 12:28:00+00',
    TIMESTAMPTZ '2026-04-21 13:28:00+00',
    '{"label":"Pateo do Collegio","lat":-23.5503,"lng":-46.6339}'::JSONB,
    '{"label":"Mosteiro Sao Bento","lat":-23.5449,"lng":-46.6345}'::JSONB,
    3.250,
    780,
    18.0000,
    22.0000,
    24.9000,
    29.5000,
    38.0000,
    '[{"provider":"UBER","price_brl":29.5},{"provider":"99","price_brl":24.9},{"provider":"TAXI_LOCAL","price_brl":38.0}]'::JSONB,
    'VALLEY_MOVE',
    'Benchmark seedado para prova de rota Mobility em modo producao local.',
    '{"domain":"city_mobility_security","source":"mobility_production_schema"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:28:00+00',
    TIMESTAMPTZ '2026-04-21 12:28:00+00'
) ON CONFLICT (benchmark_id) DO NOTHING;

INSERT INTO mobility.user_routes (
    route_id,
    user_id,
    wallet_id,
    module_code,
    order_id,
    trip_id,
    benchmark_id,
    route_status,
    route_kind,
    route_fingerprint,
    origin_label,
    destination_label,
    origin_geo_json,
    destination_geo_json,
    waypoints_json,
    requested_modes,
    selected_mode,
    selected_provider,
    planned_for,
    estimate_expires_at,
    estimated_distance_km,
    estimated_duration_sec,
    estimated_cost_brl,
    carbon_estimate_kg,
    accessibility_flags,
    safety_context_json,
    pricing_snapshot_json,
    routing_engine,
    trace_id,
    accepted_at,
    started_at,
    completed_at,
    cancelled_at,
    cancellation_reason,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000530',
    '10000000-0000-4000-8000-000000000302',
    '20000000-0000-4000-8000-000000000302',
    'MOBILITY',
    NULL,
    NULL,
    '30000000-0000-4000-8000-000000000529',
    'OFFERED'::mobility.route_status_enum,
    'TOURISM'::mobility.route_kind_enum,
    'city-mobility-security:rota-patrimonial:livia:20260421',
    'Pateo do Collegio',
    'Mosteiro Sao Bento',
    '{"label":"Pateo do Collegio","lat":-23.5503,"lng":-46.6339}'::JSONB,
    '{"label":"Mosteiro Sao Bento","lat":-23.5449,"lng":-46.6345}'::JSONB,
    '[{"label":"Largo Sao Bento","lat":-23.5458,"lng":-46.6351}]'::JSONB,
    ARRAY['MOBILITY','WALK']::TEXT[],
    'MOBILITY',
    'VALLEY_MOVE',
    TIMESTAMPTZ '2026-05-02 18:00:00+00',
    TIMESTAMPTZ '2026-04-21 13:28:00+00',
    3.250,
    780,
    18.0000,
    0.760000,
    ARRAY['SAFE_ROUTE','TOURISM_ESCORT']::TEXT[],
    '{"sos_enabled":true,"trusted_contact_id":"30000000-0000-4000-8000-000000000520","risk_score":22}'::JSONB,
    '{"benchmark_id":"30000000-0000-4000-8000-000000000529","valley_estimated_brl":18.0,"competitor_lowest_brl":24.9}'::JSONB,
    'VALLEY_ROUTER',
    'city-mobility-route-0001',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{"domain":"city_mobility_security","playbook":"tourism_escort_route"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:29:00+00',
    TIMESTAMPTZ '2026-04-21 12:29:00+00'
) ON CONFLICT (route_id) DO NOTHING;

INSERT INTO mobility.realtime_buffer (
    buffer_id,
    user_id,
    module_code,
    route_id,
    order_id,
    trip_id,
    subject_role,
    source_kind,
    buffer_status,
    source_reference,
    geo_json,
    heading_degrees,
    speed_kph,
    accuracy_meters,
    battery_level,
    network_quality,
    eta_seconds,
    distance_remaining_km,
    captured_at,
    received_at,
    expires_at,
    trace_id,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000531',
    '10000000-0000-4000-8000-000000000302',
    'MOBILITY',
    '30000000-0000-4000-8000-000000000530',
    NULL,
    NULL,
    'PASSENGER'::mobility.realtime_subject_role_enum,
    'APP'::mobility.realtime_source_kind_enum,
    'ACTIVE'::mobility.realtime_buffer_status_enum,
    'city-mobile-app:livia',
    '{"lat":-23.5501,"lng":-46.6340,"accuracy":8.5}'::JSONB,
    22.50,
    4.800,
    8.500,
    82.00,
    'LTE_GOOD',
    720,
    2.950,
    TIMESTAMPTZ '2026-04-21 12:30:00+00',
    TIMESTAMPTZ '2026-04-21 12:30:03+00',
    TIMESTAMPTZ '2026-04-21 12:35:00+00',
    'city-mobility-route-0001',
    '{"domain":"city_mobility_security","source":"app_location","privacy":"coarse_for_ops"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 12:30:03+00',
    TIMESTAMPTZ '2026-04-21 12:30:03+00'
) ON CONFLICT (buffer_id) DO NOTHING;

INSERT INTO gov_service_catalog (
    gov_service_id,
    owner_user_id,
    wallet_id,
    module_code,
    service_code,
    service_status,
    service_title,
    department_name,
    fee_brl,
    sla_business_days,
    delivery_mode,
    requirements_json,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000524',
    '10000000-0000-4000-8000-000000000301',
    '20000000-0000-4000-8000-000000000301',
    'GOV',
    'URBAN_PASS_01',
    'ACTIVE'::gov_service_status_enum,
    'Credencial Urbana Integrada',
    'Secretaria de Mobilidade e Cultura',
    45.0000,
    5,
    'DIGITAL',
    '{"documents":["cpf","comprovante_residencia"],"eligibility":"resident"}'::JSONB,
    '{"service_family":"citizen_pass","channel":"portal"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 13:10:00+00',
    TIMESTAMPTZ '2026-04-21 13:10:00+00'
) ON CONFLICT (gov_service_id) DO NOTHING;

INSERT INTO gov_service_requests (
    gov_request_id,
    gov_service_id,
    requester_user_id,
    assigned_officer_user_id,
    wallet_id,
    module_code,
    request_status,
    protocol_code,
    request_fee_transaction_id,
    legal_contract_id,
    document_id,
    submitted_payload_json,
    response_json,
    notes,
    submitted_at,
    scheduled_at,
    resolved_at,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000526',
    '30000000-0000-4000-8000-000000000524',
    '10000000-0000-4000-8000-000000000302',
    '10000000-0000-4000-8000-000000000303',
    '20000000-0000-4000-8000-000000000302',
    'GOV',
    'FULFILLED'::gov_request_status_enum,
    'GOV-SP-20260421-0001',
    '30000000-0000-4000-8000-000000000525',
    '30000000-0000-4000-8000-000000000504',
    '30000000-0000-4000-8000-000000000503',
    '{"citizen_type":"resident","request":"urban_pass"}'::JSONB,
    '{"result":"approved","credential_code":"PASS-SP-001"}'::JSONB,
    'Fluxo seedado para amarrar taxa, contrato e entrega digital.',
    TIMESTAMPTZ '2026-04-21 13:20:00+00',
    TIMESTAMPTZ '2026-04-22 10:00:00+00',
    TIMESTAMPTZ '2026-04-22 11:30:00+00',
    TIMESTAMPTZ '2026-04-21 13:20:00+00',
    TIMESTAMPTZ '2026-04-22 11:30:00+00'
) ON CONFLICT (gov_request_id) DO NOTHING;

INSERT INTO gov_request_events (
    gov_request_event_id,
    gov_request_id,
    actor_user_id,
    document_id,
    event_type,
    details_json,
    occurred_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000527',
        '30000000-0000-4000-8000-000000000526',
        '10000000-0000-4000-8000-000000000302',
        '30000000-0000-4000-8000-000000000503',
        'SUBMITTED'::gov_request_event_type_enum,
        '{"source":"citizen_portal","stage":"submission"}'::JSONB,
        TIMESTAMPTZ '2026-04-21 13:20:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000528',
        '30000000-0000-4000-8000-000000000526',
        '10000000-0000-4000-8000-000000000303',
        '30000000-0000-4000-8000-000000000503',
        'FULFILLED'::gov_request_event_type_enum,
        '{"result":"credential_delivered","credential_code":"PASS-SP-001"}'::JSONB,
        TIMESTAMPTZ '2026-04-22 11:30:00+00'
    )
ON CONFLICT (gov_request_event_id) DO NOTHING;

COMMIT;
