BEGIN;

-- Seed operacional idempotente dos pacotes fisicos por dominio prioritario.
-- Gerado automaticamente por scripts/automacao_sincronizador_modulos.py.

WITH package_source (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
) AS (
    VALUES
    ('city_mobility_security.priority.v1', 'city_mobility_security', 'City Mobility Security', 2, 'priority_domains_v1', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"artifacts":[{"artifact_key":"city_mobility_security.ddl.v1","artifact_path":"database/domain-delivery/priority-domains/city_mobility_security/ddl_complement.sql","layer_type":"DDL_COMPLEMENT","target_engine":"postgres"},{"artifact_key":"city_mobility_security.seed.v1","artifact_path":"database/domain-delivery/priority-domains/city_mobility_security/operational_seed.sql","layer_type":"OPERATIONS_SEED","target_engine":"postgres"},{"artifact_key":"city_mobility_security.contract.v1","artifact_path":"contracts/events/priority-domains/city_mobility_security.json","layer_type":"EVENT_CONTRACT","target_engine":"filesystem"}],"backlog_keys":["LEGAL.exec.01","LEGAL.exec.02","EVENTS.exec.01","EVENTS.exec.02","MOBILITY.exec.01","MOBILITY.exec.02","SECURITY.exec.01","SECURITY.exec.02","LEGAL.exec.03","TOURISM.exec.01","TOURISM.exec.02","EVENTS.exec.03","MOBILITY.exec.03","SECURITY.exec.03","GOV.exec.01","GOV.exec.02","TOURISM.exec.03","GOV.exec.03"],"domain_key":"city_mobility_security","domain_label":"City Mobility Security","event_topics":["legal.contract.created","legal.signature.recorded","legal.dispute.opened","events.program.published","events.ticket.issued","events.ticket.transferred","mobility.trip.requested","mobility.trip.started","mobility.trip.completed","security.sos.triggered","security.biometric.enrolled","security.incident.closed","tourism.experience.published","tourism.booking.confirmed","tourism.checkin.recorded","gov.service.requested","gov.request.routed","gov.request.resolved"],"modules":["LEGAL","EVENTS","MOBILITY","SECURITY","TOURISM","GOV"],"package_key":"city_mobility_security.priority.v1","priority_rank":2}'::JSONB)
)
INSERT INTO domain_delivery_packages (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
)
SELECT
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
FROM package_source
ON CONFLICT (package_key) DO UPDATE SET
    domain_key = EXCLUDED.domain_key,
    domain_label = EXCLUDED.domain_label,
    priority_rank = EXCLUDED.priority_rank,
    package_scope = EXCLUDED.package_scope,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    package_status = EXCLUDED.package_status,
    artifact_manifest_json = EXCLUDED.artifact_manifest_json,
    updated_at = NOW();

WITH artifact_source (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
) AS (
    VALUES
    ('city_mobility_security.ddl.v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'DDL_COMPLEMENT'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/city_mobility_security/ddl_complement.sql', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], ARRAY[]::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"package_key":"city_mobility_security.priority.v1","priority_rank":2,"views":["v_city_mobility_security_priority_backlog","v_city_mobility_security_delivery_artifacts","v_city_mobility_security_event_contracts"]}'::JSONB),
    ('city_mobility_security.seed.v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'OPERATIONS_SEED'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/city_mobility_security/operational_seed.sql', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], ARRAY['city_mobility_security.ddl.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"contract_count":18,"package_key":"city_mobility_security.priority.v1","seed_scope":"priority_domain_delivery_v1"}'::JSONB),
    ('city_mobility_security.contract.v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENT_CONTRACT'::domain_delivery_layer_enum, 'filesystem', 'contracts/events/priority-domains/city_mobility_security.json', ARRAY['LEGAL', 'EVENTS', 'MOBILITY', 'SECURITY', 'TOURISM', 'GOV']::TEXT[], ARRAY['LEGAL.exec.01', 'LEGAL.exec.02', 'EVENTS.exec.01', 'EVENTS.exec.02', 'MOBILITY.exec.01', 'MOBILITY.exec.02', 'SECURITY.exec.01', 'SECURITY.exec.02', 'LEGAL.exec.03', 'TOURISM.exec.01', 'TOURISM.exec.02', 'EVENTS.exec.03', 'MOBILITY.exec.03', 'SECURITY.exec.03', 'GOV.exec.01', 'GOV.exec.02', 'TOURISM.exec.03', 'GOV.exec.03']::TEXT[], ARRAY['city_mobility_security.ddl.v1', 'city_mobility_security.seed.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"event_topics":["legal.contract.created","legal.signature.recorded","legal.dispute.opened","events.program.published","events.ticket.issued","events.ticket.transferred","mobility.trip.requested","mobility.trip.started","mobility.trip.completed","security.sos.triggered","security.biometric.enrolled","security.incident.closed","tourism.experience.published","tourism.booking.confirmed","tourism.checkin.recorded","gov.service.requested","gov.request.routed","gov.request.resolved"],"package_key":"city_mobility_security.priority.v1"}'::JSONB)
)
INSERT INTO domain_delivery_artifacts (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
)
SELECT
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
FROM artifact_source
ON CONFLICT (artifact_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    layer_type = EXCLUDED.layer_type,
    target_engine = EXCLUDED.target_engine,
    artifact_path = EXCLUDED.artifact_path,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    depends_on_keys = EXCLUDED.depends_on_keys,
    artifact_status = EXCLUDED.artifact_status,
    artifact_payload_json = EXCLUDED.artifact_payload_json,
    updated_at = NOW();

WITH contract_source (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
) AS (
    VALUES
    ('LEGAL:legal.contract.created:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'LEGAL', 'legal.contract.created', '1.0.0', 'painel juridico', ARRAY['DOCS', 'SECURITY', 'painel juridico', 'fila de assinaturas']::TEXT[], ARRAY['legal_contracts', 'legal_contract_parties', 'legal_signatures']::TEXT[], ARRAY['legal_audit', 'signature_traceability', 'fallback_pin_hashing']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["legal_audit","signature_traceability","fallback_pin_hashing"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"legal.contract.created"},"evidence_refs":{"items":{"enum":["legal_contracts","legal_contract_parties","legal_signatures"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LEGAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contratos","assinaturas","disputas e trilha juridica"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["juridico","assinante","mediador"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LEGAL::legal.contract.created","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('LEGAL:legal.signature.recorded:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'LEGAL', 'legal.signature.recorded', '1.0.0', 'painel juridico', ARRAY['DOCS', 'SECURITY', 'painel juridico', 'fila de assinaturas']::TEXT[], ARRAY['legal_contracts', 'legal_contract_parties', 'legal_signatures']::TEXT[], ARRAY['legal_audit', 'signature_traceability', 'fallback_pin_hashing']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["legal_audit","signature_traceability","fallback_pin_hashing"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"legal.signature.recorded"},"evidence_refs":{"items":{"enum":["legal_contracts","legal_contract_parties","legal_signatures"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LEGAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contratos","assinaturas","disputas e trilha juridica"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["juridico","assinante","mediador"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LEGAL::legal.signature.recorded","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('LEGAL:legal.dispute.opened:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'LEGAL', 'legal.dispute.opened', '1.0.0', 'painel juridico', ARRAY['DOCS', 'SECURITY', 'painel juridico', 'fila de assinaturas']::TEXT[], ARRAY['legal_contracts', 'legal_contract_parties', 'legal_signatures']::TEXT[], ARRAY['legal_audit', 'signature_traceability', 'fallback_pin_hashing']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["legal_audit","signature_traceability","fallback_pin_hashing"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"legal.dispute.opened"},"evidence_refs":{"items":{"enum":["legal_contracts","legal_contract_parties","legal_signatures"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LEGAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contratos","assinaturas","disputas e trilha juridica"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["juridico","assinante","mediador"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LEGAL::legal.dispute.opened","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('EVENTS:events.program.published:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENTS', 'events.program.published', '1.0.0', 'painel de eventos', ARRAY['TICKETS', 'DOCS', 'painel de eventos', 'monitor de bilheteria']::TEXT[], ARRAY['event_programs', 'event_ticket_types', 'event_ticket_ledger']::TEXT[], ARRAY['ticket_immutability', 'escrow_audit', 'fraud_prevention']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ticket_immutability","escrow_audit","fraud_prevention"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"events.program.published"},"evidence_refs":{"items":{"enum":["event_programs","event_ticket_types","event_ticket_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"EVENTS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["programacao de evento","tipos de ingresso","ledger de tickets"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["organizador","participante","operador de bilheteria"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"EVENTS::events.program.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('EVENTS:events.ticket.issued:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENTS', 'events.ticket.issued', '1.0.0', 'painel de eventos', ARRAY['TICKETS', 'DOCS', 'painel de eventos', 'monitor de bilheteria']::TEXT[], ARRAY['event_programs', 'event_ticket_types', 'event_ticket_ledger']::TEXT[], ARRAY['ticket_immutability', 'escrow_audit', 'fraud_prevention']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ticket_immutability","escrow_audit","fraud_prevention"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"events.ticket.issued"},"evidence_refs":{"items":{"enum":["event_programs","event_ticket_types","event_ticket_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"EVENTS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["programacao de evento","tipos de ingresso","ledger de tickets"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["organizador","participante","operador de bilheteria"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"EVENTS::events.ticket.issued","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('EVENTS:events.ticket.transferred:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'EVENTS', 'events.ticket.transferred', '1.0.0', 'painel de eventos', ARRAY['TICKETS', 'DOCS', 'painel de eventos', 'monitor de bilheteria']::TEXT[], ARRAY['event_programs', 'event_ticket_types', 'event_ticket_ledger']::TEXT[], ARRAY['ticket_immutability', 'escrow_audit', 'fraud_prevention']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ticket_immutability","escrow_audit","fraud_prevention"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"events.ticket.transferred"},"evidence_refs":{"items":{"enum":["event_programs","event_ticket_types","event_ticket_ledger"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"EVENTS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["programacao de evento","tipos de ingresso","ledger de tickets"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["organizador","participante","operador de bilheteria"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"EVENTS::events.ticket.transferred","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('MOBILITY:mobility.trip.requested:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'MOBILITY', 'mobility.trip.requested', '1.0.0', 'torre de corridas', ARRAY['LOG', 'FLEET', 'torre de corridas', 'monitor de checkpoints']::TEXT[], ARRAY['mobility_trips', 'mobility_trip_events', 'orders', 'fleet_vehicle_profiles', 'telemetry_logs']::TEXT[], ARRAY['ride_audit', 'driver_accountability', 'fare_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ride_audit","driver_accountability","fare_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"mobility.trip.requested"},"evidence_refs":{"items":{"enum":["mobility_trips","mobility_trip_events","orders","fleet_vehicle_profiles","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MOBILITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["corrida urbana","checkpoint operacional","precificacao de rota"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["passageiro","rider","dispatcher"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MOBILITY::mobility.trip.requested","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('MOBILITY:mobility.trip.started:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'MOBILITY', 'mobility.trip.started', '1.0.0', 'torre de corridas', ARRAY['LOG', 'FLEET', 'torre de corridas', 'monitor de checkpoints']::TEXT[], ARRAY['mobility_trips', 'mobility_trip_events', 'orders', 'fleet_vehicle_profiles', 'telemetry_logs']::TEXT[], ARRAY['ride_audit', 'driver_accountability', 'fare_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ride_audit","driver_accountability","fare_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"mobility.trip.started"},"evidence_refs":{"items":{"enum":["mobility_trips","mobility_trip_events","orders","fleet_vehicle_profiles","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MOBILITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["corrida urbana","checkpoint operacional","precificacao de rota"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["passageiro","rider","dispatcher"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MOBILITY::mobility.trip.started","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('MOBILITY:mobility.trip.completed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'MOBILITY', 'mobility.trip.completed', '1.0.0', 'torre de corridas', ARRAY['LOG', 'FLEET', 'torre de corridas', 'monitor de checkpoints']::TEXT[], ARRAY['mobility_trips', 'mobility_trip_events', 'orders', 'fleet_vehicle_profiles', 'telemetry_logs']::TEXT[], ARRAY['ride_audit', 'driver_accountability', 'fare_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ride_audit","driver_accountability","fare_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"mobility.trip.completed"},"evidence_refs":{"items":{"enum":["mobility_trips","mobility_trip_events","orders","fleet_vehicle_profiles","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MOBILITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["corrida urbana","checkpoint operacional","precificacao de rota"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["passageiro","rider","dispatcher"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MOBILITY::mobility.trip.completed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('SECURITY:security.sos.triggered:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'SECURITY', 'security.sos.triggered', '1.0.0', 'torre de seguranca', ARRAY['IOT', 'LEGAL', 'torre de seguranca', 'fila de incidentes']::TEXT[], ARRAY['security_trusted_contacts', 'security_biometric_credentials', 'security_incidents', 'security_signal_logs', 'iot_sensor_events']::TEXT[], ARRAY['biometric_hashing', 'incident_chain_of_custody', 'access_control']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["biometric_hashing","incident_chain_of_custody","access_control"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"security.sos.triggered"},"evidence_refs":{"items":{"enum":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_signal_logs","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SECURITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario protegido","analista de risco","operador SOS"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SECURITY::security.sos.triggered","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('SECURITY:security.biometric.enrolled:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'SECURITY', 'security.biometric.enrolled', '1.0.0', 'torre de seguranca', ARRAY['IOT', 'LEGAL', 'torre de seguranca', 'fila de incidentes']::TEXT[], ARRAY['security_trusted_contacts', 'security_biometric_credentials', 'security_incidents', 'security_signal_logs', 'iot_sensor_events']::TEXT[], ARRAY['biometric_hashing', 'incident_chain_of_custody', 'access_control']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["biometric_hashing","incident_chain_of_custody","access_control"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"security.biometric.enrolled"},"evidence_refs":{"items":{"enum":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_signal_logs","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SECURITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario protegido","analista de risco","operador SOS"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SECURITY::security.biometric.enrolled","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('SECURITY:security.incident.closed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'SECURITY', 'security.incident.closed', '1.0.0', 'torre de seguranca', ARRAY['IOT', 'LEGAL', 'torre de seguranca', 'fila de incidentes']::TEXT[], ARRAY['security_trusted_contacts', 'security_biometric_credentials', 'security_incidents', 'security_signal_logs', 'iot_sensor_events']::TEXT[], ARRAY['biometric_hashing', 'incident_chain_of_custody', 'access_control']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["biometric_hashing","incident_chain_of_custody","access_control"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"security.incident.closed"},"evidence_refs":{"items":{"enum":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_signal_logs","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SECURITY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["usuario protegido","analista de risco","operador SOS"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SECURITY::security.incident.closed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('TOURISM:tourism.experience.published:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'TOURISM', 'tourism.experience.published', '1.0.0', 'painel de experiencias', ARRAY['EVENTS', 'MOBILITY', 'painel de experiencias', 'fila de bookings']::TEXT[], ARRAY['tourism_experiences', 'tourism_bookings', 'tourism_booking_events', 'tourism_experience_feeds', 'space_anchor_maps']::TEXT[], ARRAY['booking_audit', 'guide_accountability', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["booking_audit","guide_accountability","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"tourism.experience.published"},"evidence_refs":{"items":{"enum":["tourism_experiences","tourism_bookings","tourism_booking_events","tourism_experience_feeds","space_anchor_maps"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"TOURISM"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["experiencias locais","booking","feed exploratorio"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["turista","guia","operador local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"TOURISM::tourism.experience.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('TOURISM:tourism.booking.confirmed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'TOURISM', 'tourism.booking.confirmed', '1.0.0', 'painel de experiencias', ARRAY['EVENTS', 'MOBILITY', 'painel de experiencias', 'fila de bookings']::TEXT[], ARRAY['tourism_experiences', 'tourism_bookings', 'tourism_booking_events', 'tourism_experience_feeds', 'space_anchor_maps']::TEXT[], ARRAY['booking_audit', 'guide_accountability', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["booking_audit","guide_accountability","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"tourism.booking.confirmed"},"evidence_refs":{"items":{"enum":["tourism_experiences","tourism_bookings","tourism_booking_events","tourism_experience_feeds","space_anchor_maps"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"TOURISM"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["experiencias locais","booking","feed exploratorio"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["turista","guia","operador local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"TOURISM::tourism.booking.confirmed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('TOURISM:tourism.checkin.recorded:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'TOURISM', 'tourism.checkin.recorded', '1.0.0', 'painel de experiencias', ARRAY['EVENTS', 'MOBILITY', 'painel de experiencias', 'fila de bookings']::TEXT[], ARRAY['tourism_experiences', 'tourism_bookings', 'tourism_booking_events', 'tourism_experience_feeds', 'space_anchor_maps']::TEXT[], ARRAY['booking_audit', 'guide_accountability', 'settlement_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["booking_audit","guide_accountability","settlement_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"tourism.checkin.recorded"},"evidence_refs":{"items":{"enum":["tourism_experiences","tourism_bookings","tourism_booking_events","tourism_experience_feeds","space_anchor_maps"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"TOURISM"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["experiencias locais","booking","feed exploratorio"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["turista","guia","operador local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"TOURISM::tourism.checkin.recorded","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('GOV:gov.service.requested:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'GOV', 'gov.service.requested', '1.0.0', 'portal de requests', ARRAY['LEGAL', 'DOCS', 'portal de requests', 'fila de atendimento']::TEXT[], ARRAY['gov_service_catalog', 'gov_service_requests', 'gov_request_events']::TEXT[], ARRAY['public_auditability', 'citizen_identity', 'service_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["public_auditability","citizen_identity","service_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gov.service.requested"},"evidence_refs":{"items":{"enum":["gov_service_catalog","gov_service_requests","gov_request_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GOV"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["catalogo de servicos","requests publicos","eventos de atendimento"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["cidadao","servidor","operador govtech"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GOV::gov.service.requested","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('GOV:gov.request.routed:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'GOV', 'gov.request.routed', '1.0.0', 'portal de requests', ARRAY['LEGAL', 'DOCS', 'portal de requests', 'fila de atendimento']::TEXT[], ARRAY['gov_service_catalog', 'gov_service_requests', 'gov_request_events']::TEXT[], ARRAY['public_auditability', 'citizen_identity', 'service_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["public_auditability","citizen_identity","service_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gov.request.routed"},"evidence_refs":{"items":{"enum":["gov_service_catalog","gov_service_requests","gov_request_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GOV"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["catalogo de servicos","requests publicos","eventos de atendimento"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["cidadao","servidor","operador govtech"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GOV::gov.request.routed","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json'),
    ('GOV:gov.request.resolved:v1', 'city_mobility_security.priority.v1', 'city_mobility_security', 'GOV', 'gov.request.resolved', '1.0.0', 'portal de requests', ARRAY['LEGAL', 'DOCS', 'portal de requests', 'fila de atendimento']::TEXT[], ARRAY['gov_service_catalog', 'gov_service_requests', 'gov_request_events']::TEXT[], ARRAY['public_auditability', 'citizen_identity', 'service_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["public_auditability","citizen_identity","service_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"city_mobility_security"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gov.request.resolved"},"evidence_refs":{"items":{"enum":["gov_service_catalog","gov_service_requests","gov_request_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GOV"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["catalogo de servicos","requests publicos","eventos de atendimento"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["cidadao","servidor","operador govtech"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GOV::gov.request.resolved","type":"object"}'::JSONB, 'contracts/events/priority-domains/city_mobility_security.json')
)
INSERT INTO domain_event_contracts (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
)
SELECT
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
FROM contract_source
ON CONFLICT (contract_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    module_code = EXCLUDED.module_code,
    event_topic = EXCLUDED.event_topic,
    contract_version = EXCLUDED.contract_version,
    producer_surface = EXCLUDED.producer_surface,
    consumer_surfaces = EXCLUDED.consumer_surfaces,
    evidence_entities = EXCLUDED.evidence_entities,
    compliance_tags = EXCLUDED.compliance_tags,
    contract_status = EXCLUDED.contract_status,
    payload_schema_json = EXCLUDED.payload_schema_json,
    artifact_path = EXCLUDED.artifact_path,
    updated_at = NOW();

COMMIT;
