-- Valley Hybrid DB Bootstrap - Documentacao interna em Portugues do Brasil.
-- Este script adiciona comentarios nativos do PostgreSQL para schema, colunas, funcoes e triggers.
-- Execute depois de 001_core_identity_wallets.sql e 002_financial_ledger_equity_orders.sql.

BEGIN;

SET search_path = public;

COMMENT ON TYPE user_kind_enum IS 'Define o tipo principal do usuario no core: PF, PJ, RIDER, ADMIN ou SYSTEM.';
COMMENT ON TYPE account_status_enum IS 'Define o lifecycle status da conta para operacao, bloqueio e suporte.';
COMMENT ON TYPE kyc_status_enum IS 'Define o status de verificacao KYC/KYB usado por identidade, PJ e compliance.';
COMMENT ON TYPE wallet_asset_enum IS 'Define o ativo financeiro da wallet: BRL para moeda fiduciaria e NEX para token interno.';
COMMENT ON TYPE wallet_type_enum IS 'Define a finalidade da wallet: custodial, escrow, rewards, settlement ou equity.';
COMMENT ON TYPE wallet_status_enum IS 'Define o status operacional da wallet para uso, bloqueio ou encerramento.';
COMMENT ON TYPE led_card_status_enum IS 'Define o status do LED Card/NFC fisico integrado ao usuario e wallet.';
COMMENT ON TYPE rider_status_enum IS 'Define o status operacional do rider no modulo de mobilidade e logistica.';
COMMENT ON TYPE transaction_type_enum IS 'Define o tipo de lancamento financeiro no ledger transacional.';
COMMENT ON TYPE transaction_status_enum IS 'Define o status de autorizacao, liquidacao ou falha da transacao.';
COMMENT ON TYPE equity_event_type_enum IS 'Define o tipo de evento do Smart Equity ledger para tokens NEX.';
COMMENT ON TYPE order_domain_enum IS 'Define o dominio do pedido mestre: Food, Move ou Dropship.';
COMMENT ON TYPE order_status_enum IS 'Define o lifecycle status de um pedido operacional.';

COMMENT ON TABLE users IS 'Tabela central absoluta de identidade. Todas as entidades de usuario devem integrar com users.user_id.';
COMMENT ON COLUMN users.user_id IS 'Primary key UUID do usuario, usado como FK central por todos os modulos.';
COMMENT ON COLUMN users.user_kind IS 'Classifica o usuario como PF, PJ, RIDER, ADMIN ou SYSTEM.';
COMMENT ON COLUMN users.account_status IS 'Controla se a conta esta pendente, ativa, suspensa, bloqueada ou arquivada.';
COMMENT ON COLUMN users.kyc_status IS 'Registra o estado de verificacao KYC da identidade.';
COMMENT ON COLUMN users.full_name IS 'Nome legal ou principal do usuario para identidade e compliance.';
COMMENT ON COLUMN users.display_name IS 'Nome publico ou amigavel exibido em apps e paineis.';
COMMENT ON COLUMN users.email IS 'Email unico opcional para login, notificacao e suporte.';
COMMENT ON COLUMN users.phone_e164 IS 'Telefone em padrao E.164 para autenticacao, notificacoes e antifraude.';
COMMENT ON COLUMN users.birth_date IS 'Data de nascimento usada quando a conta representa pessoa fisica.';
COMMENT ON COLUMN users.document_country IS 'Pais emissor do documento no padrao ISO alpha-2.';
COMMENT ON COLUMN users.document_type IS 'Tipo de documento, como CPF, CNPJ, passaporte ou documento interno.';
COMMENT ON COLUMN users.document_number IS 'Numero do documento usado para unicidade regulatoria.';
COMMENT ON COLUMN users.nationality IS 'Nacionalidade ISO alpha-2 quando aplicavel.';
COMMENT ON COLUMN users.tax_residence_country IS 'Pais de residencia fiscal para compliance e reporting.';
COMMENT ON COLUMN users.risk_level IS 'Nivel simples de risco de 0 a 5 para KYC, fraude e operacao.';
COMMENT ON COLUMN users.primary_role IS 'Papel principal usado por RBAC/ABAC e Web Admin.';
COMMENT ON COLUMN users.nexus_external_ref IS 'Referencia externa do Valley ID ou provedor de identidade.';
COMMENT ON COLUMN users.led_card_default_id IS 'LED Card padrao do usuario, integrado a led_cards.led_card_id.';
COMMENT ON COLUMN users.terms_accepted_at IS 'Timestamp de aceite dos termos de uso.';
COMMENT ON COLUMN users.privacy_accepted_at IS 'Timestamp de aceite de privacidade e consentimento.';
COMMENT ON COLUMN users.last_login_at IS 'Ultimo login conhecido para seguranca e suporte.';
COMMENT ON COLUMN users.module_tier IS 'Nivel de modulo/plano para expansao operacional dos 37 modulos.';
COMMENT ON COLUMN users.ops_region_code IS 'Regiao operacional do usuario para suporte, logistica e compliance.';
COMMENT ON COLUMN users.compliance_notes IS 'Notas internas de compliance com uso controlado.';
COMMENT ON COLUMN users.internal_tags IS 'Tags internas para segmentacao operacional e suporte.';
COMMENT ON COLUMN users.created_at IS 'Data de criacao do registro.';
COMMENT ON COLUMN users.updated_at IS 'Data da ultima atualizacao logica controlada por trigger.';

COMMENT ON TABLE pj_profiles IS 'Perfil empresarial de usuarios PJ, integrado um-para-um com users.user_id.';
COMMENT ON COLUMN pj_profiles.pj_profile_id IS 'Primary key UUID do perfil PJ.';
COMMENT ON COLUMN pj_profiles.user_id IS 'FK para users.user_id; exige user_kind PJ por trigger.';
COMMENT ON COLUMN pj_profiles.legal_name IS 'Razao social legal da empresa.';
COMMENT ON COLUMN pj_profiles.trade_name IS 'Nome fantasia usado em marketplace, fiscal e Web Admin.';
COMMENT ON COLUMN pj_profiles.cnpj IS 'CNPJ numerico de 14 digitos com unicidade obrigatoria.';
COMMENT ON COLUMN pj_profiles.state_registration IS 'Inscricao estadual quando aplicavel.';
COMMENT ON COLUMN pj_profiles.municipal_registration IS 'Inscricao municipal quando aplicavel.';
COMMENT ON COLUMN pj_profiles.tax_regime IS 'Regime tributario usado por fiscal, ERP e conciliacao.';
COMMENT ON COLUMN pj_profiles.cnae_primary IS 'CNAE principal da empresa.';
COMMENT ON COLUMN pj_profiles.cnae_secondary IS 'Lista de CNAEs secundarios para expansao fiscal.';
COMMENT ON COLUMN pj_profiles.legal_representative_name IS 'Nome do responsavel legal da PJ.';
COMMENT ON COLUMN pj_profiles.legal_representative_document IS 'Documento do responsavel legal.';
COMMENT ON COLUMN pj_profiles.billing_email IS 'Email fiscal/financeiro para cobranca e notas.';
COMMENT ON COLUMN pj_profiles.billing_phone IS 'Telefone fiscal/financeiro em E.164.';
COMMENT ON COLUMN pj_profiles.incorporation_date IS 'Data de abertura/incorporacao da empresa.';
COMMENT ON COLUMN pj_profiles.kyb_status IS 'Status de verificacao KYB empresarial.';
COMMENT ON COLUMN pj_profiles.kyb_verified_at IS 'Timestamp de aprovacao KYB.';
COMMENT ON COLUMN pj_profiles.created_at IS 'Data de criacao do perfil PJ.';
COMMENT ON COLUMN pj_profiles.updated_at IS 'Data da ultima atualizacao do perfil PJ.';

COMMENT ON TABLE rider_profiles IS 'Perfil operacional de riders, integrado um-para-um com users.user_id.';
COMMENT ON COLUMN rider_profiles.rider_profile_id IS 'Primary key UUID do perfil rider.';
COMMENT ON COLUMN rider_profiles.user_id IS 'FK para users.user_id; exige user_kind RIDER por trigger.';
COMMENT ON COLUMN rider_profiles.rider_status IS 'Status operacional do rider no app e despacho.';
COMMENT ON COLUMN rider_profiles.mode_preference IS 'Preferencia de modalidade, como bike, moto, carro ou van.';
COMMENT ON COLUMN rider_profiles.vehicle_type IS 'Tipo de veiculo usado em Move/Logistics.';
COMMENT ON COLUMN rider_profiles.vehicle_plate IS 'Placa do veiculo quando aplicavel.';
COMMENT ON COLUMN rider_profiles.vehicle_model IS 'Modelo do veiculo para suporte e compliance.';
COMMENT ON COLUMN rider_profiles.driver_license_number IS 'Numero da habilitacao quando exigida.';
COMMENT ON COLUMN rider_profiles.driver_license_category IS 'Categoria da habilitacao.';
COMMENT ON COLUMN rider_profiles.driver_license_expires_at IS 'Validade da habilitacao.';
COMMENT ON COLUMN rider_profiles.service_zone_code IS 'Zona operacional do rider.';
COMMENT ON COLUMN rider_profiles.availability_status IS 'Disponibilidade atual: offline, online, busy ou paused.';
COMMENT ON COLUMN rider_profiles.background_check_status IS 'Status de background check do rider.';
COMMENT ON COLUMN rider_profiles.insurance_policy_ref IS 'Referencia de seguro ou apolice.';
COMMENT ON COLUMN rider_profiles.performance_score IS 'Score operacional do rider entre 0 e 100.';
COMMENT ON COLUMN rider_profiles.created_at IS 'Data de criacao do perfil rider.';
COMMENT ON COLUMN rider_profiles.updated_at IS 'Data da ultima atualizacao do perfil rider.';

COMMENT ON TABLE wallets IS 'Carteira financeira por usuario, separando BRL e NEX com checks de coerencia.';
COMMENT ON COLUMN wallets.wallet_id IS 'Primary key UUID da wallet.';
COMMENT ON COLUMN wallets.user_id IS 'FK para users.user_id, dono absoluto da wallet.';
COMMENT ON COLUMN wallets.wallet_type IS 'Finalidade da wallet: custodial, escrow, rewards, settlement ou equity.';
COMMENT ON COLUMN wallets.asset_code IS 'Ativo controlado pela wallet: BRL ou NEX.';
COMMENT ON COLUMN wallets.wallet_status IS 'Status operacional da wallet.';
COMMENT ON COLUMN wallets.balance_available_brl IS 'Saldo BRL disponivel para uso.';
COMMENT ON COLUMN wallets.balance_blocked_brl IS 'Saldo BRL bloqueado por risco, disputa ou escrow.';
COMMENT ON COLUMN wallets.balance_pending_brl IS 'Saldo BRL pendente de liquidacao.';
COMMENT ON COLUMN wallets.balance_available_nex IS 'Saldo NEX disponivel com precisao DECIMAL(18,8).';
COMMENT ON COLUMN wallets.balance_blocked_nex IS 'Saldo NEX bloqueado por equity, vesting ou disputa.';
COMMENT ON COLUMN wallets.balance_pending_nex IS 'Saldo NEX pendente de liquidacao.';
COMMENT ON COLUMN wallets.daily_limit_brl IS 'Limite diario BRL para antifraude e compliance.';
COMMENT ON COLUMN wallets.monthly_limit_brl IS 'Limite mensal BRL para antifraude e compliance.';
COMMENT ON COLUMN wallets.ledger_version IS 'Versao de ledger para reconciliacao e controle concorrente.';
COMMENT ON COLUMN wallets.last_reconciled_at IS 'Ultima reconciliacao financeira da wallet.';
COMMENT ON COLUMN wallets.created_at IS 'Data de criacao da wallet.';
COMMENT ON COLUMN wallets.updated_at IS 'Data da ultima atualizacao da wallet.';

COMMENT ON TABLE led_cards IS 'Cartoes fisicos LED/NFC integrados a usuario, wallet e Handshake NFC.';
COMMENT ON COLUMN led_cards.led_card_id IS 'Primary key UUID do LED Card.';
COMMENT ON COLUMN led_cards.user_id IS 'FK para users.user_id, dono do cartao.';
COMMENT ON COLUMN led_cards.wallet_id IS 'FK opcional para wallet vinculada ao cartao.';
COMMENT ON COLUMN led_cards.card_uid IS 'Identificador unico logico do cartao.';
COMMENT ON COLUMN led_cards.nfc_serial IS 'Serial NFC unico lido por dispositivos de handshake.';
COMMENT ON COLUMN led_cards.token_reference IS 'Referencia de tokenizacao segura do cartao.';
COMMENT ON COLUMN led_cards.card_status IS 'Status operacional do cartao.';
COMMENT ON COLUMN led_cards.issued_at IS 'Data de emissao do cartao.';
COMMENT ON COLUMN led_cards.assigned_at IS 'Data de atribuicao ao usuario.';
COMMENT ON COLUMN led_cards.activated_at IS 'Data de ativacao.';
COMMENT ON COLUMN led_cards.blocked_at IS 'Data de bloqueio.';
COMMENT ON COLUMN led_cards.revoked_at IS 'Data de revogacao ou perda.';
COMMENT ON COLUMN led_cards.revocation_reason IS 'Motivo de revogacao, perda ou bloqueio definitivo.';
COMMENT ON COLUMN led_cards.last_handshake_at IS 'Ultimo Handshake NFC registrado.';
COMMENT ON COLUMN led_cards.custody_notes IS 'Notas de custodia fisica do cartao.';
COMMENT ON COLUMN led_cards.created_at IS 'Data de criacao do LED Card.';
COMMENT ON COLUMN led_cards.updated_at IS 'Data da ultima atualizacao do LED Card.';

COMMENT ON TABLE orders IS 'Tabela mestre de pedidos para Food, Move e Dropship, integrada a usuarios, wallets e transactions.';
COMMENT ON COLUMN orders.order_id IS 'Primary key UUID do pedido.';
COMMENT ON COLUMN orders.user_id IS 'FK para users.user_id do cliente principal.';
COMMENT ON COLUMN orders.wallet_id IS 'FK para wallets.wallet_id usada no pagamento do pedido.';
COMMENT ON COLUMN orders.order_domain IS 'Dominio operacional do pedido: Food, Move ou Dropship.';
COMMENT ON COLUMN orders.order_status IS 'Status do lifecycle do pedido.';
COMMENT ON COLUMN orders.merchant_user_id IS 'FK opcional para lojista, parceiro ou seller.';
COMMENT ON COLUMN orders.rider_user_id IS 'FK opcional para rider responsavel por entrega ou corrida.';
COMMENT ON COLUMN orders.affiliate_user_id IS 'FK opcional para afiliado/influencer que originou venda.';
COMMENT ON COLUMN orders.source_channel IS 'Canal de origem do pedido, como APP, WEB, API ou ADMIN.';
COMMENT ON COLUMN orders.currency_code IS 'Moeda principal do pedido em ISO-4217.';
COMMENT ON COLUMN orders.subtotal_brl IS 'Subtotal em BRL antes de taxas, impostos e descontos.';
COMMENT ON COLUMN orders.delivery_fee_brl IS 'Taxa de entrega em BRL.';
COMMENT ON COLUMN orders.service_fee_brl IS 'Taxa de servico da plataforma em BRL.';
COMMENT ON COLUMN orders.discount_brl IS 'Desconto aplicado em BRL.';
COMMENT ON COLUMN orders.tax_brl IS 'Impostos calculados em BRL.';
COMMENT ON COLUMN orders.total_brl IS 'Total final em BRL validado por check.';
COMMENT ON COLUMN orders.total_nex IS 'Total final em NEX quando a wallet do pedido usa token.';
COMMENT ON COLUMN orders.payment_transaction_id IS 'FK para transactions.transaction_id que liquida o pedido.';
COMMENT ON COLUMN orders.pickup_address_json IS 'Endereco de coleta em JSONB para Food, Move ou Logistics.';
COMMENT ON COLUMN orders.dropoff_address_json IS 'Endereco de entrega/destino em JSONB.';
COMMENT ON COLUMN orders.scheduled_for IS 'Agendamento futuro do pedido quando aplicavel.';
COMMENT ON COLUMN orders.confirmed_at IS 'Data de confirmacao operacional.';
COMMENT ON COLUMN orders.dispatched_at IS 'Data de despacho ou inicio de rota.';
COMMENT ON COLUMN orders.delivered_at IS 'Data de entrega ou conclusao fisica.';
COMMENT ON COLUMN orders.cancelled_at IS 'Data de cancelamento.';
COMMENT ON COLUMN orders.cancellation_reason IS 'Motivo de cancelamento para suporte e auditoria.';
COMMENT ON COLUMN orders.customer_notes IS 'Notas visiveis do cliente.';
COMMENT ON COLUMN orders.ops_notes IS 'Notas internas de operacao.';
COMMENT ON COLUMN orders.restaurant_user_id IS 'FK opcional para restaurante no dominio Food.';
COMMENT ON COLUMN orders.kitchen_status IS 'Status de cozinha/preparo no dominio Food.';
COMMENT ON COLUMN orders.prep_started_at IS 'Inicio de preparo no dominio Food.';
COMMENT ON COLUMN orders.route_distance_km IS 'Distancia da rota em km para Move/Logistics.';
COMMENT ON COLUMN orders.route_duration_sec IS 'Duracao estimada da rota em segundos.';
COMMENT ON COLUMN orders.surge_multiplier IS 'Multiplicador dinamico de preco em Move.';
COMMENT ON COLUMN orders.vehicle_category IS 'Categoria de veiculo em Move.';
COMMENT ON COLUMN orders.supplier_name IS 'Fornecedor externo no dominio Dropship.';
COMMENT ON COLUMN orders.supplier_sku IS 'SKU do fornecedor externo.';
COMMENT ON COLUMN orders.tracking_code IS 'Codigo de rastreio externo.';
COMMENT ON COLUMN orders.tracking_provider IS 'Transportadora ou provedor de tracking.';
COMMENT ON COLUMN orders.customs_status IS 'Status alfandegario quando houver importacao.';
COMMENT ON COLUMN orders.created_at IS 'Data de criacao do pedido.';
COMMENT ON COLUMN orders.updated_at IS 'Data da ultima atualizacao do pedido.';

COMMENT ON TABLE transactions IS 'Ledger financeiro append-only para pagamentos, P2P, compras, splits, refunds, fees e escrow.';
COMMENT ON COLUMN transactions.transaction_id IS 'Primary key UUID da transacao.';
COMMENT ON COLUMN transactions.user_id IS 'FK para users.user_id do dono do lancamento.';
COMMENT ON COLUMN transactions.wallet_id IS 'FK para wallet debitada, creditada ou movimentada.';
COMMENT ON COLUMN transactions.counterparty_user_id IS 'FK opcional para contraparte da transacao.';
COMMENT ON COLUMN transactions.counterparty_wallet_id IS 'FK opcional para wallet da contraparte.';
COMMENT ON COLUMN transactions.transaction_type IS 'Tipo do lancamento financeiro.';
COMMENT ON COLUMN transactions.transaction_status IS 'Status de autorizacao, liquidacao, falha ou reversao.';
COMMENT ON COLUMN transactions.order_id IS 'FK opcional para orders.order_id quando transacao nasce de pedido.';
COMMENT ON COLUMN transactions.asset_code IS 'Ativo financeiro da transacao: BRL ou NEX.';
COMMENT ON COLUMN transactions.amount_brl IS 'Valor principal em BRL.';
COMMENT ON COLUMN transactions.amount_nex IS 'Valor principal em NEX.';
COMMENT ON COLUMN transactions.fee_amount_brl IS 'Taxa financeira em BRL.';
COMMENT ON COLUMN transactions.platform_amount_brl IS 'Parte da plataforma em split BRL.';
COMMENT ON COLUMN transactions.merchant_amount_brl IS 'Parte do merchant em split BRL.';
COMMENT ON COLUMN transactions.affiliate_amount_brl IS 'Parte do afiliado/influencer em split BRL.';
COMMENT ON COLUMN transactions.escrow_amount_brl IS 'Valor retido em escrow BRL.';
COMMENT ON COLUMN transactions.fx_rate IS 'Taxa de conversao usada quando existir cambio ou precificacao tokenizada.';
COMMENT ON COLUMN transactions.reference_code IS 'Referencia interna unica do ledger.';
COMMENT ON COLUMN transactions.external_reference IS 'Referencia externa de PSP, gateway ou parceiro.';
COMMENT ON COLUMN transactions.channel IS 'Canal tecnico de origem.';
COMMENT ON COLUMN transactions.origin_module IS 'Modulo Valley que originou a transacao.';
COMMENT ON COLUMN transactions.description IS 'Descricao operacional da transacao.';
COMMENT ON COLUMN transactions.metadata_json IS 'Metadados tecnicos em JSONB para integracoes.';
COMMENT ON COLUMN transactions.authorized_at IS 'Data de autorizacao.';
COMMENT ON COLUMN transactions.settled_at IS 'Data de liquidacao.';
COMMENT ON COLUMN transactions.failed_at IS 'Data de falha.';
COMMENT ON COLUMN transactions.created_at IS 'Data de criacao imutavel do lancamento.';

COMMENT ON TABLE equity_ledger IS 'Ledger append-only de Smart Equity para controle de supply, certificados, vesting e clausulas.';
COMMENT ON COLUMN equity_ledger.equity_entry_id IS 'Primary key UUID do evento de equity.';
COMMENT ON COLUMN equity_ledger.user_id IS 'FK para users.user_id do titular do evento.';
COMMENT ON COLUMN equity_ledger.wallet_id IS 'FK para wallet NEX do tipo EQUITY.';
COMMENT ON COLUMN equity_ledger.equity_event_type IS 'Tipo de evento societario ou tokenizado.';
COMMENT ON COLUMN equity_ledger.token_amount_nex IS 'Quantidade de tokens NEX do evento com DECIMAL(18,8).';
COMMENT ON COLUMN equity_ledger.unit_reference_brl IS 'Valor de referencia unitario em BRL quando aplicavel.';
COMMENT ON COLUMN equity_ledger.certificate_hash IS 'Hash do certificado ou documento societario.';
COMMENT ON COLUMN equity_ledger.certificate_uri IS 'URI segura do certificado ou anexo externo.';
COMMENT ON COLUMN equity_ledger.vesting_start_at IS 'Inicio do periodo de vesting.';
COMMENT ON COLUMN equity_ledger.vesting_end_at IS 'Fim do periodo de vesting.';
COMMENT ON COLUMN equity_ledger.lock_until IS 'Data ate quando os tokens ficam bloqueados.';
COMMENT ON COLUMN equity_ledger.drag_along_clause IS 'Flag da clausula Drag-Along.';
COMMENT ON COLUMN equity_ledger.tag_along_clause IS 'Flag da clausula Tag-Along.';
COMMENT ON COLUMN equity_ledger.board_approval_ref IS 'Referencia de aprovacao societaria ou board approval.';
COMMENT ON COLUMN equity_ledger.authorized_by_user_id IS 'FK para usuario/admin que autorizou o evento.';
COMMENT ON COLUMN equity_ledger.source_transaction_id IS 'FK opcional para transacao financeira relacionada.';
COMMENT ON COLUMN equity_ledger.notes IS 'Notas de auditoria societaria.';
COMMENT ON COLUMN equity_ledger.created_at IS 'Data de criacao imutavel do evento de equity.';

COMMENT ON FUNCTION set_updated_at() IS 'Trigger function que atualiza updated_at automaticamente em tabelas mutaveis.';
COMMENT ON FUNCTION assert_profile_user_kind() IS 'Trigger function que impede perfil PJ ou Rider em usuario de tipo incorreto.';
COMMENT ON FUNCTION assert_led_card_wallet_owner() IS 'Trigger function que garante que LED Card e wallet pertencam ao mesmo usuario.';
COMMENT ON FUNCTION assert_default_led_card_owner() IS 'Trigger function que garante que o LED Card padrao pertence ao usuario.';
COMMENT ON FUNCTION prevent_append_only_mutation() IS 'Trigger function que bloqueia UPDATE e DELETE em ledgers append-only.';
COMMENT ON FUNCTION assert_order_wallet_owner() IS 'Trigger function que garante que pedido e wallet pertencam ao mesmo usuario e ativo.';
COMMENT ON FUNCTION assert_transaction_wallets() IS 'Trigger function que valida dono e ativo das wallets em transacoes.';
COMMENT ON FUNCTION assert_equity_ledger_entry() IS 'Trigger function que valida wallet EQUITY/NEX e cap de supply de 1M NEX.';

COMMENT ON TRIGGER trg_users_set_updated_at ON users IS 'Atualiza users.updated_at antes de updates.';
COMMENT ON TRIGGER trg_pj_profiles_set_updated_at ON pj_profiles IS 'Atualiza pj_profiles.updated_at antes de updates.';
COMMENT ON TRIGGER trg_rider_profiles_set_updated_at ON rider_profiles IS 'Atualiza rider_profiles.updated_at antes de updates.';
COMMENT ON TRIGGER trg_wallets_set_updated_at ON wallets IS 'Atualiza wallets.updated_at antes de updates.';
COMMENT ON TRIGGER trg_led_cards_set_updated_at ON led_cards IS 'Atualiza led_cards.updated_at antes de updates.';
COMMENT ON TRIGGER trg_pj_profiles_assert_user_kind ON pj_profiles IS 'Bloqueia perfil PJ para usuario que nao seja user_kind PJ.';
COMMENT ON TRIGGER trg_rider_profiles_assert_user_kind ON rider_profiles IS 'Bloqueia perfil rider para usuario que nao seja user_kind RIDER.';
COMMENT ON TRIGGER trg_led_cards_assert_wallet_owner ON led_cards IS 'Bloqueia vinculo de LED Card a wallet de outro usuario.';
COMMENT ON TRIGGER trg_users_assert_default_led_card_owner ON users IS 'Bloqueia LED Card padrao que nao pertence ao usuario.';
COMMENT ON TRIGGER trg_orders_set_updated_at ON orders IS 'Atualiza orders.updated_at antes de updates.';
COMMENT ON TRIGGER trg_orders_assert_wallet_owner ON orders IS 'Bloqueia pedido com wallet de outro usuario ou ativo incoerente.';
COMMENT ON TRIGGER trg_transactions_prevent_update ON transactions IS 'Impede UPDATE no ledger financeiro append-only.';
COMMENT ON TRIGGER trg_transactions_prevent_delete ON transactions IS 'Impede DELETE no ledger financeiro append-only.';
COMMENT ON TRIGGER trg_transactions_assert_wallets ON transactions IS 'Valida dono e ativo das wallets antes de inserir transacao.';
COMMENT ON TRIGGER trg_equity_ledger_prevent_update ON equity_ledger IS 'Impede UPDATE no ledger de equity append-only.';
COMMENT ON TRIGGER trg_equity_ledger_prevent_delete ON equity_ledger IS 'Impede DELETE no ledger de equity append-only.';
COMMENT ON TRIGGER trg_equity_ledger_assert_entry ON equity_ledger IS 'Valida evento de equity, wallet NEX/EQUITY e supply cap.';

COMMIT;
