-- Valley Hybrid DB Patch - Blueprints detalhados dos 47 modulos.
-- Este arquivo e gerado por scripts/valley_module_automation.py.
-- Ele evolui module_delivery_registry sem recriar a tabela existente.

BEGIN;

SET search_path = public;

ALTER TABLE module_delivery_registry
    ADD COLUMN IF NOT EXISTS module_blueprint_json JSONB NOT NULL DEFAULT '{}'::JSONB;

WITH blueprint_source (module_code, current_phase, module_blueprint_json) AS (
VALUES
    ('REPLY', 'VALIDATE', '{"admin_surfaces":["painel de compras","cadastro de fornecedores","fila de faturamento"],"compliance_tags":["financial_audit","tax_traceability","supplier_approval"],"current_phase":"VALIDATE","event_topics":["reply.procurement_order.created","reply.service_work_order.closed","reply.billing_cycle.closed"],"key_capabilities":["compras e sourcing","ordens de servico","faturamento operacional"],"mongo_collections":[],"next_deliverables":["fechar fluxo fiscal ponta a ponta","amarrar aprovacao por unidade","instrumentar SLA de compras"],"postgres_entities":["suppliers","procurement_orders","service_work_orders","inventory_items"],"primary_actors":["operador interno","comprador","gestor empresarial"]}'::JSONB),
('STOCK', 'VALIDATE', '{"admin_surfaces":["painel de catalogo","monitor de margem","painel de tracking"],"compliance_tags":["pricing_traceability","supplier_settlement","catalog_governance"],"current_phase":"VALIDATE","event_topics":["stock.catalog.synced","stock.margin.repriced","stock.tracking.updated"],"key_capabilities":["dropshipping centralizado","margem dinamica","tracking de fornecedor"],"mongo_collections":[],"next_deliverables":["definir politica de margem por canal","fechar conciliacao com fornecedor","amarrar excecao de ruptura"],"postgres_entities":["marketplace_listings","procurement_orders","inventory_lots"],"primary_actors":["analista de catalogo","operador de estoque","fornecedor parceiro"]}'::JSONB),
('LOG', 'VALIDATE', '{"admin_surfaces":["painel de tracking","fila de excecoes","monitor de transportadoras"],"compliance_tags":["chain_of_custody","tracking_traceability","carrier_audit"],"current_phase":"VALIDATE","event_topics":["log.tracking_event.ingested","log.route.anomaly.detected","log.delivery.status_changed"],"key_capabilities":["tracking unificado","checkpoints canonicos","alerta de anomalia"],"mongo_collections":["log_tracking_events"],"next_deliverables":["normalizar status canonicos","ligar alertas de atraso","fechar dedupe por evento"],"postgres_entities":[],"primary_actors":["operador logistico","cliente final","transportadora"]}'::JSONB),
('FOOD', 'DATA_CONTRACT', '{"admin_surfaces":["painel de pedidos","gestao de cardapio","monitor de cozinha"],"compliance_tags":["food_safety_traceability","payment_split_audit","allergen_notice"],"current_phase":"DATA_CONTRACT","event_topics":["food.order.placed","food.order.prepared","food.order.delivered"],"key_capabilities":["pedido alimentar","split operacional","restricoes nutricionais"],"mongo_collections":[],"next_deliverables":["criar contrato especifico de cardapio e loja","definir SLA de preparo","amarrar taxonomia nutricional"],"postgres_entities":["orders","transactions","health_profiles"],"primary_actors":["restaurante","consumidor","operador de atendimento"]}'::JSONB),
('DELIVERY', 'VALIDATE', '{"admin_surfaces":["torre de despacho","fila de ocorrencias","painel de courier"],"compliance_tags":["chain_of_custody","proof_of_delivery","driver_accountability"],"current_phase":"VALIDATE","event_topics":["delivery.shipment.created","delivery.route.dispatched","delivery.proof_recorded"],"key_capabilities":["coleta urbana","roteamento operacional","prova de entrega"],"mongo_collections":["delivery_dispatch_runs","telemetry_logs"],"next_deliverables":["fechar reatribuicao automatica","definir KPI de janela prometida","ligar prova de entrega por media"],"postgres_entities":["delivery_shipments","delivery_shipment_events","orders"],"primary_actors":["dispatcher","courier","loja emissora"]}'::JSONB),
('WMS', 'VALIDATE', '{"admin_surfaces":["painel de armazem","monitor de variancia","console de sensores"],"compliance_tags":["inventory_audit","cold_chain_monitoring","warehouse_traceability"],"current_phase":"VALIDATE","event_topics":["wms.cycle_count.started","wms.inventory.variance_detected","wms.sensor.threshold_breached"],"key_capabilities":["enderecamento de estoque","contagem ciclica","sensoriamento de armazem"],"mongo_collections":["warehouse_sensor_snapshots","iot_sensor_events"],"next_deliverables":["fechar mapa de enderecamento","amarrar ajuste de variancia","ligar alarmes por temperatura"],"postgres_entities":["warehouses","inventory_items","warehouse_cycle_counts","inventory_movements"],"primary_actors":["coordenador de armazem","separador","auditor operacional"]}'::JSONB),
('MARKETPLACE', 'VALIDATE', '{"admin_surfaces":["painel de seller","aprovacao de listing","monitor de conversao"],"compliance_tags":["merchant_kyb","pricing_audit","listing_governance"],"current_phase":"VALIDATE","event_topics":["marketplace.listing.published","marketplace.cart.checked_out","marketplace.sale.validated"],"key_capabilities":["listagem local","storefront por merchant","validacao de venda"],"mongo_collections":[],"next_deliverables":["fechar politica de seller score","definir moderacao de catalogo","amarrar regras anti-fraude de checkout"],"postgres_entities":["marketplace_listings","merchant_storefronts","sale_validation_events"],"primary_actors":["seller","comprador","curador comercial"]}'::JSONB),
('PAY', 'VALIDATE', '{"admin_surfaces":["painel financeiro","monitor de conciliacao","fila de limites e bloqueios"],"compliance_tags":["kyc","aml_monitoring","financial_ledger_immutability"],"current_phase":"VALIDATE","event_topics":["pay.wallet.opened","pay.transaction.posted","pay.settlement.reconciled"],"key_capabilities":["wallet e saldo","ledger atomico","splits e conciliacao"],"mongo_collections":[],"next_deliverables":["fechar matriz de limites","amarrar regras de chargeback","instrumentar reconciliacao D0 e D1"],"postgres_entities":["wallets","transactions","equity_ledger","pepita_ledger"],"primary_actors":["titular da wallet","operador financeiro","motor de conciliacao"]}'::JSONB),
('FLEET', 'VALIDATE', '{"admin_surfaces":["painel de frota","calendario de manutencao","monitor de telemetria"],"compliance_tags":["driver_accountability","maintenance_traceability","vehicle_compliance"],"current_phase":"VALIDATE","event_topics":["fleet.vehicle.registered","fleet.maintenance.logged","fleet.telemetry.alerted"],"key_capabilities":["perfil de veiculo","telemetria de uso","manutencao preventiva"],"mongo_collections":["fleet_vehicle_profiles","fleet_maintenance_events","telemetry_logs"],"next_deliverables":["fechar score de saude do veiculo","definir corte por manutencao critica","ligar custo por km"],"postgres_entities":["mobility_trips"],"primary_actors":["gestor de frota","motorista","tecnico de manutencao"]}'::JSONB),
('SERVICES', 'VALIDATE', '{"admin_surfaces":["painel de prestadores","agenda de bookings","fila de reputacao"],"compliance_tags":["provider_verification","service_auditability","payment_split_audit"],"current_phase":"VALIDATE","event_topics":["services.provider.approved","services.booking.confirmed","services.booking.closed"],"key_capabilities":["catalogo de servicos","booking","trilha de atendimento"],"mongo_collections":[],"next_deliverables":["fechar score de prestador","definir no-show policy","ligar disputa operacional"],"postgres_entities":["service_provider_profiles","service_catalog_services","service_bookings","service_booking_events"],"primary_actors":["prestador","cliente","operador de marketplace"]}'::JSONB),
('DIGITAL', 'VALIDATE', '{"admin_surfaces":["painel de colecoes","fila de mint","monitor de royalties"],"compliance_tags":["ownership_traceability","royalty_audit","custody_controls"],"current_phase":"VALIDATE","event_topics":["digital.asset.minted","digital.asset.transferred","digital.royalty.calculated"],"key_capabilities":["colecoes digitais","mint e transferencia","trilha de royalties"],"mongo_collections":[],"next_deliverables":["fechar politica de metadata","amarrar elegibilidade de mint","ligar trilha de royalty por creator"],"postgres_entities":["digital_asset_collections","digital_assets","digital_asset_events"],"primary_actors":["criador","colecionador","operador de custodia"]}'::JSONB),
('REAL_ESTATE', 'VALIDATE', '{"admin_surfaces":["painel de propriedades","fila de due diligence","monitor de deals"],"compliance_tags":["property_traceability","contract_audit","investor_suitability"],"current_phase":"VALIDATE","event_topics":["real_estate.property.registered","real_estate.listing.published","real_estate.deal.executed"],"key_capabilities":["cadastro de imovel","listagem e proposta","deal tokenizado"],"mongo_collections":[],"next_deliverables":["fechar onboarding documental","definir escrow de proposta","amarrar tokenizacao por fracao"],"postgres_entities":["real_estate_properties","real_estate_listings","real_estate_deals"],"primary_actors":["corretor","investidor","operador juridico"]}'::JSONB),
('HEALTH', 'VALIDATE', '{"admin_surfaces":["painel clinico","fila de consentimento","monitor de risco assistencial"],"compliance_tags":["lgpd_sensitive_data","clinical_audit","consent_management"],"current_phase":"VALIDATE","event_topics":["health.profile.updated","health.care_plan.activated","health.prescription.issued"],"key_capabilities":["perfil clinico","plano de cuidado","prescricao segura"],"mongo_collections":["ai_memory","telemetry_logs"],"next_deliverables":["amarrar consentimento granular","definir trilha de acesso clinico","ligar sinais de risco preditivo"],"postgres_entities":["health_profiles","health_care_plans","health_prescriptions"],"primary_actors":["paciente","profissional de saude","operador clinico"]}'::JSONB),
('EDU', 'VALIDATE', '{"admin_surfaces":["painel academico","catalogo de trilhas","monitor de progresso"],"compliance_tags":["certificate_traceability","learning_reward_audit","content_governance"],"current_phase":"VALIDATE","event_topics":["edu.path.published","edu.enrollment.started","edu.unit.completed"],"key_capabilities":["trilhas de aprendizado","unidades educacionais","enrollment e progresso"],"mongo_collections":[],"next_deliverables":["fechar emissao de certificado","ligar rewards por conclusao","definir versionamento de conteudo"],"postgres_entities":["edu_learning_paths","edu_learning_units","edu_enrollments"],"primary_actors":["aluno","instrutor","operador academico"]}'::JSONB),
('TECH', 'VALIDATE', '{"admin_surfaces":["painel de integracoes","gestao de credenciais","monitor de webhooks"],"compliance_tags":["secret_hashing","api_audit","integration_traceability"],"current_phase":"VALIDATE","event_topics":["tech.client.provisioned","tech.webhook.delivered","tech.connector.synced"],"key_capabilities":["api clients","credenciais seguras","webhooks e conectores"],"mongo_collections":[],"next_deliverables":["fechar rotate de credenciais","ligar replay seguro de webhook","definir limites por client"],"postgres_entities":["tech_api_clients","tech_api_credentials","tech_webhook_subscriptions","tech_webhook_delivery_attempts"],"primary_actors":["developer","integrador","operador de plataforma"]}'::JSONB),
('JOBS', 'VALIDATE', '{"admin_surfaces":["painel de vagas","fila de matching","monitor de funil"],"compliance_tags":["candidate_privacy","matching_auditability","anti_bias_review"],"current_phase":"VALIDATE","event_topics":["jobs.posting.opened","jobs.application.submitted","jobs.match.scored"],"key_capabilities":["vagas","aplicacoes","engagement com IA"],"mongo_collections":["ai_memory"],"next_deliverables":["fechar score explicavel","definir sinais de aderencia","ligar consentimento para recomendacao"],"postgres_entities":["job_postings","job_applications","job_engagements"],"primary_actors":["candidato","recrutador","operador de matching"]}'::JSONB),
('NEWS_PODCAST', 'VALIDATE', '{"admin_surfaces":["cms editorial","fila de revisao","monitor de distribuicao"],"compliance_tags":["editorial_governance","copyright_traceability","content_moderation"],"current_phase":"VALIDATE","event_topics":["news.story.published","podcast.episode.released","media.content.moderated"],"key_capabilities":["conteudo editorial","episodios e blocos","distribuicao midia"],"mongo_collections":["news_content_items"],"next_deliverables":["fechar taxonomia editorial","ligar agenda de publicacao","amarrar politica de moderacao"],"postgres_entities":[],"primary_actors":["editor","criador de audio","consumidor"]}'::JSONB),
('ADS', 'VALIDATE', '{"admin_surfaces":["painel de campanhas","monitor de atribuicao","console de crescimento"],"compliance_tags":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"current_phase":"VALIDATE","event_topics":["ads.campaign.launched","ads.impression.attributed","ads.reward.booked"],"key_capabilities":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"mongo_collections":["social_videos","influencer_metrics"],"next_deliverables":["fechar janela de atribuicao","definir cap de frequencia","ligar score de criativo"],"postgres_entities":["gold_campaigns","sale_validation_events","pepita_accounts"],"primary_actors":["anunciante","operador de growth","merchant"]}'::JSONB),
('INFLUENCERS', 'BUILD', '{"admin_surfaces":["painel de creators","fila de brand safety","monitor de afiliacao"],"compliance_tags":["creator_disclosure","commission_audit","brand_safety"],"current_phase":"BUILD","event_topics":["influencer.profile.qualified","influencer.metric.ingested","influencer.commission.attributed"],"key_capabilities":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"mongo_collections":["influencer_metrics","social_videos"],"next_deliverables":["fechar score de creator fit","definir politica de disclosure","ligar payout por campanha"],"postgres_entities":["creator_uploads"],"primary_actors":["creator","brand manager","operador de afiliacao"]}'::JSONB),
('SOCIAL', 'BUILD', '{"admin_surfaces":["painel de moderacao","fila de denuncias","monitor de reputacao"],"compliance_tags":["content_moderation","community_safety","privacy_controls"],"current_phase":"BUILD","event_topics":["social.post.published","social.report.opened","social.reputation.updated"],"key_capabilities":["feed de bairro","reputacao social","moderacao contextual"],"mongo_collections":["social_videos","ai_memory"],"next_deliverables":["fechar score de reputacao","ligar anti-spam por bairro","definir politica de retencao"],"postgres_entities":[],"primary_actors":["morador","moderador","comerciante local"]}'::JSONB),
('FITNESS', 'VALIDATE', '{"admin_surfaces":["painel wellness","monitor de metas","fila de recompensa"],"compliance_tags":["health_consent","activity_reward_audit","wearable_data_traceability"],"current_phase":"VALIDATE","event_topics":["fitness.session.logged","fitness.goal.hit","fitness.reward.qualified"],"key_capabilities":["sessao de atividade","move-to-earn","integracao com saude"],"mongo_collections":["fitness_activity_sessions"],"next_deliverables":["fechar score de consistencia","definir fraude de atividade","ligar rewards por meta semanal"],"postgres_entities":["health_profiles"],"primary_actors":["usuario ativo","coach","operador wellness"]}'::JSONB),
('PHARMACY', 'VALIDATE', '{"admin_surfaces":["painel farmaceutico","fila de prescricao","monitor de dispensacao"],"compliance_tags":["prescription_compliance","dispense_audit","controlled_medication_traceability"],"current_phase":"VALIDATE","event_topics":["pharmacy.order.received","pharmacy.item.dispensed","pharmacy.delivery.released"],"key_capabilities":["catalogo farmaceutico","fulfillment","dispensacao auditavel"],"mongo_collections":[],"next_deliverables":["fechar checagem de receita","definir corte por medicamento controlado","ligar SLA de separacao"],"postgres_entities":["pharmacy_catalog_items","pharmacy_fulfillments","pharmacy_fulfillment_items","pharmacy_dispense_events"],"primary_actors":["farmaceutico","paciente","operador de fulfilment"]}'::JSONB),
('VET', 'VALIDATE', '{"admin_surfaces":["painel pet","fila de casos","monitor de prescricoes"],"compliance_tags":["clinical_pet_traceability","controlled_medication_audit","owner_consent"],"current_phase":"VALIDATE","event_topics":["vet.pet.registered","vet.case.opened","vet.prescription.issued"],"key_capabilities":["perfil pet","caso clinico","prescricao veterinaria"],"mongo_collections":[],"next_deliverables":["fechar historico vacinal","definir agenda de retorno","ligar integracao com farmacia"],"postgres_entities":["vet_pet_profiles","vet_service_cases","vet_prescriptions"],"primary_actors":["tutor","veterinario","operador pet"]}'::JSONB),
('TOURISM', 'VALIDATE', '{"admin_surfaces":["painel de experiencias","fila de bookings","monitor de check-in"],"compliance_tags":["booking_audit","guide_accountability","settlement_traceability"],"current_phase":"VALIDATE","event_topics":["tourism.experience.published","tourism.booking.confirmed","tourism.checkin.recorded"],"key_capabilities":["experiencias locais","booking","feed exploratorio"],"mongo_collections":["tourism_experience_feeds","space_anchor_maps"],"next_deliverables":["fechar politica de cancelamento","definir no-show do guia","ligar reputacao por experiencia"],"postgres_entities":["tourism_experiences","tourism_bookings","tourism_booking_events"],"primary_actors":["turista","guia","operador local"]}'::JSONB),
('EVENTS', 'VALIDATE', '{"admin_surfaces":["painel de eventos","monitor de bilheteria","fila de dispute"],"compliance_tags":["ticket_immutability","escrow_audit","fraud_prevention"],"current_phase":"VALIDATE","event_topics":["events.program.published","events.ticket.issued","events.ticket.transferred"],"key_capabilities":["programacao de evento","tipos de ingresso","ledger de tickets"],"mongo_collections":[],"next_deliverables":["fechar anti-scalping","definir transferencia segura","ligar concilicao de evento"],"postgres_entities":["event_programs","event_ticket_types","event_ticket_ledger"],"primary_actors":["organizador","participante","operador de bilheteria"]}'::JSONB),
('MOBILITY', 'VALIDATE', '{"admin_surfaces":["torre de corridas","monitor de checkpoints","painel de rider"],"compliance_tags":["ride_audit","driver_accountability","fare_traceability"],"current_phase":"VALIDATE","event_topics":["mobility.trip.requested","mobility.trip.started","mobility.trip.completed"],"key_capabilities":["corrida urbana","checkpoint operacional","precificacao de rota"],"mongo_collections":["fleet_vehicle_profiles","telemetry_logs"],"next_deliverables":["fechar calculo de tarifa","definir score de seguranca da corrida","ligar suporte em tempo real"],"postgres_entities":["mobility_trips","mobility_trip_events","orders"],"primary_actors":["passageiro","rider","dispatcher"]}'::JSONB),
('SECURITY', 'VALIDATE', '{"admin_surfaces":["torre de seguranca","fila de incidentes","painel de credenciais"],"compliance_tags":["biometric_hashing","incident_chain_of_custody","access_control"],"current_phase":"VALIDATE","event_topics":["security.sos.triggered","security.biometric.enrolled","security.incident.closed"],"key_capabilities":["contatos confiaveis","credencial biometrica por hash","trilha de incidente"],"mongo_collections":["security_signal_logs","iot_sensor_events"],"next_deliverables":["fechar severidade de incidente","definir resposta por playbook","ligar trilha forense"],"postgres_entities":["security_trusted_contacts","security_biometric_credentials","security_incidents","security_incident_events"],"primary_actors":["usuario protegido","analista de risco","operador SOS"]}'::JSONB),
('GOV', 'VALIDATE', '{"admin_surfaces":["portal de requests","fila de atendimento","monitor de SLA publico"],"compliance_tags":["public_auditability","citizen_identity","service_traceability"],"current_phase":"VALIDATE","event_topics":["gov.service.requested","gov.request.routed","gov.request.resolved"],"key_capabilities":["catalogo de servicos","requests publicos","eventos de atendimento"],"mongo_collections":[],"next_deliverables":["fechar taxonomia de servico publico","definir SLA por categoria","ligar trilha documental"],"postgres_entities":["gov_service_catalog","gov_service_requests","gov_request_events"],"primary_actors":["cidadao","servidor","operador govtech"]}'::JSONB),
('LEGAL', 'VALIDATE', '{"admin_surfaces":["painel juridico","fila de assinaturas","monitor de disputas"],"compliance_tags":["legal_audit","signature_traceability","fallback_pin_hashing"],"current_phase":"VALIDATE","event_topics":["legal.contract.created","legal.signature.recorded","legal.dispute.opened"],"key_capabilities":["contratos","assinaturas","disputas e trilha juridica"],"mongo_collections":[],"next_deliverables":["fechar clausulas parametrizadas","definir mediacao assistida por IA","ligar prova documental do contrato"],"postgres_entities":["legal_contracts","legal_contract_parties","legal_signatures","legal_disputes","legal_audit_events","legal_fallback_pin_credentials"],"primary_actors":["juridico","assinante","mediador"]}'::JSONB),
('CHARITY', 'VALIDATE', '{"admin_surfaces":["painel de causas","fila de grants","monitor de ledger social"],"compliance_tags":["donation_audit","impact_traceability","fund_immutability"],"current_phase":"VALIDATE","event_topics":["charity.cause.published","charity.grant.approved","charity.fund.posted"],"key_capabilities":["causas","grants","ledger de fundos"],"mongo_collections":[],"next_deliverables":["fechar prova de impacto","definir governanca de grants","ligar recibo social auditavel"],"postgres_entities":["charity_causes","charity_grants","charity_fund_ledger"],"primary_actors":["doador","gestor de causa","auditor social"]}'::JSONB),
('INSURANCE', 'VALIDATE', '{"admin_surfaces":["painel de apolices","fila de claim","monitor de underwriting"],"compliance_tags":["policy_audit","claim_traceability","risk_underwriting"],"current_phase":"VALIDATE","event_topics":["insurance.policy.issued","insurance.claim.opened","insurance.claim.settled"],"key_capabilities":["produtos e apolices","claims","eventos de claim"],"mongo_collections":[],"next_deliverables":["fechar score de risco","definir anti-fraude de claim","ligar payout auditavel"],"postgres_entities":["insurance_products","insurance_policies","insurance_claims","insurance_claim_events"],"primary_actors":["segurado","underwriter","analista de sinistro"]}'::JSONB),
('GAMING', 'VALIDATE', '{"admin_surfaces":["painel de quests","monitor de rewards","console de comunidade"],"compliance_tags":["reward_audit","age_safety","community_moderation"],"current_phase":"VALIDATE","event_topics":["gaming.player.progressed","gaming.reward.unlocked","gaming.quest.completed"],"key_capabilities":["estado do jogador","gamificacao","ponte com rewards"],"mongo_collections":["gaming_player_states","social_videos"],"next_deliverables":["fechar regra de quest","definir anti-abuso de reward","ligar ranking por bairro"],"postgres_entities":["points_ledger"],"primary_actors":["player","community manager","operador de reward"]}'::JSONB),
('IOT', 'VALIDATE', '{"admin_surfaces":["painel de devices","fila de provisioning","monitor de sensores"],"compliance_tags":["device_traceability","telemetry_retention","access_control"],"current_phase":"VALIDATE","event_topics":["iot.device.provisioned","iot.sensor.event_ingested","iot.device.offline_detected"],"key_capabilities":["registry de device","eventos de sensor","hub conectado"],"mongo_collections":["iot_device_registry","iot_sensor_events","telemetry_logs"],"next_deliverables":["fechar inventario de device","definir heartbeat canonico","ligar playbook de device offline"],"postgres_entities":[],"primary_actors":["operador de dispositivos","tecnico de campo","motor de automacao"]}'::JSONB),
('BIO', 'VALIDATE', '{"admin_surfaces":["painel ambiental","fila de coleta","monitor de impacto"],"compliance_tags":["reverse_logistics_traceability","impact_audit","chain_of_custody"],"current_phase":"VALIDATE","event_topics":["bio.program.opened","bio.collection.scheduled","bio.impact.measured"],"key_capabilities":["programas de material","ordem de coleta reversa","log de impacto"],"mongo_collections":["bio_impact_logs","iot_sensor_events"],"next_deliverables":["fechar score de impacto por material","definir prova de coleta","ligar conciliacao com parceiro ambiental"],"postgres_entities":["bio_material_programs","bio_collection_orders","bio_collection_events"],"primary_actors":["operador de coleta","parceiro ambiental","auditor de impacto"]}'::JSONB),
('HOME', 'VALIDATE', '{"admin_surfaces":["painel de residencia","console de automacao","monitor de alertas"],"compliance_tags":["household_access_control","event_retention","device_safety"],"current_phase":"VALIDATE","event_topics":["home.device.bound","home.scene.executed","home.alert.triggered"],"key_capabilities":["automacao residencial","eventos domesticos","regras de cena"],"mongo_collections":["home_automation_events","iot_device_registry"],"next_deliverables":["fechar modelo de household","definir automacao segura","ligar trilha de acesso domestico"],"postgres_entities":[],"primary_actors":["morador","instalador","operador smart home"]}'::JSONB),
('ENERGY', 'VALIDATE', '{"admin_surfaces":["painel de ativos","monitor de trades","console de settlement"],"compliance_tags":["meter_traceability","financial_settlement_immutability","grid_compliance"],"current_phase":"VALIDATE","event_topics":["energy.asset.registered","energy.trade.matched","energy.settlement.posted"],"key_capabilities":["ativos de energia","trade P2P","settlement auditavel"],"mongo_collections":["energy_meter_streams","iot_sensor_events"],"next_deliverables":["fechar matching de energia","definir janela de settlement","ligar conciliacao com medidor"],"postgres_entities":["energy_assets","energy_trade_orders","energy_settlement_ledger"],"primary_actors":["prosumidor","operador de grid","analista de settlement"]}'::JSONB),
('SPACE', 'VALIDATE', '{"admin_surfaces":["painel AR","monitor de ancoras","fila de curadoria espacial"],"compliance_tags":["location_privacy","content_safety","creator_traceability"],"current_phase":"VALIDATE","event_topics":["space.anchor.created","space.anchor.visited","space.layer.published"],"key_capabilities":["ancoras espaciais","camadas AR","experiencias geolocalizadas"],"mongo_collections":["space_anchor_maps","social_videos"],"next_deliverables":["fechar taxonomia de ancora","definir moderacao espacial","ligar analytics de visita"],"postgres_entities":[],"primary_actors":["explorador","criador AR","operador de mapa"]}'::JSONB),
('AGENDA', 'VALIDATE', '{"admin_surfaces":["painel de agenda","fila de lembretes","console de memoria"],"compliance_tags":["personal_data_retention","consent_management","assistant_audit"],"current_phase":"VALIDATE","event_topics":["agenda.item.created","agenda.reminder.triggered","agenda.memory.linked"],"key_capabilities":["agenda inteligente","listas","memoria operacional"],"mongo_collections":["agenda_items","ai_memory"],"next_deliverables":["fechar recorrencia canonica","definir hierarquia de listas","ligar memoria de contexto"],"postgres_entities":[],"primary_actors":["usuario final","Helena","operador de produtividade"]}'::JSONB),
('ADVISOR', 'BUILD', '{"admin_surfaces":["painel consultivo","fila de aprovacoes","monitor de recomendacoes"],"compliance_tags":["consent_management","ai_auditability","cross_module_traceability"],"current_phase":"BUILD","event_topics":["advisor.insight.generated","advisor.action.proposed","advisor.consent.recorded"],"key_capabilities":["insights","recomendacao com consentimento","orquestracao entre modulos"],"mongo_collections":["ai_memory","agenda_items"],"next_deliverables":["fechar registro de consentimento","definir escopo de acao por modulo","ligar explainability do insight"],"postgres_entities":["advisor_insights","financial_goals"],"primary_actors":["usuario assistido","motor de IA","operador consultivo"]}'::JSONB),
('FINANCAS', 'VALIDATE', '{"admin_surfaces":["painel financeiro pessoal","monitor de metas","fila de conciliacao"],"compliance_tags":["financial_privacy","goal_audit","ledger_traceability"],"current_phase":"VALIDATE","event_topics":["financas.goal.created","financas.roundup.booked","financas.cashflow.closed"],"key_capabilities":["metas financeiras","round-up","visao de caixa"],"mongo_collections":[],"next_deliverables":["fechar agregacao por categoria","definir orcamento mensal","ligar alertas de caixa"],"postgres_entities":["financial_goals","transactions","wallets"],"primary_actors":["usuario PF","microempreendedor","operador financeiro"]}'::JSONB),
('MENTE', 'VALIDATE', '{"admin_surfaces":["painel terapeutico","fila de sessoes","monitor de follow-up"],"compliance_tags":["lgpd_sensitive_data","therapy_confidentiality","clinical_access_audit"],"current_phase":"VALIDATE","event_topics":["mente.session.scheduled","mente.session.completed","mente.followup.created"],"key_capabilities":["teleterapia","notas seguras","sinais de acompanhamento"],"mongo_collections":[],"next_deliverables":["fechar trilha de nota cifrada","definir protocolo de risco","ligar agenda terapeutica"],"postgres_entities":["teletherapy_sessions","health_profiles"],"primary_actors":["paciente","terapeuta","operador de cuidado"]}'::JSONB),
('BUSINESS', 'DATA_CONTRACT', '{"admin_surfaces":["painel empresarial","monitor de rotina","fila de documentos"],"compliance_tags":["tax_traceability","rbac_controls","financial_audit"],"current_phase":"DATA_CONTRACT","event_topics":["business.company.onboarded","business.statement.closed","business.routine.executed"],"key_capabilities":["erp integrado","visao operacional","ponte com fiscal e folha"],"mongo_collections":[],"next_deliverables":["criar contrato especifico de empresa e unidade","definir visao fiscal consolidada","ligar fluxo de folha e invoices"],"postgres_entities":["module_catalog","procurement_orders","merchant_storefronts"],"primary_actors":["dono do negocio","contador","operador backoffice"]}'::JSONB),
('PLUG', 'DATA_CONTRACT', '{"admin_surfaces":["painel de adquirencia","monitor de terminais","fila de antecipacao"],"compliance_tags":["pci_boundary","mdr_audit","settlement_traceability"],"current_phase":"DATA_CONTRACT","event_topics":["plug.device.activated","plug.payment.authorized","plug.advance.requested"],"key_capabilities":["tap-to-pay","maquininha","antecipacao de recebivel"],"mongo_collections":[],"next_deliverables":["criar contrato especifico de terminal","definir MDR por faixa","ligar fluxo D0 de antecipacao"],"postgres_entities":["transactions","wallets","merchant_storefronts"],"primary_actors":["lojista","operador de adquirencia","comprador presencial"]}'::JSONB),
('UP', 'DATA_CONTRACT', '{"admin_surfaces":["painel de afiliados","monitor de conversao","fila de comissao"],"compliance_tags":["attribution_audit","commission_traceability","anti_fraud"],"current_phase":"DATA_CONTRACT","event_topics":["up.link.generated","up.conversion.attributed","up.commission.booked"],"key_capabilities":["indicacao","link de atribuicao","comissao"],"mongo_collections":["influencer_metrics","social_videos"],"next_deliverables":["criar contrato especifico de atribuicao","definir janela de comissao","ligar fraude por auto-indicacao"],"postgres_entities":["transactions","pepita_ledger"],"primary_actors":["afiliado","merchant","operador de atribuicao"]}'::JSONB),
('MEDIA', 'BUILD', '{"admin_surfaces":["studio de creator","fila de publicacao","monitor de receita"],"compliance_tags":["copyright_traceability","creator_payout_audit","brand_safety"],"current_phase":"BUILD","event_topics":["media.upload.received","media.asset.published","media.revenue.booked"],"key_capabilities":["upload de creator","monetizacao","distribuicao de conteudo"],"mongo_collections":["social_videos","news_content_items"],"next_deliverables":["fechar pipeline de media","definir direitos por asset","ligar receita por creator"],"postgres_entities":["creator_uploads","transactions"],"primary_actors":["criador","operador de midia","marca"]}'::JSONB),
('CHAT', 'VALIDATE', '{"admin_surfaces":["painel de conversas","monitor de contexto","fila de retencao"],"compliance_tags":["message_retention_policy","helena_context_separation","consent_audit"],"current_phase":"VALIDATE","event_topics":["chat.conversation.opened","chat.message.persisted","chat.context.promoted"],"key_capabilities":["conversa Helena dual","retencao segura","ponte com agenda e advisor"],"mongo_collections":["ai_memory","agenda_items"],"next_deliverables":["fechar politica de retention","definir separacao pessoal x profissional","ligar contexto com advisor"],"postgres_entities":["chat_conversations","users"],"primary_actors":["usuario pessoal","usuario profissional","motor de assistencia"]}'::JSONB),
('DOCS', 'DATA_CONTRACT', '{"admin_surfaces":["painel documental","fila de emissao","monitor de checksum"],"compliance_tags":["document_immutability","signature_traceability","receipt_audit"],"current_phase":"DATA_CONTRACT","event_topics":["docs.receipt.generated","docs.document.signed","docs.hash.registered"],"key_capabilities":["documentos","recibos","checksums e prova"],"mongo_collections":[],"next_deliverables":["criar contrato especifico de template","definir trilha de checksum","ligar versionamento de recibo"],"postgres_entities":["legal_contracts","transactions","orders","event_ticket_ledger"],"primary_actors":["operador documental","juridico","motor de recibos"]}'::JSONB)
)
UPDATE module_delivery_registry AS target
SET
    current_phase = blueprint_source.current_phase::module_delivery_phase_enum,
    module_blueprint_json = blueprint_source.module_blueprint_json,
    updated_at = NOW()
FROM blueprint_source
WHERE target.module_code = blueprint_source.module_code;

COMMENT ON COLUMN module_delivery_registry.module_blueprint_json IS 'Blueprint canonico do modulo com atores, entidades, eventos, compliance e backlog imediato.';

COMMIT;
