#!/usr/bin/env python3
"""Materialize Codex Cloud setup secrets into local runtime files.

Codex Cloud secrets are available during the setup script phase. This script is
designed to run in that phase and persist the configured values into ignored
runtime files needed by the Valley automation.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_EXAMPLE_PATH = ROOT / ".env.example"
ENV_PATH = ROOT / ".env"
RUNTIME_DIR = ROOT / "tmp" / "runtime"
STATUS_PATH = RUNTIME_DIR / "codex-cloud-materialize-status.json"

EXTRA_KEYS = (
    "ALIEXPRESS_SELLER_ID",
    "ALIBABA_SELLER_ID",
    "MAGALU_ACCESS_TOKEN",
    "MAGALU_CLIENT_ID",
    "MAGALU_CLIENT_SECRET",
    "MAGALU_REFRESH_TOKEN",
    "MAGALU_SELLER_ID",
    "MERCADOLIVRE_ACCESS_TOKEN",
    "MERCADOLIVRE_CLIENT_ID",
    "MERCADOLIVRE_CLIENT_SECRET",
    "MERCADOLIVRE_REFRESH_TOKEN",
    "MERCADOLIVRE_SELLER_ID",
)


def utc_now_iso() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def parse_env_example_keys() -> list[str]:
    keys: list[str] = []
    if not ENV_EXAMPLE_PATH.exists():
        return keys
    for raw_line in ENV_EXAMPLE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key = line.split("=", 1)[0].strip()
        if key and key not in keys:
            keys.append(key)
    for key in EXTRA_KEYS:
        if key not in keys:
            keys.append(key)
    return keys


def render_env_value(value: str) -> str:
    if "\n" in value or "\r" in value:
        value = value.replace("\r", "\\r").replace("\n", "\\n")
    if value and any(char.isspace() for char in value):
        return f'"{value.replace(chr(34), "\\\"")}"'
    return value


def materialize_env_file() -> dict[str, int]:
    keys = parse_env_example_keys()
    lines = [
        "# Generated by scripts/materialize_codex_cloud_env.py during Codex Cloud setup.",
        "# Do not commit this file.",
        "",
    ]
    written = 0
    missing = 0
    for key in keys:
        value = str(os.environ.get(key) or "").strip()
        if value:
            written += 1
        else:
            missing += 1
        lines.append(f"{key}={render_env_value(value)}")

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"keys_total": len(keys), "keys_written": written, "keys_missing": missing}


def run_repair() -> dict[str, object]:
    repair_script = ROOT / "scripts" / "repair_dropshipping_integrations.py"
    if not repair_script.exists():
        return {"status": "missing", "script": str(repair_script.relative_to(ROOT))}
    result = subprocess.run(
        [sys.executable, str(repair_script)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
        timeout=180,
    )
    payload: object = {}
    stdout = (result.stdout or "").strip()
    if stdout:
        try:
            payload = json.loads(stdout)
        except json.JSONDecodeError:
            payload = {"stdout_lines": len(stdout.splitlines())}
    return {
        "status": "ok" if result.returncode == 0 else "failed",
        "returncode": result.returncode,
        "payload": payload,
        "stderr_lines": len((result.stderr or "").splitlines()),
    }


def main() -> None:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    env_status = materialize_env_file()
    repair_status = run_repair()
    status = {
        "status": "ok" if repair_status.get("status") in {"ok", "missing"} else "failed",
        "generated_at_utc": utc_now_iso(),
        "env": env_status,
        "repair": repair_status,
        "secret_values_printed": False,
    }
    STATUS_PATH.write_text(json.dumps(status, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(status, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
