apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valley.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "valley.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "valley.fullname" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "valley.fullname" . }}-config
            - secretRef:
                name: {{ include "valley.fullname" . }}-secrets
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
