apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: valley-app
  namespace: valley
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: valley.example.com
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: valley.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: valley-app
                port:
                  number: 80
  tls:
    - hosts:
        - valley.example.com
      secretName: valley-tls
