BEGIN;

-- Seed operacional idempotente dos pacotes fisicos por dominio prioritario.
-- Gerado automaticamente por scripts/valley_module_automation.py.

WITH package_source (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
) AS (
    VALUES
    ('logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'Logistics ERP Operations', 1, 'priority_domains_v1', ARRAY['BUSINESS', 'REPLY', 'STOCK', 'LOG', 'FOOD', 'WMS', 'DELIVERY', 'FLEET']::TEXT[], ARRAY['BUSINESS.exec.01', 'BUSINESS.exec.02', 'REPLY.exec.01', 'REPLY.exec.02', 'STOCK.exec.01', 'STOCK.exec.02', 'LOG.exec.01', 'LOG.exec.02', 'FOOD.exec.01', 'FOOD.exec.02', 'WMS.exec.01', 'WMS.exec.02', 'BUSINESS.exec.03', 'REPLY.exec.03', 'STOCK.exec.03', 'LOG.exec.03', 'FOOD.exec.03', 'DELIVERY.exec.01', 'DELIVERY.exec.02', 'WMS.exec.03', 'FLEET.exec.01', 'FLEET.exec.02', 'DELIVERY.exec.03', 'FLEET.exec.03']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"artifacts":[{"artifact_key":"logistics_erp_operations.ddl.v1","artifact_path":"database/domain-delivery/priority-domains/logistics_erp_operations/ddl_complement.sql","layer_type":"DDL_COMPLEMENT","target_engine":"postgres"},{"artifact_key":"logistics_erp_operations.seed.v1","artifact_path":"database/domain-delivery/priority-domains/logistics_erp_operations/operational_seed.sql","layer_type":"OPERATIONS_SEED","target_engine":"postgres"},{"artifact_key":"logistics_erp_operations.contract.v1","artifact_path":"contracts/events/priority-domains/logistics_erp_operations.json","layer_type":"EVENT_CONTRACT","target_engine":"filesystem"}],"backlog_keys":["BUSINESS.exec.01","BUSINESS.exec.02","REPLY.exec.01","REPLY.exec.02","STOCK.exec.01","STOCK.exec.02","LOG.exec.01","LOG.exec.02","FOOD.exec.01","FOOD.exec.02","WMS.exec.01","WMS.exec.02","BUSINESS.exec.03","REPLY.exec.03","STOCK.exec.03","LOG.exec.03","FOOD.exec.03","DELIVERY.exec.01","DELIVERY.exec.02","WMS.exec.03","FLEET.exec.01","FLEET.exec.02","DELIVERY.exec.03","FLEET.exec.03"],"domain_key":"logistics_erp_operations","domain_label":"Logistics ERP Operations","event_topics":["business.company.onboarded","business.statement.closed","business.routine.executed","reply.procurement_order.created","reply.service_work_order.closed","reply.billing_cycle.closed","stock.catalog.synced","stock.margin.repriced","stock.tracking.updated","log.tracking_event.ingested","log.route.anomaly.detected","log.delivery.status_changed","food.order.placed","food.order.prepared","food.order.delivered","wms.cycle_count.started","wms.inventory.variance_detected","wms.sensor.threshold_breached","delivery.shipment.created","delivery.route.dispatched","delivery.proof_recorded","fleet.vehicle.registered","fleet.maintenance.logged","fleet.telemetry.alerted"],"modules":["BUSINESS","REPLY","STOCK","LOG","FOOD","WMS","DELIVERY","FLEET"],"package_key":"logistics_erp_operations.priority.v1","priority_rank":1}'::JSONB)
)
INSERT INTO domain_delivery_packages (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
)
SELECT
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
FROM package_source
ON CONFLICT (package_key) DO UPDATE SET
    domain_key = EXCLUDED.domain_key,
    domain_label = EXCLUDED.domain_label,
    priority_rank = EXCLUDED.priority_rank,
    package_scope = EXCLUDED.package_scope,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    package_status = EXCLUDED.package_status,
    artifact_manifest_json = EXCLUDED.artifact_manifest_json,
    updated_at = NOW();

WITH artifact_source (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
) AS (
    VALUES
    ('logistics_erp_operations.ddl.v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'DDL_COMPLEMENT'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/logistics_erp_operations/ddl_complement.sql', ARRAY['BUSINESS', 'REPLY', 'STOCK', 'LOG', 'FOOD', 'WMS', 'DELIVERY', 'FLEET']::TEXT[], ARRAY['BUSINESS.exec.01', 'BUSINESS.exec.02', 'REPLY.exec.01', 'REPLY.exec.02', 'STOCK.exec.01', 'STOCK.exec.02', 'LOG.exec.01', 'LOG.exec.02', 'FOOD.exec.01', 'FOOD.exec.02', 'WMS.exec.01', 'WMS.exec.02', 'BUSINESS.exec.03', 'REPLY.exec.03', 'STOCK.exec.03', 'LOG.exec.03', 'FOOD.exec.03', 'DELIVERY.exec.01', 'DELIVERY.exec.02', 'WMS.exec.03', 'FLEET.exec.01', 'FLEET.exec.02', 'DELIVERY.exec.03', 'FLEET.exec.03']::TEXT[], ARRAY[]::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"package_key":"logistics_erp_operations.priority.v1","priority_rank":1,"views":["v_logistics_erp_operations_priority_backlog","v_logistics_erp_operations_delivery_artifacts","v_logistics_erp_operations_event_contracts"]}'::JSONB),
    ('logistics_erp_operations.seed.v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'OPERATIONS_SEED'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/logistics_erp_operations/operational_seed.sql', ARRAY['BUSINESS', 'REPLY', 'STOCK', 'LOG', 'FOOD', 'WMS', 'DELIVERY', 'FLEET']::TEXT[], ARRAY['BUSINESS.exec.01', 'BUSINESS.exec.02', 'REPLY.exec.01', 'REPLY.exec.02', 'STOCK.exec.01', 'STOCK.exec.02', 'LOG.exec.01', 'LOG.exec.02', 'FOOD.exec.01', 'FOOD.exec.02', 'WMS.exec.01', 'WMS.exec.02', 'BUSINESS.exec.03', 'REPLY.exec.03', 'STOCK.exec.03', 'LOG.exec.03', 'FOOD.exec.03', 'DELIVERY.exec.01', 'DELIVERY.exec.02', 'WMS.exec.03', 'FLEET.exec.01', 'FLEET.exec.02', 'DELIVERY.exec.03', 'FLEET.exec.03']::TEXT[], ARRAY['logistics_erp_operations.ddl.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"contract_count":24,"package_key":"logistics_erp_operations.priority.v1","seed_scope":"priority_domain_delivery_v1"}'::JSONB),
    ('logistics_erp_operations.contract.v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'EVENT_CONTRACT'::domain_delivery_layer_enum, 'filesystem', 'contracts/events/priority-domains/logistics_erp_operations.json', ARRAY['BUSINESS', 'REPLY', 'STOCK', 'LOG', 'FOOD', 'WMS', 'DELIVERY', 'FLEET']::TEXT[], ARRAY['BUSINESS.exec.01', 'BUSINESS.exec.02', 'REPLY.exec.01', 'REPLY.exec.02', 'STOCK.exec.01', 'STOCK.exec.02', 'LOG.exec.01', 'LOG.exec.02', 'FOOD.exec.01', 'FOOD.exec.02', 'WMS.exec.01', 'WMS.exec.02', 'BUSINESS.exec.03', 'REPLY.exec.03', 'STOCK.exec.03', 'LOG.exec.03', 'FOOD.exec.03', 'DELIVERY.exec.01', 'DELIVERY.exec.02', 'WMS.exec.03', 'FLEET.exec.01', 'FLEET.exec.02', 'DELIVERY.exec.03', 'FLEET.exec.03']::TEXT[], ARRAY['logistics_erp_operations.ddl.v1', 'logistics_erp_operations.seed.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"event_topics":["business.company.onboarded","business.statement.closed","business.routine.executed","reply.procurement_order.created","reply.service_work_order.closed","reply.billing_cycle.closed","stock.catalog.synced","stock.margin.repriced","stock.tracking.updated","log.tracking_event.ingested","log.route.anomaly.detected","log.delivery.status_changed","food.order.placed","food.order.prepared","food.order.delivered","wms.cycle_count.started","wms.inventory.variance_detected","wms.sensor.threshold_breached","delivery.shipment.created","delivery.route.dispatched","delivery.proof_recorded","fleet.vehicle.registered","fleet.maintenance.logged","fleet.telemetry.alerted"],"package_key":"logistics_erp_operations.priority.v1"}'::JSONB)
)
INSERT INTO domain_delivery_artifacts (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
)
SELECT
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
FROM artifact_source
ON CONFLICT (artifact_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    layer_type = EXCLUDED.layer_type,
    target_engine = EXCLUDED.target_engine,
    artifact_path = EXCLUDED.artifact_path,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    depends_on_keys = EXCLUDED.depends_on_keys,
    artifact_status = EXCLUDED.artifact_status,
    artifact_payload_json = EXCLUDED.artifact_payload_json,
    updated_at = NOW();

WITH contract_source (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
) AS (
    VALUES
    ('BUSINESS:business.company.onboarded:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'BUSINESS', 'business.company.onboarded', '1.0.0', 'painel empresarial', ARRAY['INVOICES', 'PAYROLLS', 'painel empresarial', 'monitor de rotina']::TEXT[], ARRAY['module_catalog', 'procurement_orders', 'merchant_storefronts']::TEXT[], ARRAY['tax_traceability', 'rbac_controls', 'financial_audit']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["tax_traceability","rbac_controls","financial_audit"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"business.company.onboarded"},"evidence_refs":{"items":{"enum":["module_catalog","procurement_orders","merchant_storefronts"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"BUSINESS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["erp integrado","visao operacional","ponte com fiscal e folha"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["dono do negocio","contador","operador backoffice"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"BUSINESS::business.company.onboarded","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('BUSINESS:business.statement.closed:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'BUSINESS', 'business.statement.closed', '1.0.0', 'painel empresarial', ARRAY['INVOICES', 'PAYROLLS', 'painel empresarial', 'monitor de rotina']::TEXT[], ARRAY['module_catalog', 'procurement_orders', 'merchant_storefronts']::TEXT[], ARRAY['tax_traceability', 'rbac_controls', 'financial_audit']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["tax_traceability","rbac_controls","financial_audit"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"business.statement.closed"},"evidence_refs":{"items":{"enum":["module_catalog","procurement_orders","merchant_storefronts"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"BUSINESS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["erp integrado","visao operacional","ponte com fiscal e folha"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["dono do negocio","contador","operador backoffice"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"BUSINESS::business.statement.closed","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('BUSINESS:business.routine.executed:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'BUSINESS', 'business.routine.executed', '1.0.0', 'painel empresarial', ARRAY['INVOICES', 'PAYROLLS', 'painel empresarial', 'monitor de rotina']::TEXT[], ARRAY['module_catalog', 'procurement_orders', 'merchant_storefronts']::TEXT[], ARRAY['tax_traceability', 'rbac_controls', 'financial_audit']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["tax_traceability","rbac_controls","financial_audit"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"business.routine.executed"},"evidence_refs":{"items":{"enum":["module_catalog","procurement_orders","merchant_storefronts"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"BUSINESS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["erp integrado","visao operacional","ponte com fiscal e folha"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["dono do negocio","contador","operador backoffice"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"BUSINESS::business.routine.executed","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('REPLY:reply.procurement_order.created:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'REPLY', 'reply.procurement_order.created', '1.0.0', 'painel de compras', ARRAY['STOCK', 'MARKETPLACE', 'WMS', 'painel de compras', 'cadastro de fornecedores']::TEXT[], ARRAY['suppliers', 'procurement_orders', 'service_work_orders']::TEXT[], ARRAY['financial_audit', 'tax_traceability', 'supplier_approval']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["financial_audit","tax_traceability","supplier_approval"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"reply.procurement_order.created"},"evidence_refs":{"items":{"enum":["suppliers","procurement_orders","service_work_orders"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"REPLY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["compras e sourcing","ordens de servico","faturamento operacional"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["operador interno","comprador","gestor empresarial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"REPLY::reply.procurement_order.created","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('REPLY:reply.service_work_order.closed:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'REPLY', 'reply.service_work_order.closed', '1.0.0', 'painel de compras', ARRAY['STOCK', 'MARKETPLACE', 'WMS', 'painel de compras', 'cadastro de fornecedores']::TEXT[], ARRAY['suppliers', 'procurement_orders', 'service_work_orders']::TEXT[], ARRAY['financial_audit', 'tax_traceability', 'supplier_approval']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["financial_audit","tax_traceability","supplier_approval"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"reply.service_work_order.closed"},"evidence_refs":{"items":{"enum":["suppliers","procurement_orders","service_work_orders"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"REPLY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["compras e sourcing","ordens de servico","faturamento operacional"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["operador interno","comprador","gestor empresarial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"REPLY::reply.service_work_order.closed","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('REPLY:reply.billing_cycle.closed:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'REPLY', 'reply.billing_cycle.closed', '1.0.0', 'painel de compras', ARRAY['STOCK', 'MARKETPLACE', 'WMS', 'painel de compras', 'cadastro de fornecedores']::TEXT[], ARRAY['suppliers', 'procurement_orders', 'service_work_orders']::TEXT[], ARRAY['financial_audit', 'tax_traceability', 'supplier_approval']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["financial_audit","tax_traceability","supplier_approval"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"reply.billing_cycle.closed"},"evidence_refs":{"items":{"enum":["suppliers","procurement_orders","service_work_orders"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"REPLY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["compras e sourcing","ordens de servico","faturamento operacional"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["operador interno","comprador","gestor empresarial"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"REPLY::reply.billing_cycle.closed","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('STOCK:stock.catalog.synced:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'STOCK', 'stock.catalog.synced', '1.0.0', 'painel de catalogo', ARRAY['LOG', 'UP', 'DOCS', 'painel de catalogo', 'monitor de margem']::TEXT[], ARRAY['marketplace_listings', 'procurement_orders', 'inventory_lots']::TEXT[], ARRAY['pricing_traceability', 'supplier_settlement', 'catalog_governance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["pricing_traceability","supplier_settlement","catalog_governance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"stock.catalog.synced"},"evidence_refs":{"items":{"enum":["marketplace_listings","procurement_orders","inventory_lots"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"STOCK"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["dropshipping centralizado","margem dinamica","tracking de fornecedor"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["analista de catalogo","operador de estoque","fornecedor parceiro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"STOCK::stock.catalog.synced","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('STOCK:stock.margin.repriced:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'STOCK', 'stock.margin.repriced', '1.0.0', 'painel de catalogo', ARRAY['LOG', 'UP', 'DOCS', 'painel de catalogo', 'monitor de margem']::TEXT[], ARRAY['marketplace_listings', 'procurement_orders', 'inventory_lots']::TEXT[], ARRAY['pricing_traceability', 'supplier_settlement', 'catalog_governance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["pricing_traceability","supplier_settlement","catalog_governance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"stock.margin.repriced"},"evidence_refs":{"items":{"enum":["marketplace_listings","procurement_orders","inventory_lots"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"STOCK"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["dropshipping centralizado","margem dinamica","tracking de fornecedor"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["analista de catalogo","operador de estoque","fornecedor parceiro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"STOCK::stock.margin.repriced","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('STOCK:stock.tracking.updated:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'STOCK', 'stock.tracking.updated', '1.0.0', 'painel de catalogo', ARRAY['LOG', 'UP', 'DOCS', 'painel de catalogo', 'monitor de margem']::TEXT[], ARRAY['marketplace_listings', 'procurement_orders', 'inventory_lots']::TEXT[], ARRAY['pricing_traceability', 'supplier_settlement', 'catalog_governance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["pricing_traceability","supplier_settlement","catalog_governance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"stock.tracking.updated"},"evidence_refs":{"items":{"enum":["marketplace_listings","procurement_orders","inventory_lots"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"STOCK"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["dropshipping centralizado","margem dinamica","tracking de fornecedor"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["analista de catalogo","operador de estoque","fornecedor parceiro"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"STOCK::stock.tracking.updated","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('LOG:log.tracking_event.ingested:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'LOG', 'log.tracking_event.ingested', '1.0.0', 'painel de tracking', ARRAY['DELIVERY', 'FOOD', 'MOBILITY', 'painel de tracking', 'fila de excecoes']::TEXT[], ARRAY['log_tracking_events']::TEXT[], ARRAY['chain_of_custody', 'tracking_traceability', 'carrier_audit']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["chain_of_custody","tracking_traceability","carrier_audit"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"log.tracking_event.ingested"},"evidence_refs":{"items":{"enum":["log_tracking_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LOG"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["tracking unificado","checkpoints canonicos","alerta de anomalia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["operador logistico","cliente final","transportadora"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LOG::log.tracking_event.ingested","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('LOG:log.route.anomaly.detected:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'LOG', 'log.route.anomaly.detected', '1.0.0', 'painel de tracking', ARRAY['DELIVERY', 'FOOD', 'MOBILITY', 'painel de tracking', 'fila de excecoes']::TEXT[], ARRAY['log_tracking_events']::TEXT[], ARRAY['chain_of_custody', 'tracking_traceability', 'carrier_audit']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["chain_of_custody","tracking_traceability","carrier_audit"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"log.route.anomaly.detected"},"evidence_refs":{"items":{"enum":["log_tracking_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LOG"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["tracking unificado","checkpoints canonicos","alerta de anomalia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["operador logistico","cliente final","transportadora"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LOG::log.route.anomaly.detected","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('LOG:log.delivery.status_changed:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'LOG', 'log.delivery.status_changed', '1.0.0', 'painel de tracking', ARRAY['DELIVERY', 'FOOD', 'MOBILITY', 'painel de tracking', 'fila de excecoes']::TEXT[], ARRAY['log_tracking_events']::TEXT[], ARRAY['chain_of_custody', 'tracking_traceability', 'carrier_audit']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["chain_of_custody","tracking_traceability","carrier_audit"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"log.delivery.status_changed"},"evidence_refs":{"items":{"enum":["log_tracking_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"LOG"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["tracking unificado","checkpoints canonicos","alerta de anomalia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["operador logistico","cliente final","transportadora"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"LOG::log.delivery.status_changed","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('FOOD:food.order.placed:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'FOOD', 'food.order.placed', '1.0.0', 'painel de pedidos', ARRAY['ORDERS', 'MOBILITY', 'DOCS', 'painel de pedidos', 'gestao de cardapio']::TEXT[], ARRAY['orders', 'transactions', 'health_profiles']::TEXT[], ARRAY['food_safety_traceability', 'payment_split_audit', 'allergen_notice']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["food_safety_traceability","payment_split_audit","allergen_notice"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"food.order.placed"},"evidence_refs":{"items":{"enum":["orders","transactions","health_profiles"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FOOD"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["pedido alimentar","split operacional","restricoes nutricionais"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["restaurante","consumidor","operador de atendimento"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FOOD::food.order.placed","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('FOOD:food.order.prepared:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'FOOD', 'food.order.prepared', '1.0.0', 'painel de pedidos', ARRAY['ORDERS', 'MOBILITY', 'DOCS', 'painel de pedidos', 'gestao de cardapio']::TEXT[], ARRAY['orders', 'transactions', 'health_profiles']::TEXT[], ARRAY['food_safety_traceability', 'payment_split_audit', 'allergen_notice']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["food_safety_traceability","payment_split_audit","allergen_notice"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"food.order.prepared"},"evidence_refs":{"items":{"enum":["orders","transactions","health_profiles"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FOOD"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["pedido alimentar","split operacional","restricoes nutricionais"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["restaurante","consumidor","operador de atendimento"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FOOD::food.order.prepared","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('FOOD:food.order.delivered:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'FOOD', 'food.order.delivered', '1.0.0', 'painel de pedidos', ARRAY['ORDERS', 'MOBILITY', 'DOCS', 'painel de pedidos', 'gestao de cardapio']::TEXT[], ARRAY['orders', 'transactions', 'health_profiles']::TEXT[], ARRAY['food_safety_traceability', 'payment_split_audit', 'allergen_notice']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["food_safety_traceability","payment_split_audit","allergen_notice"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"DATA_CONTRACT"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"food.order.delivered"},"evidence_refs":{"items":{"enum":["orders","transactions","health_profiles"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FOOD"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["pedido alimentar","split operacional","restricoes nutricionais"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["restaurante","consumidor","operador de atendimento"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FOOD::food.order.delivered","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('WMS:wms.cycle_count.started:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'WMS', 'wms.cycle_count.started', '1.0.0', 'painel de armazem', ARRAY['STOCK', 'IOT', 'BUSINESS', 'painel de armazem', 'monitor de variancia']::TEXT[], ARRAY['warehouses', 'inventory_items', 'warehouse_cycle_counts', 'warehouse_sensor_snapshots', 'iot_sensor_events']::TEXT[], ARRAY['inventory_audit', 'cold_chain_monitoring', 'warehouse_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["inventory_audit","cold_chain_monitoring","warehouse_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"wms.cycle_count.started"},"evidence_refs":{"items":{"enum":["warehouses","inventory_items","warehouse_cycle_counts","warehouse_sensor_snapshots","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"WMS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["enderecamento de estoque","contagem ciclica","sensoriamento de armazem"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["coordenador de armazem","separador","auditor operacional"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"WMS::wms.cycle_count.started","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('WMS:wms.inventory.variance_detected:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'WMS', 'wms.inventory.variance_detected', '1.0.0', 'painel de armazem', ARRAY['STOCK', 'IOT', 'BUSINESS', 'painel de armazem', 'monitor de variancia']::TEXT[], ARRAY['warehouses', 'inventory_items', 'warehouse_cycle_counts', 'warehouse_sensor_snapshots', 'iot_sensor_events']::TEXT[], ARRAY['inventory_audit', 'cold_chain_monitoring', 'warehouse_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["inventory_audit","cold_chain_monitoring","warehouse_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"wms.inventory.variance_detected"},"evidence_refs":{"items":{"enum":["warehouses","inventory_items","warehouse_cycle_counts","warehouse_sensor_snapshots","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"WMS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["enderecamento de estoque","contagem ciclica","sensoriamento de armazem"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["coordenador de armazem","separador","auditor operacional"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"WMS::wms.inventory.variance_detected","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('WMS:wms.sensor.threshold_breached:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'WMS', 'wms.sensor.threshold_breached', '1.0.0', 'painel de armazem', ARRAY['STOCK', 'IOT', 'BUSINESS', 'painel de armazem', 'monitor de variancia']::TEXT[], ARRAY['warehouses', 'inventory_items', 'warehouse_cycle_counts', 'warehouse_sensor_snapshots', 'iot_sensor_events']::TEXT[], ARRAY['inventory_audit', 'cold_chain_monitoring', 'warehouse_traceability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["inventory_audit","cold_chain_monitoring","warehouse_traceability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"wms.sensor.threshold_breached"},"evidence_refs":{"items":{"enum":["warehouses","inventory_items","warehouse_cycle_counts","warehouse_sensor_snapshots","iot_sensor_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"WMS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["enderecamento de estoque","contagem ciclica","sensoriamento de armazem"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["coordenador de armazem","separador","auditor operacional"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"WMS::wms.sensor.threshold_breached","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('DELIVERY:delivery.shipment.created:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'DELIVERY', 'delivery.shipment.created', '1.0.0', 'torre de despacho', ARRAY['FOOD', 'MARKETPLACE', 'MOBILITY', 'torre de despacho', 'fila de ocorrencias']::TEXT[], ARRAY['delivery_shipments', 'delivery_shipment_events', 'orders', 'delivery_dispatch_runs', 'telemetry_logs']::TEXT[], ARRAY['chain_of_custody', 'proof_of_delivery', 'driver_accountability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["chain_of_custody","proof_of_delivery","driver_accountability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"delivery.shipment.created"},"evidence_refs":{"items":{"enum":["delivery_shipments","delivery_shipment_events","orders","delivery_dispatch_runs","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"DELIVERY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["coleta urbana","roteamento operacional","prova de entrega"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["dispatcher","courier","loja emissora"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"DELIVERY::delivery.shipment.created","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('DELIVERY:delivery.route.dispatched:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'DELIVERY', 'delivery.route.dispatched', '1.0.0', 'torre de despacho', ARRAY['FOOD', 'MARKETPLACE', 'MOBILITY', 'torre de despacho', 'fila de ocorrencias']::TEXT[], ARRAY['delivery_shipments', 'delivery_shipment_events', 'orders', 'delivery_dispatch_runs', 'telemetry_logs']::TEXT[], ARRAY['chain_of_custody', 'proof_of_delivery', 'driver_accountability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["chain_of_custody","proof_of_delivery","driver_accountability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"delivery.route.dispatched"},"evidence_refs":{"items":{"enum":["delivery_shipments","delivery_shipment_events","orders","delivery_dispatch_runs","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"DELIVERY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["coleta urbana","roteamento operacional","prova de entrega"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["dispatcher","courier","loja emissora"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"DELIVERY::delivery.route.dispatched","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('DELIVERY:delivery.proof_recorded:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'DELIVERY', 'delivery.proof_recorded', '1.0.0', 'torre de despacho', ARRAY['FOOD', 'MARKETPLACE', 'MOBILITY', 'torre de despacho', 'fila de ocorrencias']::TEXT[], ARRAY['delivery_shipments', 'delivery_shipment_events', 'orders', 'delivery_dispatch_runs', 'telemetry_logs']::TEXT[], ARRAY['chain_of_custody', 'proof_of_delivery', 'driver_accountability']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["chain_of_custody","proof_of_delivery","driver_accountability"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"delivery.proof_recorded"},"evidence_refs":{"items":{"enum":["delivery_shipments","delivery_shipment_events","orders","delivery_dispatch_runs","telemetry_logs"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"DELIVERY"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["coleta urbana","roteamento operacional","prova de entrega"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["dispatcher","courier","loja emissora"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"DELIVERY::delivery.proof_recorded","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('FLEET:fleet.vehicle.registered:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'FLEET', 'fleet.vehicle.registered', '1.0.0', 'painel de frota', ARRAY['LOG', 'SECURITY', 'painel de frota', 'calendario de manutencao']::TEXT[], ARRAY['mobility_trips', 'fleet_vehicle_profiles', 'fleet_maintenance_events']::TEXT[], ARRAY['driver_accountability', 'maintenance_traceability', 'vehicle_compliance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["driver_accountability","maintenance_traceability","vehicle_compliance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"fleet.vehicle.registered"},"evidence_refs":{"items":{"enum":["mobility_trips","fleet_vehicle_profiles","fleet_maintenance_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FLEET"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["perfil de veiculo","telemetria de uso","manutencao preventiva"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["gestor de frota","motorista","tecnico de manutencao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FLEET::fleet.vehicle.registered","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('FLEET:fleet.maintenance.logged:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'FLEET', 'fleet.maintenance.logged', '1.0.0', 'painel de frota', ARRAY['LOG', 'SECURITY', 'painel de frota', 'calendario de manutencao']::TEXT[], ARRAY['mobility_trips', 'fleet_vehicle_profiles', 'fleet_maintenance_events']::TEXT[], ARRAY['driver_accountability', 'maintenance_traceability', 'vehicle_compliance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["driver_accountability","maintenance_traceability","vehicle_compliance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"fleet.maintenance.logged"},"evidence_refs":{"items":{"enum":["mobility_trips","fleet_vehicle_profiles","fleet_maintenance_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FLEET"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["perfil de veiculo","telemetria de uso","manutencao preventiva"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["gestor de frota","motorista","tecnico de manutencao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FLEET::fleet.maintenance.logged","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json'),
    ('FLEET:fleet.telemetry.alerted:v1', 'logistics_erp_operations.priority.v1', 'logistics_erp_operations', 'FLEET', 'fleet.telemetry.alerted', '1.0.0', 'painel de frota', ARRAY['LOG', 'SECURITY', 'painel de frota', 'calendario de manutencao']::TEXT[], ARRAY['mobility_trips', 'fleet_vehicle_profiles', 'fleet_maintenance_events']::TEXT[], ARRAY['driver_accountability', 'maintenance_traceability', 'vehicle_compliance']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["driver_accountability","maintenance_traceability","vehicle_compliance"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"logistics_erp_operations"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"fleet.telemetry.alerted"},"evidence_refs":{"items":{"enum":["mobility_trips","fleet_vehicle_profiles","fleet_maintenance_events"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"FLEET"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["perfil de veiculo","telemetria de uso","manutencao preventiva"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["gestor de frota","motorista","tecnico de manutencao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"FLEET::fleet.telemetry.alerted","type":"object"}'::JSONB, 'contracts/events/priority-domains/logistics_erp_operations.json')
)
INSERT INTO domain_event_contracts (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
)
SELECT
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
FROM contract_source
ON CONFLICT (contract_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    module_code = EXCLUDED.module_code,
    event_topic = EXCLUDED.event_topic,
    contract_version = EXCLUDED.contract_version,
    producer_surface = EXCLUDED.producer_surface,
    consumer_surfaces = EXCLUDED.consumer_surfaces,
    evidence_entities = EXCLUDED.evidence_entities,
    compliance_tags = EXCLUDED.compliance_tags,
    contract_status = EXCLUDED.contract_status,
    payload_schema_json = EXCLUDED.payload_schema_json,
    artifact_path = EXCLUDED.artifact_path,
    updated_at = NOW();

COMMIT;
