BEGIN;

-- Seed operacional idempotente dos pacotes fisicos por dominio prioritario.
-- Gerado automaticamente por scripts/valley_module_automation.py.

WITH package_source (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
) AS (
    VALUES
    ('media_social_growth.priority.v1', 'media_social_growth', 'Media Social Growth', 2, 'priority_domains_v1', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"artifacts":[{"artifact_key":"media_social_growth.ddl.v1","artifact_path":"database/domain-delivery/priority-domains/media_social_growth/ddl_complement.sql","layer_type":"DDL_COMPLEMENT","target_engine":"postgres"},{"artifact_key":"media_social_growth.seed.v1","artifact_path":"database/domain-delivery/priority-domains/media_social_growth/operational_seed.sql","layer_type":"OPERATIONS_SEED","target_engine":"postgres"},{"artifact_key":"media_social_growth.contract.v1","artifact_path":"contracts/events/priority-domains/media_social_growth.json","layer_type":"EVENT_CONTRACT","target_engine":"filesystem"}],"backlog_keys":["INFLUENCERS.exec.01","INFLUENCERS.exec.02","SOCIAL.exec.01","SOCIAL.exec.02","MEDIA.exec.01","MEDIA.exec.02","ADS.exec.01","ADS.exec.02","INFLUENCERS.exec.03","SOCIAL.exec.03","MEDIA.exec.03","NEWS_PODCAST.exec.01","NEWS_PODCAST.exec.02","ADS.exec.03","GAMING.exec.01","GAMING.exec.02","NEWS_PODCAST.exec.03","GAMING.exec.03"],"domain_key":"media_social_growth","domain_label":"Media Social Growth","event_topics":["influencer.profile.qualified","influencer.metric.ingested","influencer.commission.attributed","social.post.published","social.report.opened","social.reputation.updated","media.upload.received","media.asset.published","media.revenue.booked","ads.campaign.launched","ads.impression.attributed","ads.reward.booked","news.story.published","podcast.episode.released","media.content.moderated","gaming.player.progressed","gaming.reward.unlocked","gaming.quest.completed"],"modules":["INFLUENCERS","SOCIAL","MEDIA","ADS","NEWS_PODCAST","GAMING"],"package_key":"media_social_growth.priority.v1","priority_rank":2}'::JSONB)
)
INSERT INTO domain_delivery_packages (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
)
SELECT
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
FROM package_source
ON CONFLICT (package_key) DO UPDATE SET
    domain_key = EXCLUDED.domain_key,
    domain_label = EXCLUDED.domain_label,
    priority_rank = EXCLUDED.priority_rank,
    package_scope = EXCLUDED.package_scope,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    package_status = EXCLUDED.package_status,
    artifact_manifest_json = EXCLUDED.artifact_manifest_json,
    updated_at = NOW();

WITH artifact_source (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
) AS (
    VALUES
    ('media_social_growth.ddl.v1', 'media_social_growth.priority.v1', 'media_social_growth', 'DDL_COMPLEMENT'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/media_social_growth/ddl_complement.sql', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], ARRAY[]::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"package_key":"media_social_growth.priority.v1","priority_rank":2,"views":["v_media_social_growth_creator_ops","v_media_social_growth_ads_reward_ops","v_media_social_growth_referral_ops","v_media_social_growth_gaming_ops"]}'::JSONB),
    ('media_social_growth.seed.v1', 'media_social_growth.priority.v1', 'media_social_growth', 'OPERATIONS_SEED'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/media_social_growth/operational_seed.sql', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], ARRAY['media_social_growth.ddl.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"contract_count":18,"package_key":"media_social_growth.priority.v1","seed_scope":"priority_domain_delivery_v1"}'::JSONB),
    ('media_social_growth.contract.v1', 'media_social_growth.priority.v1', 'media_social_growth', 'EVENT_CONTRACT'::domain_delivery_layer_enum, 'filesystem', 'contracts/events/priority-domains/media_social_growth.json', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], ARRAY['media_social_growth.ddl.v1', 'media_social_growth.seed.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"event_topics":["influencer.profile.qualified","influencer.metric.ingested","influencer.commission.attributed","social.post.published","social.report.opened","social.reputation.updated","media.upload.received","media.asset.published","media.revenue.booked","ads.campaign.launched","ads.impression.attributed","ads.reward.booked","news.story.published","podcast.episode.released","media.content.moderated","gaming.player.progressed","gaming.reward.unlocked","gaming.quest.completed"],"package_key":"media_social_growth.priority.v1"}'::JSONB)
)
INSERT INTO domain_delivery_artifacts (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
)
SELECT
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
FROM artifact_source
ON CONFLICT (artifact_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    layer_type = EXCLUDED.layer_type,
    target_engine = EXCLUDED.target_engine,
    artifact_path = EXCLUDED.artifact_path,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    depends_on_keys = EXCLUDED.depends_on_keys,
    artifact_status = EXCLUDED.artifact_status,
    artifact_payload_json = EXCLUDED.artifact_payload_json,
    updated_at = NOW();

WITH contract_source (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
) AS (
    VALUES
    ('INFLUENCERS:influencer.profile.qualified:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'INFLUENCERS', 'influencer.profile.qualified', '1.0.0', 'painel de creators', ARRAY['SOCIAL', 'ADS', 'painel de creators', 'fila de brand safety']::TEXT[], ARRAY['creator_uploads', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['creator_disclosure', 'commission_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["creator_disclosure","commission_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"influencer.profile.qualified"},"evidence_refs":{"items":{"enum":["creator_uploads","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INFLUENCERS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["creator","brand manager","operador de afiliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INFLUENCERS::influencer.profile.qualified","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('INFLUENCERS:influencer.metric.ingested:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'INFLUENCERS', 'influencer.metric.ingested', '1.0.0', 'painel de creators', ARRAY['SOCIAL', 'ADS', 'painel de creators', 'fila de brand safety']::TEXT[], ARRAY['creator_uploads', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['creator_disclosure', 'commission_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["creator_disclosure","commission_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"influencer.metric.ingested"},"evidence_refs":{"items":{"enum":["creator_uploads","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INFLUENCERS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["creator","brand manager","operador de afiliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INFLUENCERS::influencer.metric.ingested","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('INFLUENCERS:influencer.commission.attributed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'INFLUENCERS', 'influencer.commission.attributed', '1.0.0', 'painel de creators', ARRAY['SOCIAL', 'ADS', 'painel de creators', 'fila de brand safety']::TEXT[], ARRAY['creator_uploads', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['creator_disclosure', 'commission_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["creator_disclosure","commission_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"influencer.commission.attributed"},"evidence_refs":{"items":{"enum":["creator_uploads","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INFLUENCERS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["creator","brand manager","operador de afiliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INFLUENCERS::influencer.commission.attributed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('SOCIAL:social.post.published:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'SOCIAL', 'social.post.published', '1.0.0', 'painel de moderacao', ARRAY['EVENTS', 'ADS', 'CREATOR', 'painel de moderacao', 'fila de denuncias']::TEXT[], ARRAY['social_videos', 'ai_memory']::TEXT[], ARRAY['content_moderation', 'community_safety', 'privacy_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["content_moderation","community_safety","privacy_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"social.post.published"},"evidence_refs":{"items":{"enum":["social_videos","ai_memory"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SOCIAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["feed de bairro","reputacao social","moderacao contextual"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["morador","moderador","comerciante local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SOCIAL::social.post.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('SOCIAL:social.report.opened:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'SOCIAL', 'social.report.opened', '1.0.0', 'painel de moderacao', ARRAY['EVENTS', 'ADS', 'CREATOR', 'painel de moderacao', 'fila de denuncias']::TEXT[], ARRAY['social_videos', 'ai_memory']::TEXT[], ARRAY['content_moderation', 'community_safety', 'privacy_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["content_moderation","community_safety","privacy_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"social.report.opened"},"evidence_refs":{"items":{"enum":["social_videos","ai_memory"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SOCIAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["feed de bairro","reputacao social","moderacao contextual"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["morador","moderador","comerciante local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SOCIAL::social.report.opened","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('SOCIAL:social.reputation.updated:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'SOCIAL', 'social.reputation.updated', '1.0.0', 'painel de moderacao', ARRAY['EVENTS', 'ADS', 'CREATOR', 'painel de moderacao', 'fila de denuncias']::TEXT[], ARRAY['social_videos', 'ai_memory']::TEXT[], ARRAY['content_moderation', 'community_safety', 'privacy_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["content_moderation","community_safety","privacy_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"social.reputation.updated"},"evidence_refs":{"items":{"enum":["social_videos","ai_memory"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SOCIAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["feed de bairro","reputacao social","moderacao contextual"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["morador","moderador","comerciante local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SOCIAL::social.reputation.updated","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('MEDIA:media.upload.received:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'MEDIA', 'media.upload.received', '1.0.0', 'studio de creator', ARRAY['SOCIAL', 'ADS', 'studio de creator', 'fila de publicacao']::TEXT[], ARRAY['creator_uploads', 'transactions', 'social_videos', 'news_content_items']::TEXT[], ARRAY['copyright_traceability', 'creator_payout_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["copyright_traceability","creator_payout_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.upload.received"},"evidence_refs":{"items":{"enum":["creator_uploads","transactions","social_videos","news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MEDIA"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["upload de creator","monetizacao","distribuicao de conteudo"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","operador de midia","marca"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MEDIA::media.upload.received","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('MEDIA:media.asset.published:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'MEDIA', 'media.asset.published', '1.0.0', 'studio de creator', ARRAY['SOCIAL', 'ADS', 'studio de creator', 'fila de publicacao']::TEXT[], ARRAY['creator_uploads', 'transactions', 'social_videos', 'news_content_items']::TEXT[], ARRAY['copyright_traceability', 'creator_payout_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["copyright_traceability","creator_payout_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.asset.published"},"evidence_refs":{"items":{"enum":["creator_uploads","transactions","social_videos","news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MEDIA"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["upload de creator","monetizacao","distribuicao de conteudo"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","operador de midia","marca"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MEDIA::media.asset.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('MEDIA:media.revenue.booked:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'MEDIA', 'media.revenue.booked', '1.0.0', 'studio de creator', ARRAY['SOCIAL', 'ADS', 'studio de creator', 'fila de publicacao']::TEXT[], ARRAY['creator_uploads', 'transactions', 'social_videos', 'news_content_items']::TEXT[], ARRAY['copyright_traceability', 'creator_payout_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["copyright_traceability","creator_payout_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.revenue.booked"},"evidence_refs":{"items":{"enum":["creator_uploads","transactions","social_videos","news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MEDIA"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["upload de creator","monetizacao","distribuicao de conteudo"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","operador de midia","marca"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MEDIA::media.revenue.booked","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('ADS:ads.campaign.launched:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'ADS', 'ads.campaign.launched', '1.0.0', 'painel de campanhas', ARRAY['MARKETPLACE', 'ADS_INTELLIGENCE', 'painel de campanhas', 'monitor de atribuicao']::TEXT[], ARRAY['gold_campaigns', 'sale_validation_events', 'pepita_accounts', 'social_videos', 'influencer_metrics']::TEXT[], ARRAY['ad_policy_traceability', 'financial_attribution', 'geo_targeting_consent']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"ads.campaign.launched"},"evidence_refs":{"items":{"enum":["gold_campaigns","sale_validation_events","pepita_accounts","social_videos","influencer_metrics"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"ADS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["anunciante","operador de growth","merchant"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"ADS::ads.campaign.launched","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('ADS:ads.impression.attributed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'ADS', 'ads.impression.attributed', '1.0.0', 'painel de campanhas', ARRAY['MARKETPLACE', 'ADS_INTELLIGENCE', 'painel de campanhas', 'monitor de atribuicao']::TEXT[], ARRAY['gold_campaigns', 'sale_validation_events', 'pepita_accounts', 'social_videos', 'influencer_metrics']::TEXT[], ARRAY['ad_policy_traceability', 'financial_attribution', 'geo_targeting_consent']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"ads.impression.attributed"},"evidence_refs":{"items":{"enum":["gold_campaigns","sale_validation_events","pepita_accounts","social_videos","influencer_metrics"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"ADS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["anunciante","operador de growth","merchant"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"ADS::ads.impression.attributed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('ADS:ads.reward.booked:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'ADS', 'ads.reward.booked', '1.0.0', 'painel de campanhas', ARRAY['MARKETPLACE', 'ADS_INTELLIGENCE', 'painel de campanhas', 'monitor de atribuicao']::TEXT[], ARRAY['gold_campaigns', 'sale_validation_events', 'pepita_accounts', 'social_videos', 'influencer_metrics']::TEXT[], ARRAY['ad_policy_traceability', 'financial_attribution', 'geo_targeting_consent']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"ads.reward.booked"},"evidence_refs":{"items":{"enum":["gold_campaigns","sale_validation_events","pepita_accounts","social_videos","influencer_metrics"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"ADS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["anunciante","operador de growth","merchant"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"ADS::ads.reward.booked","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('NEWS_PODCAST:news.story.published:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'NEWS_PODCAST', 'news.story.published', '1.0.0', 'cms editorial', ARRAY['CREATOR', 'ADS', 'cms editorial', 'fila de revisao']::TEXT[], ARRAY['news_content_items']::TEXT[], ARRAY['editorial_governance', 'copyright_traceability', 'content_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["editorial_governance","copyright_traceability","content_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"news.story.published"},"evidence_refs":{"items":{"enum":["news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"NEWS_PODCAST"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["conteudo editorial","episodios e blocos","distribuicao midia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["editor","criador de audio","consumidor"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"NEWS_PODCAST::news.story.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('NEWS_PODCAST:podcast.episode.released:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'NEWS_PODCAST', 'podcast.episode.released', '1.0.0', 'cms editorial', ARRAY['CREATOR', 'ADS', 'cms editorial', 'fila de revisao']::TEXT[], ARRAY['news_content_items']::TEXT[], ARRAY['editorial_governance', 'copyright_traceability', 'content_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["editorial_governance","copyright_traceability","content_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"podcast.episode.released"},"evidence_refs":{"items":{"enum":["news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"NEWS_PODCAST"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["conteudo editorial","episodios e blocos","distribuicao midia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["editor","criador de audio","consumidor"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"NEWS_PODCAST::podcast.episode.released","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('NEWS_PODCAST:media.content.moderated:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'NEWS_PODCAST', 'media.content.moderated', '1.0.0', 'cms editorial', ARRAY['CREATOR', 'ADS', 'cms editorial', 'fila de revisao']::TEXT[], ARRAY['news_content_items']::TEXT[], ARRAY['editorial_governance', 'copyright_traceability', 'content_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["editorial_governance","copyright_traceability","content_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.content.moderated"},"evidence_refs":{"items":{"enum":["news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"NEWS_PODCAST"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["conteudo editorial","episodios e blocos","distribuicao midia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["editor","criador de audio","consumidor"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"NEWS_PODCAST::media.content.moderated","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('GAMING:gaming.player.progressed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'GAMING', 'gaming.player.progressed', '1.0.0', 'painel de quests', ARRAY['SOCIAL', 'CREATOR', 'painel de quests', 'monitor de rewards']::TEXT[], ARRAY['points_ledger', 'gaming_player_states', 'social_videos']::TEXT[], ARRAY['reward_audit', 'age_safety', 'community_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["reward_audit","age_safety","community_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gaming.player.progressed"},"evidence_refs":{"items":{"enum":["points_ledger","gaming_player_states","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GAMING"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["estado do jogador","gamificacao","ponte com rewards"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["player","community manager","operador de reward"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GAMING::gaming.player.progressed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('GAMING:gaming.reward.unlocked:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'GAMING', 'gaming.reward.unlocked', '1.0.0', 'painel de quests', ARRAY['SOCIAL', 'CREATOR', 'painel de quests', 'monitor de rewards']::TEXT[], ARRAY['points_ledger', 'gaming_player_states', 'social_videos']::TEXT[], ARRAY['reward_audit', 'age_safety', 'community_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["reward_audit","age_safety","community_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gaming.reward.unlocked"},"evidence_refs":{"items":{"enum":["points_ledger","gaming_player_states","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GAMING"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["estado do jogador","gamificacao","ponte com rewards"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["player","community manager","operador de reward"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GAMING::gaming.reward.unlocked","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('GAMING:gaming.quest.completed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'GAMING', 'gaming.quest.completed', '1.0.0', 'painel de quests', ARRAY['SOCIAL', 'CREATOR', 'painel de quests', 'monitor de rewards']::TEXT[], ARRAY['points_ledger', 'gaming_player_states', 'social_videos']::TEXT[], ARRAY['reward_audit', 'age_safety', 'community_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["reward_audit","age_safety","community_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gaming.quest.completed"},"evidence_refs":{"items":{"enum":["points_ledger","gaming_player_states","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GAMING"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["estado do jogador","gamificacao","ponte com rewards"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["player","community manager","operador de reward"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GAMING::gaming.quest.completed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json')
)
INSERT INTO domain_event_contracts (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
)
SELECT
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
FROM contract_source
ON CONFLICT (contract_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    module_code = EXCLUDED.module_code,
    event_topic = EXCLUDED.event_topic,
    contract_version = EXCLUDED.contract_version,
    producer_surface = EXCLUDED.producer_surface,
    consumer_surfaces = EXCLUDED.consumer_surfaces,
    evidence_entities = EXCLUDED.evidence_entities,
    compliance_tags = EXCLUDED.compliance_tags,
    contract_status = EXCLUDED.contract_status,
    payload_schema_json = EXCLUDED.payload_schema_json,
    artifact_path = EXCLUDED.artifact_path,
    updated_at = NOW();

-- Enriquecimento manual: seed operacional real do dominio media_social_growth.
SET LOCAL search_path = public;

INSERT INTO users (
    user_id,
    user_kind,
    account_status,
    kyc_status,
    full_name,
    display_name,
    email,
    phone_e164,
    birth_date,
    document_country,
    document_type,
    document_number,
    nationality,
    tax_residence_country,
    primary_role,
    module_tier,
    terms_accepted_at,
    privacy_accepted_at,
    created_at,
    updated_at
) VALUES
    (
        '10000000-0000-4000-8000-000000000601',
        'PJ'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Valley Creator Commerce Ltda',
        'Creator Commerce',
        'creator.commerce@valley.local',
        '+5511990000601',
        NULL,
        'BR',
        'CNPJ',
        '90000000000601',
        NULL,
        'BR',
        'MEDIA_MERCHANT',
        'CORE',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000602',
        'PF'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Lia Creator',
        'Lia',
        'lia.creator@valley.local',
        '+5511990000602',
        DATE '1995-11-09',
        'BR',
        'CPF',
        '90000000602',
        'BR',
        'BR',
        'CONTENT_CREATOR',
        'CORE',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000603',
        'PF'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Caio Comprador',
        'Caio',
        'caio.comprador@valley.local',
        '+5511990000603',
        DATE '1990-02-18',
        'BR',
        'CPF',
        '90000000603',
        'BR',
        'BR',
        'SOCIAL_BUYER',
        'CORE',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000604',
        'PF'::user_kind_enum,
        'ACTIVE'::account_status_enum,
        'APPROVED'::kyc_status_enum,
        'Nina Player',
        'Nina',
        'nina.player@valley.local',
        '+5511990000604',
        DATE '1998-06-01',
        'BR',
        'CPF',
        '90000000604',
        'BR',
        'BR',
        'COMMUNITY_PLAYER',
        'EXPANSION',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    )
ON CONFLICT (user_id) DO UPDATE SET
    account_status = EXCLUDED.account_status,
    kyc_status = EXCLUDED.kyc_status,
    full_name = EXCLUDED.full_name,
    display_name = EXCLUDED.display_name,
    email = EXCLUDED.email,
    phone_e164 = EXCLUDED.phone_e164,
    birth_date = EXCLUDED.birth_date,
    document_country = EXCLUDED.document_country,
    document_type = EXCLUDED.document_type,
    document_number = EXCLUDED.document_number,
    nationality = EXCLUDED.nationality,
    tax_residence_country = EXCLUDED.tax_residence_country,
    primary_role = EXCLUDED.primary_role,
    module_tier = EXCLUDED.module_tier,
    terms_accepted_at = EXCLUDED.terms_accepted_at,
    privacy_accepted_at = EXCLUDED.privacy_accepted_at,
    updated_at = EXCLUDED.updated_at;

INSERT INTO wallets (
    wallet_id,
    user_id,
    wallet_type,
    asset_code,
    wallet_status,
    balance_available_brl,
    balance_blocked_brl,
    balance_pending_brl,
    balance_available_nex,
    balance_blocked_nex,
    balance_pending_nex,
    daily_limit_brl,
    monthly_limit_brl,
    created_at,
    updated_at
) VALUES
    (
        '20000000-0000-4000-8000-000000000601',
        '10000000-0000-4000-8000-000000000601',
        'CUSTODIAL'::wallet_type_enum,
        'BRL'::wallet_asset_enum,
        'ACTIVE'::wallet_status_enum,
        25000.0000,
        0.0000,
        0.0000,
        0.00000000,
        0.00000000,
        0.00000000,
        60000.0000,
        900000.0000,
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    ),
    (
        '20000000-0000-4000-8000-000000000602',
        '10000000-0000-4000-8000-000000000602',
        'CUSTODIAL'::wallet_type_enum,
        'BRL'::wallet_asset_enum,
        'ACTIVE'::wallet_status_enum,
        1200.0000,
        0.0000,
        0.0000,
        0.00000000,
        0.00000000,
        0.00000000,
        4000.0000,
        50000.0000,
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    ),
    (
        '20000000-0000-4000-8000-000000000603',
        '10000000-0000-4000-8000-000000000603',
        'CUSTODIAL'::wallet_type_enum,
        'BRL'::wallet_asset_enum,
        'ACTIVE'::wallet_status_enum,
        900.0000,
        0.0000,
        0.0000,
        0.00000000,
        0.00000000,
        0.00000000,
        2000.0000,
        25000.0000,
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    ),
    (
        '20000000-0000-4000-8000-000000000604',
        '10000000-0000-4000-8000-000000000604',
        'CUSTODIAL'::wallet_type_enum,
        'BRL'::wallet_asset_enum,
        'ACTIVE'::wallet_status_enum,
        300.0000,
        0.0000,
        0.0000,
        0.00000000,
        0.00000000,
        0.00000000,
        1000.0000,
        10000.0000,
        TIMESTAMPTZ '2026-04-21 13:00:00+00',
        TIMESTAMPTZ '2026-04-21 13:00:00+00'
    )
ON CONFLICT (wallet_id) DO UPDATE SET
    wallet_status = EXCLUDED.wallet_status,
    balance_available_brl = EXCLUDED.balance_available_brl,
    balance_blocked_brl = EXCLUDED.balance_blocked_brl,
    balance_pending_brl = EXCLUDED.balance_pending_brl,
    balance_available_nex = EXCLUDED.balance_available_nex,
    balance_blocked_nex = EXCLUDED.balance_blocked_nex,
    balance_pending_nex = EXCLUDED.balance_pending_nex,
    daily_limit_brl = EXCLUDED.daily_limit_brl,
    monthly_limit_brl = EXCLUDED.monthly_limit_brl,
    updated_at = EXCLUDED.updated_at;

INSERT INTO creator_uploads (
    upload_id,
    user_id,
    file_url,
    upload_status,
    monetization_enabled,
    social_video_id,
    checksum_sha256,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000801',
    '10000000-0000-4000-8000-000000000602',
    'https://cdn.valley.local/media/creator/lia-cidade-inteligente.mp4',
    'ACTIVE'::creator_upload_status_enum,
    TRUE,
    'social-video-media-001',
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    TIMESTAMPTZ '2026-04-21 13:05:00+00',
    TIMESTAMPTZ '2026-04-21 13:18:00+00'
)
ON CONFLICT (upload_id) DO UPDATE SET
    file_url = EXCLUDED.file_url,
    upload_status = EXCLUDED.upload_status,
    monetization_enabled = EXCLUDED.monetization_enabled,
    social_video_id = EXCLUDED.social_video_id,
    checksum_sha256 = EXCLUDED.checksum_sha256,
    updated_at = EXCLUDED.updated_at;

INSERT INTO orders (
    order_id,
    user_id,
    wallet_id,
    order_domain,
    order_status,
    merchant_user_id,
    affiliate_user_id,
    source_channel,
    currency_code,
    subtotal_brl,
    delivery_fee_brl,
    service_fee_brl,
    discount_brl,
    tax_brl,
    total_brl,
    total_nex,
    supplier_name,
    customer_notes,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000802',
    '10000000-0000-4000-8000-000000000603',
    '20000000-0000-4000-8000-000000000603',
    'DROPSHIP'::order_domain_enum,
    'COMPLETED'::order_status_enum,
    '10000000-0000-4000-8000-000000000601',
    '10000000-0000-4000-8000-000000000602',
    'SOCIAL',
    'BRL',
    80.0000,
    0.0000,
    0.0000,
    0.0000,
    0.0000,
    80.0000,
    0.00000000,
    'Creator Commerce Fulfillment',
    'Compra originada a partir de conteudo do creator seedado.',
    TIMESTAMPTZ '2026-04-21 13:10:00+00',
    TIMESTAMPTZ '2026-04-21 13:18:00+00'
)
ON CONFLICT (order_id) DO UPDATE SET
    order_status = EXCLUDED.order_status,
    subtotal_brl = EXCLUDED.subtotal_brl,
    total_brl = EXCLUDED.total_brl,
    affiliate_user_id = EXCLUDED.affiliate_user_id,
    customer_notes = EXCLUDED.customer_notes,
    updated_at = EXCLUDED.updated_at;

INSERT INTO transactions (
    transaction_id,
    user_id,
    wallet_id,
    counterparty_user_id,
    counterparty_wallet_id,
    transaction_type,
    transaction_status,
    order_id,
    asset_code,
    amount_brl,
    amount_nex,
    fee_amount_brl,
    platform_amount_brl,
    merchant_amount_brl,
    affiliate_amount_brl,
    escrow_amount_brl,
    fx_rate,
    reference_code,
    external_reference,
    channel,
    origin_module,
    description,
    metadata_json,
    authorized_at,
    settled_at,
    failed_at,
    created_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000803',
        '10000000-0000-4000-8000-000000000603',
        '20000000-0000-4000-8000-000000000603',
        '10000000-0000-4000-8000-000000000601',
        '20000000-0000-4000-8000-000000000601',
        'PAYMENT'::transaction_type_enum,
        'SETTLED'::transaction_status_enum,
        '30000000-0000-4000-8000-000000000802',
        'BRL'::wallet_asset_enum,
        80.0000,
        0.00000000,
        0.0000,
        10.0000,
        70.0000,
        0.0000,
        0.0000,
        NULL,
        'TX-MEDIA-ORDER-001',
        'media-order-001',
        'creator_app',
        'ADS',
        'Pagamento de compra atribuida a creator seedado.',
        '{"domain":"media_social_growth","flow":"social_conversion"}'::JSONB,
        TIMESTAMPTZ '2026-04-21 13:12:00+00',
        TIMESTAMPTZ '2026-04-21 13:13:00+00',
        NULL,
        TIMESTAMPTZ '2026-04-21 13:12:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000804',
        '10000000-0000-4000-8000-000000000602',
        '20000000-0000-4000-8000-000000000602',
        '10000000-0000-4000-8000-000000000601',
        '20000000-0000-4000-8000-000000000601',
        'PAYOUT'::transaction_type_enum,
        'SETTLED'::transaction_status_enum,
        NULL,
        'BRL'::wallet_asset_enum,
        45.0000,
        0.00000000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        0.0000,
        NULL,
        'TX-MEDIA-PAYOUT-001',
        'creator-revenue-001',
        'studio_creator',
        'MEDIA',
        'Repasse de monetizacao para creator seedado.',
        '{"domain":"media_social_growth","flow":"creator_revenue"}'::JSONB,
        TIMESTAMPTZ '2026-04-21 13:16:00+00',
        TIMESTAMPTZ '2026-04-21 13:17:00+00',
        NULL,
        TIMESTAMPTZ '2026-04-21 13:16:00+00'
    )
ON CONFLICT (transaction_id) DO NOTHING;

INSERT INTO affiliate_referrals (
    referral_id,
    referrer_id,
    order_id,
    purchase_transaction_id,
    commission_amount_brl,
    payout_at,
    created_at
) VALUES (
    '30000000-0000-4000-8000-000000000805',
    '10000000-0000-4000-8000-000000000602',
    '30000000-0000-4000-8000-000000000802',
    '30000000-0000-4000-8000-000000000803',
    8.0000,
    TIMESTAMPTZ '2026-04-21 13:18:00+00',
    TIMESTAMPTZ '2026-04-21 13:18:00+00'
)
ON CONFLICT (referral_id) DO NOTHING;

INSERT INTO gamification_campaigns (
    campaign_id,
    module_code,
    campaign_name,
    description,
    start_date,
    end_date,
    reward_type,
    target_audience_json,
    approval_status,
    created_by_admin_id,
    created_at,
    updated_at
) VALUES
    (
        '30000000-0000-4000-8000-000000000806',
        'ADS',
        'Creator Boost Geo Reward',
        'Campanha GOLD para creator local com grant em Pepita.',
        DATE '2026-04-21',
        DATE '2026-05-15',
        'PEPITA'::reward_type_enum,
        '{"segment":"creators_locales","city":"Sao Paulo"}'::JSONB,
        'ACTIVE'::campaign_status_enum,
        NULL,
        TIMESTAMPTZ '2026-04-21 13:20:00+00',
        TIMESTAMPTZ '2026-04-21 13:20:00+00'
    ),
    (
        '30000000-0000-4000-8000-000000000811',
        'GAMING',
        'Quest Bairro Creator',
        'Campanha de pontos para engajamento gamificado de comunidade.',
        DATE '2026-04-21',
        DATE '2026-05-31',
        'POINTS'::reward_type_enum,
        '{"segment":"players_bairro","community":"creator_hub"}'::JSONB,
        'ACTIVE'::campaign_status_enum,
        NULL,
        TIMESTAMPTZ '2026-04-21 13:20:00+00',
        TIMESTAMPTZ '2026-04-21 13:20:00+00'
    )
ON CONFLICT (campaign_id) DO UPDATE SET
    campaign_name = EXCLUDED.campaign_name,
    description = EXCLUDED.description,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    reward_type = EXCLUDED.reward_type,
    target_audience_json = EXCLUDED.target_audience_json,
    approval_status = EXCLUDED.approval_status,
    updated_at = EXCLUDED.updated_at;

INSERT INTO gold_campaigns (
    gold_campaign_id,
    campaign_id,
    merchant_user_id,
    wallet_id,
    module_code,
    campaign_type,
    campaign_status,
    campaign_name,
    objective,
    target_storefront_id,
    target_zone_id,
    budget_brl,
    valley_revenue_brl,
    pepita_pool_brl,
    minimum_ticket_brl,
    target_geo_json,
    target_radius_km,
    starts_at,
    ends_at,
    validation_window_minutes,
    metadata_json,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000807',
    '30000000-0000-4000-8000-000000000806',
    '10000000-0000-4000-8000-000000000601',
    '20000000-0000-4000-8000-000000000601',
    'ADS',
    'GEO_VISIT'::gold_campaign_type_enum,
    'ACTIVE'::gold_campaign_status_enum,
    'Creator Boost Geo Reward',
    'Atribuir Pepita para creator com midia de bairro convertida.',
    NULL,
    NULL,
    400.0000,
    120.0000,
    200.0000,
    0.0000,
    '{"city":"Sao Paulo","district":"Paulista"}'::JSONB,
    5.0000,
    TIMESTAMPTZ '2026-04-21 13:22:00+00',
    TIMESTAMPTZ '2026-05-15 23:59:00+00',
    30,
    '{"channel":"creator_hub","domain":"media_social_growth"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 13:22:00+00',
    TIMESTAMPTZ '2026-04-21 13:22:00+00'
)
ON CONFLICT (gold_campaign_id) DO UPDATE SET
    campaign_status = EXCLUDED.campaign_status,
    campaign_name = EXCLUDED.campaign_name,
    objective = EXCLUDED.objective,
    budget_brl = EXCLUDED.budget_brl,
    valley_revenue_brl = EXCLUDED.valley_revenue_brl,
    pepita_pool_brl = EXCLUDED.pepita_pool_brl,
    minimum_ticket_brl = EXCLUDED.minimum_ticket_brl,
    target_geo_json = EXCLUDED.target_geo_json,
    target_radius_km = EXCLUDED.target_radius_km,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    validation_window_minutes = EXCLUDED.validation_window_minutes,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = EXCLUDED.updated_at;

INSERT INTO gold_campaign_events (
    gold_campaign_event_id,
    gold_campaign_id,
    sale_validation_id,
    candidate_user_id,
    merchant_user_id,
    order_id,
    transaction_id,
    event_type,
    event_status,
    gold_amount_brl,
    pepita_amount_brl,
    valley_revenue_amount_brl,
    reason_code,
    payload_json,
    created_at
) VALUES (
    '30000000-0000-4000-8000-000000000808',
    '30000000-0000-4000-8000-000000000807',
    NULL,
    '10000000-0000-4000-8000-000000000602',
    '10000000-0000-4000-8000-000000000601',
    NULL,
    NULL,
    'PEPITA_GRANT'::gold_event_type_enum,
    'SETTLED'::gold_event_status_enum,
    0.0000,
    30.0000,
    0.0000,
    'CREATOR_ENGAGEMENT',
    '{"surface":"creator_hub","evidence":"seed_reward"}'::JSONB,
    TIMESTAMPTZ '2026-04-21 13:24:00+00'
)
ON CONFLICT (gold_campaign_event_id) DO NOTHING;

INSERT INTO pepita_accounts (
    pepita_account_id,
    user_id,
    account_status,
    current_balance_brl,
    lifetime_earned_brl,
    lifetime_redeemed_brl,
    lifetime_expired_brl,
    last_activity_at,
    created_at,
    updated_at
) VALUES (
    '30000000-0000-4000-8000-000000000809',
    '10000000-0000-4000-8000-000000000602',
    'ACTIVE'::pepita_account_status_enum,
    0.0000,
    0.0000,
    0.0000,
    0.0000,
    NULL,
    TIMESTAMPTZ '2026-04-21 13:24:30+00',
    TIMESTAMPTZ '2026-04-21 13:24:30+00'
)
ON CONFLICT (pepita_account_id) DO UPDATE SET
    account_status = EXCLUDED.account_status,
    updated_at = EXCLUDED.updated_at;

INSERT INTO pepita_ledger (
    pepita_ledger_id,
    pepita_account_id,
    user_id,
    campaign_id,
    gold_campaign_id,
    gold_campaign_event_id,
    sale_validation_id,
    order_id,
    transaction_id,
    entry_type,
    amount_brl,
    balance_after_brl,
    reason_code,
    description,
    expires_at,
    created_at
) VALUES (
    '30000000-0000-4000-8000-000000000810',
    '30000000-0000-4000-8000-000000000809',
    '10000000-0000-4000-8000-000000000602',
    '30000000-0000-4000-8000-000000000806',
    '30000000-0000-4000-8000-000000000807',
    '30000000-0000-4000-8000-000000000808',
    NULL,
    NULL,
    NULL,
    'GOLD_CONVERSION'::pepita_entry_type_enum,
    30.0000,
    0.0000,
    'CREATOR_ENGAGEMENT',
    'Grant de Pepita para creator seedado.',
    TIMESTAMPTZ '2026-06-30 23:59:00+00',
    TIMESTAMPTZ '2026-04-21 13:25:00+00'
)
ON CONFLICT (pepita_ledger_id) DO NOTHING;

INSERT INTO points_ledger (
    points_ledger_id,
    user_id,
    campaign_id,
    points,
    reason,
    granted_at,
    expires_at
) VALUES (
    '30000000-0000-4000-8000-000000000812',
    '10000000-0000-4000-8000-000000000604',
    '30000000-0000-4000-8000-000000000811',
    120,
    'Quest de bairro concluida em circuito de creator seedado.',
    TIMESTAMPTZ '2026-04-21 13:26:00+00',
    TIMESTAMPTZ '2026-05-31 23:59:00+00'
)
ON CONFLICT (points_ledger_id) DO NOTHING;

COMMIT;
