BEGIN;

-- Seed operacional idempotente dos pacotes fisicos por dominio prioritario.
-- Gerado automaticamente por scripts/valley_module_automation.py.

WITH package_source (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
) AS (
    VALUES
    ('media_social_growth.priority.v1', 'media_social_growth', 'Media Social Growth', 2, 'priority_domains_v1', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"artifacts":[{"artifact_key":"media_social_growth.ddl.v1","artifact_path":"database/domain-delivery/priority-domains/media_social_growth/ddl_complement.sql","layer_type":"DDL_COMPLEMENT","target_engine":"postgres"},{"artifact_key":"media_social_growth.seed.v1","artifact_path":"database/domain-delivery/priority-domains/media_social_growth/operational_seed.sql","layer_type":"OPERATIONS_SEED","target_engine":"postgres"},{"artifact_key":"media_social_growth.contract.v1","artifact_path":"contracts/events/priority-domains/media_social_growth.json","layer_type":"EVENT_CONTRACT","target_engine":"filesystem"}],"backlog_keys":["INFLUENCERS.exec.01","INFLUENCERS.exec.02","SOCIAL.exec.01","SOCIAL.exec.02","MEDIA.exec.01","MEDIA.exec.02","ADS.exec.01","ADS.exec.02","INFLUENCERS.exec.03","SOCIAL.exec.03","MEDIA.exec.03","NEWS_PODCAST.exec.01","NEWS_PODCAST.exec.02","ADS.exec.03","GAMING.exec.01","GAMING.exec.02","NEWS_PODCAST.exec.03","GAMING.exec.03"],"domain_key":"media_social_growth","domain_label":"Media Social Growth","event_topics":["influencer.profile.qualified","influencer.metric.ingested","influencer.commission.attributed","social.post.published","social.report.opened","social.reputation.updated","media.upload.received","media.asset.published","media.revenue.booked","ads.campaign.launched","ads.impression.attributed","ads.reward.booked","news.story.published","podcast.episode.released","media.content.moderated","gaming.player.progressed","gaming.reward.unlocked","gaming.quest.completed"],"modules":["INFLUENCERS","SOCIAL","MEDIA","ADS","NEWS_PODCAST","GAMING"],"package_key":"media_social_growth.priority.v1","priority_rank":2}'::JSONB)
)
INSERT INTO domain_delivery_packages (
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
)
SELECT
    package_key,
    domain_key,
    domain_label,
    priority_rank,
    package_scope,
    module_codes,
    backlog_keys,
    package_status,
    artifact_manifest_json
FROM package_source
ON CONFLICT (package_key) DO UPDATE SET
    domain_key = EXCLUDED.domain_key,
    domain_label = EXCLUDED.domain_label,
    priority_rank = EXCLUDED.priority_rank,
    package_scope = EXCLUDED.package_scope,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    package_status = EXCLUDED.package_status,
    artifact_manifest_json = EXCLUDED.artifact_manifest_json,
    updated_at = NOW();

WITH artifact_source (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
) AS (
    VALUES
    ('media_social_growth.ddl.v1', 'media_social_growth.priority.v1', 'media_social_growth', 'DDL_COMPLEMENT'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/media_social_growth/ddl_complement.sql', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], ARRAY[]::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"package_key":"media_social_growth.priority.v1","priority_rank":2,"views":["v_media_social_growth_priority_backlog","v_media_social_growth_delivery_artifacts","v_media_social_growth_event_contracts"]}'::JSONB),
    ('media_social_growth.seed.v1', 'media_social_growth.priority.v1', 'media_social_growth', 'OPERATIONS_SEED'::domain_delivery_layer_enum, 'postgres', 'database/domain-delivery/priority-domains/media_social_growth/operational_seed.sql', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], ARRAY['media_social_growth.ddl.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"contract_count":18,"package_key":"media_social_growth.priority.v1","seed_scope":"priority_domain_delivery_v1"}'::JSONB),
    ('media_social_growth.contract.v1', 'media_social_growth.priority.v1', 'media_social_growth', 'EVENT_CONTRACT'::domain_delivery_layer_enum, 'filesystem', 'contracts/events/priority-domains/media_social_growth.json', ARRAY['INFLUENCERS', 'SOCIAL', 'MEDIA', 'ADS', 'NEWS_PODCAST', 'GAMING']::TEXT[], ARRAY['INFLUENCERS.exec.01', 'INFLUENCERS.exec.02', 'SOCIAL.exec.01', 'SOCIAL.exec.02', 'MEDIA.exec.01', 'MEDIA.exec.02', 'ADS.exec.01', 'ADS.exec.02', 'INFLUENCERS.exec.03', 'SOCIAL.exec.03', 'MEDIA.exec.03', 'NEWS_PODCAST.exec.01', 'NEWS_PODCAST.exec.02', 'ADS.exec.03', 'GAMING.exec.01', 'GAMING.exec.02', 'NEWS_PODCAST.exec.03', 'GAMING.exec.03']::TEXT[], ARRAY['media_social_growth.ddl.v1', 'media_social_growth.seed.v1']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"event_topics":["influencer.profile.qualified","influencer.metric.ingested","influencer.commission.attributed","social.post.published","social.report.opened","social.reputation.updated","media.upload.received","media.asset.published","media.revenue.booked","ads.campaign.launched","ads.impression.attributed","ads.reward.booked","news.story.published","podcast.episode.released","media.content.moderated","gaming.player.progressed","gaming.reward.unlocked","gaming.quest.completed"],"package_key":"media_social_growth.priority.v1"}'::JSONB)
)
INSERT INTO domain_delivery_artifacts (
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
)
SELECT
    artifact_key,
    package_key,
    domain_key,
    layer_type,
    target_engine,
    artifact_path,
    module_codes,
    backlog_keys,
    depends_on_keys,
    artifact_status,
    artifact_payload_json
FROM artifact_source
ON CONFLICT (artifact_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    layer_type = EXCLUDED.layer_type,
    target_engine = EXCLUDED.target_engine,
    artifact_path = EXCLUDED.artifact_path,
    module_codes = EXCLUDED.module_codes,
    backlog_keys = EXCLUDED.backlog_keys,
    depends_on_keys = EXCLUDED.depends_on_keys,
    artifact_status = EXCLUDED.artifact_status,
    artifact_payload_json = EXCLUDED.artifact_payload_json,
    updated_at = NOW();

WITH contract_source (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
) AS (
    VALUES
    ('INFLUENCERS:influencer.profile.qualified:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'INFLUENCERS', 'influencer.profile.qualified', '1.0.0', 'painel de creators', ARRAY['SOCIAL', 'ADS', 'painel de creators', 'fila de brand safety']::TEXT[], ARRAY['creator_uploads', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['creator_disclosure', 'commission_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["creator_disclosure","commission_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"influencer.profile.qualified"},"evidence_refs":{"items":{"enum":["creator_uploads","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INFLUENCERS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["creator","brand manager","operador de afiliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INFLUENCERS::influencer.profile.qualified","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('INFLUENCERS:influencer.metric.ingested:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'INFLUENCERS', 'influencer.metric.ingested', '1.0.0', 'painel de creators', ARRAY['SOCIAL', 'ADS', 'painel de creators', 'fila de brand safety']::TEXT[], ARRAY['creator_uploads', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['creator_disclosure', 'commission_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["creator_disclosure","commission_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"influencer.metric.ingested"},"evidence_refs":{"items":{"enum":["creator_uploads","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INFLUENCERS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["creator","brand manager","operador de afiliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INFLUENCERS::influencer.metric.ingested","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('INFLUENCERS:influencer.commission.attributed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'INFLUENCERS', 'influencer.commission.attributed', '1.0.0', 'painel de creators', ARRAY['SOCIAL', 'ADS', 'painel de creators', 'fila de brand safety']::TEXT[], ARRAY['creator_uploads', 'influencer_metrics', 'social_videos']::TEXT[], ARRAY['creator_disclosure', 'commission_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["creator_disclosure","commission_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"influencer.commission.attributed"},"evidence_refs":{"items":{"enum":["creator_uploads","influencer_metrics","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"INFLUENCERS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["hub de criadores","metricas de audiencia","monetizacao afiliada"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["creator","brand manager","operador de afiliacao"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"INFLUENCERS::influencer.commission.attributed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('SOCIAL:social.post.published:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'SOCIAL', 'social.post.published', '1.0.0', 'painel de moderacao', ARRAY['EVENTS', 'ADS', 'CREATOR', 'painel de moderacao', 'fila de denuncias']::TEXT[], ARRAY['social_videos', 'ai_memory']::TEXT[], ARRAY['content_moderation', 'community_safety', 'privacy_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["content_moderation","community_safety","privacy_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"social.post.published"},"evidence_refs":{"items":{"enum":["social_videos","ai_memory"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SOCIAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["feed de bairro","reputacao social","moderacao contextual"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["morador","moderador","comerciante local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SOCIAL::social.post.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('SOCIAL:social.report.opened:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'SOCIAL', 'social.report.opened', '1.0.0', 'painel de moderacao', ARRAY['EVENTS', 'ADS', 'CREATOR', 'painel de moderacao', 'fila de denuncias']::TEXT[], ARRAY['social_videos', 'ai_memory']::TEXT[], ARRAY['content_moderation', 'community_safety', 'privacy_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["content_moderation","community_safety","privacy_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"social.report.opened"},"evidence_refs":{"items":{"enum":["social_videos","ai_memory"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SOCIAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["feed de bairro","reputacao social","moderacao contextual"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["morador","moderador","comerciante local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SOCIAL::social.report.opened","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('SOCIAL:social.reputation.updated:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'SOCIAL', 'social.reputation.updated', '1.0.0', 'painel de moderacao', ARRAY['EVENTS', 'ADS', 'CREATOR', 'painel de moderacao', 'fila de denuncias']::TEXT[], ARRAY['social_videos', 'ai_memory']::TEXT[], ARRAY['content_moderation', 'community_safety', 'privacy_controls']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["content_moderation","community_safety","privacy_controls"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"social.reputation.updated"},"evidence_refs":{"items":{"enum":["social_videos","ai_memory"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"SOCIAL"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["feed de bairro","reputacao social","moderacao contextual"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["morador","moderador","comerciante local"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"SOCIAL::social.reputation.updated","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('MEDIA:media.upload.received:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'MEDIA', 'media.upload.received', '1.0.0', 'studio de creator', ARRAY['SOCIAL', 'ADS', 'studio de creator', 'fila de publicacao']::TEXT[], ARRAY['creator_uploads', 'transactions', 'social_videos', 'news_content_items']::TEXT[], ARRAY['copyright_traceability', 'creator_payout_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["copyright_traceability","creator_payout_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.upload.received"},"evidence_refs":{"items":{"enum":["creator_uploads","transactions","social_videos","news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MEDIA"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["upload de creator","monetizacao","distribuicao de conteudo"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","operador de midia","marca"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MEDIA::media.upload.received","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('MEDIA:media.asset.published:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'MEDIA', 'media.asset.published', '1.0.0', 'studio de creator', ARRAY['SOCIAL', 'ADS', 'studio de creator', 'fila de publicacao']::TEXT[], ARRAY['creator_uploads', 'transactions', 'social_videos', 'news_content_items']::TEXT[], ARRAY['copyright_traceability', 'creator_payout_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["copyright_traceability","creator_payout_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.asset.published"},"evidence_refs":{"items":{"enum":["creator_uploads","transactions","social_videos","news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MEDIA"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["upload de creator","monetizacao","distribuicao de conteudo"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","operador de midia","marca"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MEDIA::media.asset.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('MEDIA:media.revenue.booked:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'MEDIA', 'media.revenue.booked', '1.0.0', 'studio de creator', ARRAY['SOCIAL', 'ADS', 'studio de creator', 'fila de publicacao']::TEXT[], ARRAY['creator_uploads', 'transactions', 'social_videos', 'news_content_items']::TEXT[], ARRAY['copyright_traceability', 'creator_payout_audit', 'brand_safety']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["copyright_traceability","creator_payout_audit","brand_safety"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"BUILD"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.revenue.booked"},"evidence_refs":{"items":{"enum":["creator_uploads","transactions","social_videos","news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"MEDIA"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["upload de creator","monetizacao","distribuicao de conteudo"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["criador","operador de midia","marca"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"MEDIA::media.revenue.booked","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('ADS:ads.campaign.launched:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'ADS', 'ads.campaign.launched', '1.0.0', 'painel de campanhas', ARRAY['MARKETPLACE', 'ADS_INTELLIGENCE', 'painel de campanhas', 'monitor de atribuicao']::TEXT[], ARRAY['gold_campaigns', 'sale_validation_events', 'pepita_accounts', 'social_videos', 'influencer_metrics']::TEXT[], ARRAY['ad_policy_traceability', 'financial_attribution', 'geo_targeting_consent']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"ads.campaign.launched"},"evidence_refs":{"items":{"enum":["gold_campaigns","sale_validation_events","pepita_accounts","social_videos","influencer_metrics"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"ADS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["anunciante","operador de growth","merchant"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"ADS::ads.campaign.launched","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('ADS:ads.impression.attributed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'ADS', 'ads.impression.attributed', '1.0.0', 'painel de campanhas', ARRAY['MARKETPLACE', 'ADS_INTELLIGENCE', 'painel de campanhas', 'monitor de atribuicao']::TEXT[], ARRAY['gold_campaigns', 'sale_validation_events', 'pepita_accounts', 'social_videos', 'influencer_metrics']::TEXT[], ARRAY['ad_policy_traceability', 'financial_attribution', 'geo_targeting_consent']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"ads.impression.attributed"},"evidence_refs":{"items":{"enum":["gold_campaigns","sale_validation_events","pepita_accounts","social_videos","influencer_metrics"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"ADS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["anunciante","operador de growth","merchant"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"ADS::ads.impression.attributed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('ADS:ads.reward.booked:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'ADS', 'ads.reward.booked', '1.0.0', 'painel de campanhas', ARRAY['MARKETPLACE', 'ADS_INTELLIGENCE', 'painel de campanhas', 'monitor de atribuicao']::TEXT[], ARRAY['gold_campaigns', 'sale_validation_events', 'pepita_accounts', 'social_videos', 'influencer_metrics']::TEXT[], ARRAY['ad_policy_traceability', 'financial_attribution', 'geo_targeting_consent']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["ad_policy_traceability","financial_attribution","geo_targeting_consent"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"ads.reward.booked"},"evidence_refs":{"items":{"enum":["gold_campaigns","sale_validation_events","pepita_accounts","social_videos","influencer_metrics"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"ADS"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["campanhas geolocalizadas","gold e pepitas","atribuicao comercial"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["anunciante","operador de growth","merchant"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"ADS::ads.reward.booked","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('NEWS_PODCAST:news.story.published:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'NEWS_PODCAST', 'news.story.published', '1.0.0', 'cms editorial', ARRAY['CREATOR', 'ADS', 'cms editorial', 'fila de revisao']::TEXT[], ARRAY['news_content_items']::TEXT[], ARRAY['editorial_governance', 'copyright_traceability', 'content_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["editorial_governance","copyright_traceability","content_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"news.story.published"},"evidence_refs":{"items":{"enum":["news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"NEWS_PODCAST"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["conteudo editorial","episodios e blocos","distribuicao midia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["editor","criador de audio","consumidor"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"NEWS_PODCAST::news.story.published","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('NEWS_PODCAST:podcast.episode.released:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'NEWS_PODCAST', 'podcast.episode.released', '1.0.0', 'cms editorial', ARRAY['CREATOR', 'ADS', 'cms editorial', 'fila de revisao']::TEXT[], ARRAY['news_content_items']::TEXT[], ARRAY['editorial_governance', 'copyright_traceability', 'content_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["editorial_governance","copyright_traceability","content_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"podcast.episode.released"},"evidence_refs":{"items":{"enum":["news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"NEWS_PODCAST"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["conteudo editorial","episodios e blocos","distribuicao midia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["editor","criador de audio","consumidor"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"NEWS_PODCAST::podcast.episode.released","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('NEWS_PODCAST:media.content.moderated:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'NEWS_PODCAST', 'media.content.moderated', '1.0.0', 'cms editorial', ARRAY['CREATOR', 'ADS', 'cms editorial', 'fila de revisao']::TEXT[], ARRAY['news_content_items']::TEXT[], ARRAY['editorial_governance', 'copyright_traceability', 'content_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["editorial_governance","copyright_traceability","content_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"media.content.moderated"},"evidence_refs":{"items":{"enum":["news_content_items"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"NEWS_PODCAST"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["conteudo editorial","episodios e blocos","distribuicao midia"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["editor","criador de audio","consumidor"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"NEWS_PODCAST::media.content.moderated","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('GAMING:gaming.player.progressed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'GAMING', 'gaming.player.progressed', '1.0.0', 'painel de quests', ARRAY['SOCIAL', 'CREATOR', 'painel de quests', 'monitor de rewards']::TEXT[], ARRAY['points_ledger', 'gaming_player_states', 'social_videos']::TEXT[], ARRAY['reward_audit', 'age_safety', 'community_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["reward_audit","age_safety","community_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gaming.player.progressed"},"evidence_refs":{"items":{"enum":["points_ledger","gaming_player_states","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GAMING"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["estado do jogador","gamificacao","ponte com rewards"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["player","community manager","operador de reward"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GAMING::gaming.player.progressed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('GAMING:gaming.reward.unlocked:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'GAMING', 'gaming.reward.unlocked', '1.0.0', 'painel de quests', ARRAY['SOCIAL', 'CREATOR', 'painel de quests', 'monitor de rewards']::TEXT[], ARRAY['points_ledger', 'gaming_player_states', 'social_videos']::TEXT[], ARRAY['reward_audit', 'age_safety', 'community_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["reward_audit","age_safety","community_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gaming.reward.unlocked"},"evidence_refs":{"items":{"enum":["points_ledger","gaming_player_states","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GAMING"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["estado do jogador","gamificacao","ponte com rewards"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["player","community manager","operador de reward"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GAMING::gaming.reward.unlocked","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json'),
    ('GAMING:gaming.quest.completed:v1', 'media_social_growth.priority.v1', 'media_social_growth', 'GAMING', 'gaming.quest.completed', '1.0.0', 'painel de quests', ARRAY['SOCIAL', 'CREATOR', 'painel de quests', 'monitor de rewards']::TEXT[], ARRAY['points_ledger', 'gaming_player_states', 'social_videos']::TEXT[], ARRAY['reward_audit', 'age_safety', 'community_moderation']::TEXT[], 'READY'::domain_delivery_package_status_enum, '{"$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"aggregate_id":{"format":"uuid","type":"string"},"aggregate_type":{"type":"string"},"compliance_tags":{"default":["reward_audit","age_safety","community_moderation"],"items":{"type":"string"},"type":"array"},"delivery_phase":{"const":"VALIDATE"},"domain_key":{"const":"media_social_growth"},"event_id":{"format":"uuid","type":"string"},"event_topic":{"const":"gaming.quest.completed"},"evidence_refs":{"items":{"enum":["points_ledger","gaming_player_states","social_videos"],"type":"string"},"minItems":1,"type":"array"},"module_code":{"const":"GAMING"},"occurred_at":{"format":"date-time","type":"string"},"payload":{"additionalProperties":true,"properties":{"capability":{"enum":["estado do jogador","gamificacao","ponte com rewards"],"type":"string"},"details":{"additionalProperties":true,"type":"object"},"primary_actor":{"enum":["player","community manager","operador de reward"],"type":"string"},"status":{"type":"string"}},"type":"object"},"trace_id":{"format":"uuid","type":"string"},"user_id":{"format":"uuid","type":"string"}},"required":["event_id","event_topic","module_code","domain_key","user_id","occurred_at","payload","evidence_refs"],"title":"GAMING::gaming.quest.completed","type":"object"}'::JSONB, 'contracts/events/priority-domains/media_social_growth.json')
)
INSERT INTO domain_event_contracts (
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
)
SELECT
    contract_key,
    package_key,
    domain_key,
    module_code,
    event_topic,
    contract_version,
    producer_surface,
    consumer_surfaces,
    evidence_entities,
    compliance_tags,
    contract_status,
    payload_schema_json,
    artifact_path
FROM contract_source
ON CONFLICT (contract_key) DO UPDATE SET
    package_key = EXCLUDED.package_key,
    domain_key = EXCLUDED.domain_key,
    module_code = EXCLUDED.module_code,
    event_topic = EXCLUDED.event_topic,
    contract_version = EXCLUDED.contract_version,
    producer_surface = EXCLUDED.producer_surface,
    consumer_surfaces = EXCLUDED.consumer_surfaces,
    evidence_entities = EXCLUDED.evidence_entities,
    compliance_tags = EXCLUDED.compliance_tags,
    contract_status = EXCLUDED.contract_status,
    payload_schema_json = EXCLUDED.payload_schema_json,
    artifact_path = EXCLUDED.artifact_path,
    updated_at = NOW();

COMMIT;
